# -*- coding: utf-8 -*-
"""AINE 2026 - TXT.4 - Transformers 2 - benmauflo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1Pnkzhbz1TxxtZdqS8uMj7Z948wS4T4

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26
---
---

**Escriba aquí su nombre y apellidos:** Benjamin Ignacio Maureira Flores

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:

* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable").
* Completar el código que esté incompleto (marcado con comentarios #TODO)

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**

---

# TEXTOS 4: **Transformers 2**
Última modificación: febrero de 2026

Ejecute la siguiente celda para descargar algunos archivos de datos que usaremos en nuestros experimentos.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q transformers datasets umap-learn accelerate tf-keras

datos_basedir = "./datos/"

import requests
import shutil
import os
from tqdm.auto import tqdm

def download_file(url, basedir):
  with requests.get(url, stream=True) as r:
      if not os.path.isdir(basedir):
        os.makedirs(basedir)
      total_length = int(r.headers.get("Content-Length"))
      filename = url.split("/")[-1].split("?")[0]
      with tqdm.wrapattr(r.raw, "read", total=total_length, desc=filename) as raw:
          with open(basedir + filename, 'wb') as output:
              shutil.copyfileobj(raw, output)

download_file('https://www.dropbox.com/s/fvq8my7o0ucnvoa/spanish_movie_reviews.csv?dl=1', datos_basedir)
download_file('https://www.dropbox.com/s/a2xzik0vyymvykw/prensa.csv?dl=1', datos_basedir)

"""## Introducción

Después de haber visto en profundidad en qué consiste el mecanismo de atención de los *transformers*, y cómo usar los *embeddings* generados por un *decoder* para hacer un clasificador de textos, en este *notebook* nos vamos a centrar en la parte más aplicada de esta tecnología.

Vamos a ver las posibilidades que nos brinda la librería 🤗 *Transformers* para tokenizar textos, utilizar modelos preentrenados para diversas tareas de PLN, y realizar un ajuste fino de los modelos preentrenados para que se adapten a las tareas que queramos definir (lo que se conoce como *transfer learning*).

## 🤗 Transformers

Aunque podemos usar sistemas como BERT cargando los modelos directamente en librerías de redes neuronales como PyTorch o TensorFlow, esto exige cierta formación y conocimiento sobre redes neuronales profundas. Al igual que Spacy nos permite utilizar analizadores de textos sin necesidad de conocer los detalles internos de los mismos, existen librerías que nos permiten utilizar los *transformers* de una manera sencilla y rápida. Nosotros utilizaremos *Transformers* de la compañía [Hugging Face](https://huggingface.co/) (suele sustituirse el nombre de la compañía, *Hugging Face*, por un emoticono 🤗, de manera que la librería anterior se suele referenciar como 🤗 *Transformers*).

🤗 *Transformers* incluye un montón de modelos preentrenados, tanto los originales más populares como BERT, como modelos *afinados* para multitud de tareas concretas. En este caso, se trata de modelos aportados por compañías o desarrolladores independientes, que son ofrecidos gratuitamente a modo de repositorio. Estos modelos se pueden cargar y utilizar de una forma muy sencilla. También es posible escoger nuestro modelo favorito y adaptarlo a la tarea o los datos que necesitemos, realizando lo que se conoce como proceso de *fine-tuning* (puesto que lo que hacemos es afinar los parámetros previamente calculados en el entrenamiento del modelo base del que partimos).

## Tokenizadores y modelos



Los dos elementos básicos con los que trabajaremos son los tokenizadores y los modelos. Los tokenizadores son los encargados de procesar el texto de entrada y convertirlo en una secuencia de números, tal como vimos en la sección anterior. Dado que cada modelo tiene sus peculiaridades en cuanto a cómo resuelve el tokenizado, tenemos un método que automáticamente nos devuelve el tokenizador apropiado para el modelo que vamos a utilizar. Por su parte, el modelo es un objeto que nos permite obtener las salidas de una forma sencilla, pasándole como entrada la secuencia codificada por el tokenizador.

Puedes ver una lista de los modelos disponibles aquí: https://huggingface.co/transformers/pretrained_models.html

Veamos con un ejemplo de código cómo se cargan los tokenizadores y los modelos:
"""

import torch
from transformers import AutoTokenizer, AutoModel

device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # Si hay disponible una GPU, el modelo se cargará en la VRAM

# Sólo tenemos que conocer el nombre del modelo para poderlo usar.
# La primera vez que se ejecuta, se descarga todo lo necesario.
tokenizador = AutoTokenizer.from_pretrained("distilbert-base-multilingual-cased") # ¡Este modelo contiene 104 lenguas!
modelo = AutoModel.from_pretrained("distilbert-base-multilingual-cased")

# Veamos el tipo de cada objeto obtenido
print("Tipo del tokenizador: ", type(tokenizador))
print("Tipo del modelo: ",type(modelo))
print("\nArquitectura del modelo:")
print(modelo)

"""Prueba a cambiar el nombre del modelo por otro (busca alguno que te llame la atención en el enlace anterior), y mira cómo cambian las clases de los objetos que se obtienen. El modelo que estamos usando está basado en DistilBERT, que es una versión más ligera de BERT (tiene menos parámetros y por tanto se puede ejecutar en máquinas con menos recursos).

Veamos ahora cómo usar el tokenizador:
"""

# Con una sola frase de entrada
entrada = tokenizador("Veamos cómo se usa el tokenizador")
print('Frase: "Veamos cómo se usa el tokenizador"')

from pprint import pprint
pprint(entrada)

"""Los "input_ids" son los números que codifican nuestro texto (los llamamos *tokens*). ¿Observas algo extraño en lo que hemos obtenido? Si cuentas el número de elementos en "input_ids", verás que hay más *tokens* que palabras en el texto... Convirtamos cada id a texto:"""

tokenizador.convert_ids_to_tokens(entrada['input_ids'])

"""Normalmente trabajaremos con paquetes de textos de entrada (*batch*), en lugar de procesar los textos uno a uno:"""

# Con varias frases de entrada
frases = ["Ahora con varias frases de entrada.",
          "Se procesan cada una por su lado.",
          ""] # La última frase está vacía
entradas = tokenizador(frases)
print('Frases:', '\n'.join(frases), sep='\n')
pprint(entradas)

"""Podemos volver a convertir esta codificación en texto con el método decode:"""

tokenizador.decode(entradas['input_ids'][1])

"""También es posible pedirle al tokenizador que haga *padding* (es decir, que complete con las entradas para que todas tengan el mismo tamaño con un token determinado, cero en el caso de BERT) y que las trunque (en caso de que las entradas sean más grandes que el tamaño máximo permitido por el modelo). Ambas cosas son habituales si vamos a usar *batches* para hacer un reentrenamiento del modelo:"""

# Con varias frases de entrada, con padding y truncando
frases = ["Ahora con varias frases de entrada.",
          "Se procesan cada una por su lado.",
          "Todas las secuencias obtenidas tengan el mismo tamaño.",
          ""] # La última frase está vacía
entradas = tokenizador(frases, padding=True, truncation=True)
print('Frases:', '\n'.join(frases), sep='\n')
pprint(entradas)

"""Ahora pasemos la entrada por el modelo. Para que el modelo acepte la entrada, debemos pedirle al tokenizador que nos devuelva tensores, que son la estructura de datos que usan las librerías de redes neuronales en que se apoya 🤗 *Transformers*:"""

frase = "Probemos el modelo!"
# Aseguramos que el modelo esté en el mismo dispositivo que los datos
modelo.to(device)

# Pedimos tensores de PyTorch, y que lo cargue en el dispositivo (GPU o CPU)
entrada = tokenizador(frase, return_tensors="pt").to(device)
print('\nFrase:', frase)
pprint(entrada)

print("\nSalida del modelo:")
with torch.no_grad():
    salida = modelo(**entrada)
print(salida)

"""El objeto que obtenemos de salida tiene dentro como puedes ver una matriz de *embeddings*, correspondientes a las entradas codificadas por la red en su última capa (*last_hidden_state*). Estos valores condensan toda la información del texto de entrada, aplicando todo lo que ha aprendido la red neuronal en el proceso de entrenamiento sobre una gran cantidad de textos. Esta será la clave para que podamos resolver todo tipo de tareas de PLN, añadiendo una o más capas que tomen estos valores como entrada y resuelvan la tarea deseada (para esto será necesario hacer *fine-tuning* y proporcionar algunos ejemplos de la tarea a resolver).

Carguemos ahora un modelo que ya ha sido *tuneado* para una tarea concreta, para obtener salidas más sencillas de interpretar. Vamos a usar un modelo entrenado para clasificar textos en base a la opinión expresada.

"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch.nn.functional as F  # Esto se usa para obtener las predicciones finales del modelo

# Cargamos un modelo adaptado a clasificar reviews de productos
# generando como salida una puntuación (de 1 a 5)
tokenizador = AutoTokenizer.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")

# Observa que ahora la clase para cargar el modelo indica la tarea concreta que resuelve
# el modelo. Esto permite que el objeto obtenido tenga operaciones adaptadas a dicha tarea
modelo = AutoModelForSequenceClassification.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment").to(device)

print("Tipo del objeto obtenido al cargar el modelo:", type(modelo))

texto = "En si es una cámara moderna y de fácil configuración, la visión nocturna pésima, una Go-Pro\
 tiene mejor visión nocturna. Decepcionada."
entrada = tokenizador(texto, return_tensors="pt").to(device)
print('\nTexto:', texto)
print(entrada)

salida = modelo(**entrada)
print('\nSalida:', salida)
print('\nValores de activación de la salida:', salida[0]) # también se puede acceder con salida.logits

# Para obtener la predicción con valores de probabilidad, hay que aplicar el filtro softmax
# a los valores de activación de salida, de esta forma:
prediccion = F.softmax(salida[0], dim=-1)
print("\nPredicción:", prediccion)

# Busquemos el mayor de los valores del vector anterior
puntuacion = max((v, i) for i,v in enumerate(prediccion[0], start=1))[1]
print("\nLa puntuación del review es", puntuacion,"sobre 5.")

"""El vector que obtenemos de predicciones indica la probabilidad de cada posible puntuación. El valor mayor es el segundo, con un un 0,68 de probabilidad, por lo que el modelo predice que la puntuación asignada al review es 2.

## **☞ Ejercicio entregable**: Clasificador de reviews

Encapsulando el código anterior, implementa una clase ClasificadorReviews que tenga un método que reciba el texto de un review y devuelva un número con la predicción de la puntuación.  

Busca algunos ejemplos de reviews en alguna web de compras y clasifícalos para probar el funcionamiento.
"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class ClasificadorReviews():
    def __init__(self):
        nombre_modelo = "nlptown/bert-base-multilingual-uncased-sentiment"
        self.tokenizador = AutoTokenizer.from_pretrained(nombre_modelo)
        self.modelo = AutoModelForSequenceClassification.from_pretrained(nombre_modelo).to(device)

    def clasifica(self, texto):
        entrada = self.tokenizador(texto, return_tensors="pt", truncation=True, max_length=512).to(device)
        with torch.no_grad():
            salida = self.modelo(**entrada)

        prediccion = F.softmax(salida.logits, dim=-1)
        puntuacion = torch.argmax(prediccion, dim=-1).item() + 1

        return puntuacion


clasificador = ClasificadorReviews()

# TODO: Implementa algunas pruebas con textos reales
reviews = [
    "This product is amazing! I loved it and would definitely recommend it to others.",
    "Terrible experience. The product broke after one use and the customer service was unhelpful.",
    "It's okay, not the best but it does the job.",
    "Excellent quality and fast shipping. Very satisfied with my purchase.",
    "Not worth the money. Very disappointed with the quality.",
    "The camera is great, but the battery life is surprisingly short. I expected more.",

    "¡Me ha encantado! Cumple su función a la perfección y el diseño es muy bonito. 10/10.",
    "Pésimo producto. Llegó con piezas rotas y el vendedor no me da ninguna solución. Una estafa.",
    "Está bien por el precio que tiene, aunque los plásticos podrían ser de mejor calidad.",
    "Tardó muchísimo en llegar, pero al menos funciona correctamente.",
    "Una maravilla, superó todas mis expectativas. Volveré a comprar seguro."
]

for review in reviews:
        pred = clasificador.clasifica(review)
        print(f"Review: {review}\nPredicción: {pred}\n")

"""---

## Resolución de tareas PLN *out-of-the-box*

Podemos hacer ejecuciones de modelos entrenados para tareas específicas de PLN de una forma sencilla a través del objeto *pipeline*. Por ejemplo, podemos llevar a cabo la predicción de puntuación de reviews que hemos visto a más bajo nivel en la sección anterior, pero de una forma mucho más sencilla:
"""

from transformers import pipeline

texto = "En si es una cámara moderna y de fácil configuración, la visión\
 nocturna pésima, una Go-Pro tiene mejor visión nocturna. Decepcionada."

# Consulta los detalles del modelo: https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment
clasifica_reviews = pipeline('sentiment-analysis', model='nlptown/bert-base-multilingual-uncased-sentiment')
clasifica_reviews(texto)

"""En esencia, lo que hace *pipeline* es esconder los detalles sobre la tokenización y uso del modelo, de forma parecida a como has hecho en el ejercicio anterior. Podemos optar por no introducir nada en el parámetro *model*, en cuyo caso se escogerá uno por defecto (generalmente, entrenado para funcionar únicamente en inglés).

En las siguientes celdas tienes ejemplos de algunas de las tareas listas para usar que tienes disponibles en 🤗 Transformers. Observa que es posible pasarle listas de textos de entrada al *pipeline*.
"""

# Clasificación de polaridad en inglés: POSITIVE vs NEGATIVE

from transformers import pipeline

sentiment = pipeline('sentiment-analysis')

# Si le pasas varios textos, se procesan todos de una vez
sentiment(['I wish I had never met you', 'You are the best thing that ever happened to me.'])

# Reconocimiento de entidades en inglés

ner = pipeline('ner')

ner("Project Mercury was the first human spaceflight program of the United States,\
 running from 1958 through 1963. An early highlight of the Space Race, its goal was\
  to put a man into Earth orbit and return him safely, ideally before the Soviet Union.",
  aggregation_strategy = "simple")

# Fill-Mask, adivinar una palabra que ha sido eliminada de un texto
# (recuerda que esta es una de las tareas con las que se entrena BERT)

fm = pipeline('fill-mask')
fm("I <mask> if you could guess the word that is missing here.")

from transformers import AutoModelForQuestionAnswering, AutoTokenizer
import torch

model_name = 'distilbert-base-cased-distilled-squad'
model_qa = AutoModelForQuestionAnswering.from_pretrained(model_name)
tokenizer_qa = AutoTokenizer.from_pretrained(model_name)

def qa_manual(question, context):
    inputs = tokenizer_qa(question, context, return_tensors="pt")
    with torch.no_grad():
        outputs = model_qa(**inputs)

    answer_start_index = outputs.start_logits.argmax()
    answer_end_index = outputs.end_logits.argmax()

    predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + 1]
    answer = tokenizer_qa.decode(predict_answer_tokens)

    # Calculamos una puntuación de confianza básica
    score = torch.max(torch.softmax(outputs.start_logits, dim=-1)).item()
    return {'answer': answer, 'score': score}

contexto = """
Project Mercury was the first human spaceflight program of the United States, running from 1958 through 1963.
An early highlight of the Space Race, its goal was to put a man into Earth orbit and return him safely,
ideally before the Soviet Union. Taken over from the US Air Force by the newly created civilian space agency NASA,
it conducted twenty uncrewed developmental flights (some using animals), and six successful flights by astronauts.
The program, which took its name from Roman mythology, cost $2.25 billion (adjusted for inflation).
The astronauts were collectively known as the "Mercury Seven", and each spacecraft was given a name ending
with a "7" by its pilot.
"""

preguntas = [
             "What is Project Mercury?",
             "What was the goal of Project Mercury?",
             "What was the Project Mercury trying to achieve?",
             "Who were the Mercury Seven?"
]

for pregunta in preguntas:
  print(f"Pregunta: {pregunta}")
  resultado = qa_manual(pregunta, contexto)
  print(f"Respuesta: {resultado['answer']} (Confianza: {resultado['score']:.4f})")
  print()

from transformers import AutoModelForQuestionAnswering, AutoTokenizer
import torch

# Cargamos el modelo y el tokenizador en español
model_es_name = 'mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es'
model_es = AutoModelForQuestionAnswering.from_pretrained(model_es_name)
tokenizador_es = AutoTokenizer.from_pretrained(model_es_name, use_fast=False)

def qa_es_manual(question, context):
    inputs = tokenizador_es(question, context, return_tensors="pt")
    with torch.no_grad():
        outputs = model_es(**inputs)

    answer_start_index = outputs.start_logits.argmax()
    answer_end_index = outputs.end_logits.argmax()

    predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + 1]
    answer = tokenizador_es.decode(predict_answer_tokens)

    score = torch.max(torch.softmax(outputs.start_logits, dim=-1)).item()
    return {'answer': answer, 'score': score}

contexto = """
La mostaza de Dijon es una forma francesa de mostaza. Se utiliza como condimento común
y se presenta en forma ligeramente pastosa. Se usa comúnmente para glaseados, salsas y
aderezos para sándwiches. La mostaza de Dijon es de un color amarillo pálido , a diferencia
del amarillo brillante de la mostaza amarilla. Es ligeramente cremoso y pastoso y no tiene
una base acuosa, ya que no tiene tanto vinagre como la mostaza amarilla. La mostaza de Dijon
está hecha con semillas picantes de mostaza marrón y negra. Luego se condimenta con verjuice,
que es casi como el vino elaborado con uvas jóvenes.
"""

preguntas = [
             "¿Qué es la mostaza de Dijon?",
             "¿Para qué se utiliza la mostaza de Dijon?",
             "¿Qué aspecto tiene la mostaza de Dijon?",
             "¿Con qué se fabrica la mostaza de Dijon?"
]

for pregunta in preguntas:
  print(pregunta)
  print(qa_es_manual(pregunta, contexto))
  print()

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch

# Cargamos el modelo y tokenizador de resumen manualmente
model_name = "sshleifer/distilbart-cnn-12-6"
model_sum = AutoModelForSeq2SeqLM.from_pretrained(model_name)
tokenizer_sum = AutoTokenizer.from_pretrained(model_name)

def resumir_manual(text, min_length=30, max_length=50):
    inputs = tokenizer_sum(text, return_tensors="pt", truncation=True, max_length=1024)
    with torch.no_grad():
        summary_ids = model_sum.generate(
            inputs["input_ids"],
            num_beams=4,
            min_length=min_length,
            max_length=max_length,
            early_stopping=True
        )
    return tokenizer_sum.decode(summary_ids[0], skip_special_tokens=True)

texto_a_resumir = """
Project Mercury was the first human spaceflight program of the United States, running from 1958 through 1963.
An early highlight of the Space Race, its goal was to put a man into Earth orbit and return him safely,
ideally before the Soviet Union. Taken over from the US Air Force by the newly created civilian space agency NASA,
it conducted twenty uncrewed developmental flights (some using animals), and six successful flights by astronauts.
The program, which took its name from Roman mythology, cost $2.25 billion (adjusted for inflation).
The astronauts were collectively known as the "Mercury Seven", and each spacecraft was given a name ending
with a "7" by its pilot.
"""

resumen_final = resumir_manual(texto_a_resumir, min_length=30, max_length=50)
print("Resumen:")
print(resumen_final)

"""### **☞ Ejercicio entregable**: Más tareas preentrenadas

Busca al menos dos pipelines más e implementa algún ejemplo de cada uno. Tienes los pipelines disponibles aquí: https://huggingface.co/transformers/main_classes/pipelines.html.

¿Puedes adaptar alguno de los pipelines (de los que has escogido o de los que hemos visto anteriormente) para que funcione con un modelo que incluya español? Puedes buscar un modelo que te sirva aquí: https://huggingface.co/models.
"""

from transformers import AutoModelForCausalLM, AutoModelForSeq2SeqLM, AutoTokenizer
import torch

print("--- 1. GENERACIÓN DE TEXTO (Modelo en Español) ---")
model_gen_name = 'DeepESP/gpt2-spanish'
tokenizer_gen = AutoTokenizer.from_pretrained(model_gen_name)
model_gen = AutoModelForCausalLM.from_pretrained(model_gen_name)

prompt = "El futuro de la inteligencia artificial en España es"
inputs_gen = tokenizer_gen(prompt, return_tensors="pt")

with torch.no_grad():
    outputs_gen = model_gen.generate(**inputs_gen, max_length=50, do_sample=True)

texto_generado = tokenizer_gen.decode(outputs_gen[0], skip_special_tokens=True)
print(f"Texto inicial: {prompt}")
print(f"Texto generado: {texto_generado}\n")


print("--- 2. TRADUCCIÓN AUTOMÁTICA (Inglés a Español) ---")
model_tr_name = 'Helsinki-NLP/opus-mt-en-es'
tokenizer_tr = AutoTokenizer.from_pretrained(model_tr_name)
model_tr = AutoModelForSeq2SeqLM.from_pretrained(model_tr_name)

texto_ingles = "Transformers have completely revolutionized the field of natural language processing in recent years."
inputs_tr = tokenizer_tr(texto_ingles, return_tensors="pt")

with torch.no_grad():
    outputs_tr = model_tr.generate(**inputs_tr)

traduccion = tokenizer_tr.decode(outputs_tr[0], skip_special_tokens=True)
print(f"Original (EN): {texto_ingles}")
print(f"Traducción (ES): {traduccion}")