# -*- coding: utf-8 -*-
"""AINE 2026 - TXT.5 - Conceptos Avanzados - benmauflo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfI4ofUK2H3LR1ORVjmp3CdryLNYr0nE

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26
---
---

**Escriba aquí su nombre y apellidos:** Benjamin Ignacio Maureira Flores

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:

* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable").
* Completar el código que esté incompleto (marcado con comentarios #TODO)

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install datasets umap-learn transformers accelerate autoawq gguf -U
# %pip install -U bitsandbytes
# %pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124

"""# TEXTOS 6: **Conceptos Avanzados en PLN**

Última modificación: Enero de 2026

## Introducción

Tras explorar las principales funcionalidades de la librería 🤗 Transformers y haber adquirido una base para aplicarla a distintas tareas de PLN, en este notebook daremos un paso más y exploraremos algunos de los conceptos que han surgido en los últimos años.

Analizaremos algunas de las limitaciones más habituales de los LLM (coste computacional, restricciones de memoria, conocimiento acotado al entrenamiento y falta de capacidad de interacción) y veremos cómo mitigarlas mediante técnicas avanzadas a través de tres ejercicios prácticos:

* **Despliegue de modelos**: profundizaremos en el concepto de la cuantización y en el uso de distintos motores de inferencia para reducir consumo de memoria y mejorar rendimiento tanto en CPU (LlamaCPP) como en GPU (LlamaCPP, VLLM, etc).

* **Creación de un chatbot RAG**: construiremos un chatbot basado en Retrieval-Augmented Generation para responder con apoyo en fuentes externas y mejorar la calidad y la confianza de las respuestas.

* **Desarrollo de un agente**: implementaremos un agente capaz de interactuar con herramientas externas, encadenar acciones y ejecutar tareas de forma autónoma bajo un objetivo definido.

> [!NOTE]
> Cada ejercicio es independiente uno del otro. Tras completar cada ejercicio, es recomendable que reinicies el servidor de Colab para liberar la VRAM .

Para este notebook es muy recomendable disponer de gráfica, comprueba que puedes ejecutar el siguiente comando y que tienes acceso a un Tesla T4:
"""

!nvidia-smi

"""# Despliegue de modelos: Cuantización"""

from transformers import AutoTokenizer, AutoModelForCausalLM, AutoModelForSequenceClassification, BitsAndBytesConfig
from llama_cpp import Llama
import torch

"""En notebooks anteriores nos vimos limitados a utilizar modelos relativamente pequeños, ya que los recursos disponibles (memoria principalmente) imponían restricciones claras sobre el tamaño y la complejidad de los modelos que podían ejecutarse.

La cuantización nos permite superar estas limitaciones reduciendo la precisión numérica de los pesos del modelo, o al menos de los pesos menos "relevantes". De este modo, es posible disminuir significativamente el consumo de memoria, a cambio de una pérdida de calidad generalmente pequeña. Gracias a ello, podemos ejecutar modelos más grandes en el mismo hardware.

![FP32](https://cdn.prod.website-files.com/62528d398a42420e66390ef9/684fe7581e3e6a2f71679f09_image%20(20).png)

### Funciones Auxiliares para Análisis de Modelos

Antes de profundizar en la cuantización, vamos a definir funciones auxiliares que nos permitan:

1. **Medir la memoria utilizada**: La función `count_model_parameters()` calcula cuántos parámetros tiene un modelo y cuánta memoria RAM/VRAM ocupa en megabytes aproximadamente (ver nota informativa).
2. **Evaluar la calidad de predicciones**: La función `classify_text()` realiza las predicciones sobre un modelo de clasificación tal y como vimos en notebooks anteriores.

> Nota: La función utilizada para estimar el consumo de memoria no proporciona una medida exacta y, al contrastarla con la salida del comando `nvidia-smi`, es normal observar discrepancias. Esto se debe a que el cálculo solo contempla los parámetros y buffers persistentes del modelo, y deja fuera varios componentes relevantes, entre ellos:
>
> * Las activaciones generadas durante la propagación de la información.
> * La memoria temporal (workspaces) empleada internamente por determinadas operaciones.
> * El "overhead" del allocator de PyTorch, que reserva y mantiene bloques de memoria para una gestión más eficiente (caching y fragmentación).
>
> Todo lo anterior corresponde únicamente al escenario de inferencia. En el caso de entrenamiento, el consumo real de memoria es aún mayor, ya que habría que añadir:
>
> * Los gradientes asociados a cada parámetro.
> * El estado del optimizador (por ejemplo, momentos en Adam o momentum en SGD).
>
> Por tanto, el valor obtenido debe interpretarse como una aproximación orientativa, no como una medida fiel del consumo real de memoria en GPU.
"""

from typing import Any

def count_model_parameters(model: torch.nn.Module):
    """Count the memory usage of a PyTorch model in megabytes (MB).
       Note that this function does not include memory used for gradients during training or
       any temporary memory allocations that may occur during forward/backward passes.
    """

    # .numel() gives the number of elements in the tensor
    # .element_size() gives the size in bytes of each element
    params = sum(p.numel() * p.element_size() for p in model.parameters()) # Trainable parameters: weights, biases, etc.
    buffers = sum(b.numel() * b.element_size() for b in model.buffers()) # Non-trainable parameters: running stats, constants, etc.

    bytes_used = params + buffers

    number_of_parameters = sum(p.numel() for p in model.parameters())\
          + sum(b.numel() for b in model.buffers())
    print(f"The model has {number_of_parameters:,} parameters.")

    print(f"The model requires {bytes_used / 1024 ** 2:.2f} MB with dtype {model.dtype}")

def classify_text(tokenizer: Any, model: torch.nn.Module, text: str, device:str='cpu'):
  """
  Classify the sentiment of a given text using the provided tokenizer and model.
  Args:
      tokenizer (AutoTokenizer): The tokenizer to preprocess the text.
      model (torch.nn.Module): The pre-trained model for sequence classification.
      text (str): The input text to classify.
      device (str): The device to run the model on ('cpu' or 'cuda').
  """

  input = tokenizer(text, return_tensors="pt").to(device)
  print('\nText:', text)

  output = model(**input)

  score = max((v, i) for i,v in enumerate(output[0], start=1))[1]
  print('\nScore:', score)
  print('\nActivation outputs:', output[0].detach().cpu().numpy()[0])

"""Para realizar las pruebas, definiremos un texto de ejemplo que ya te sonará de notebooks anteriores. Siéntete libre de modificarlo a tu gusto.

Además, definiremos un tokenizador que emplearemos durante las pruebas de los distintos modelos cuántizados. Ya sabes qué es un tokenizador, si no es así...¡qué haces aquí! ve al notebook anterior.
"""

text = "En si es una cámara moderna y de fácil configuración, la visión nocturna pésima, una Go-Pro\
 tiene mejor visión nocturna. Decepcionada."
tokenizer = AutoTokenizer.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")

"""A partir de aquí, analizaremos la eficacia y consumo de memoria de las distintas técnicas de cuantización.

### Escenario 1: Modelo Original sin Cuantización

Comencemos cargando el modelo clasificador de reviews usado en la clase anterior (BERT multilingüe) y midamos:
1. Número total de parámetros
2. Memoria requerida (usando float32 por defecto)
3. Calidad de las predicciones (puntuación y activaciones)

Este es el **baseline** para poder compararnos con las distintas técnicas de cuantización.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# model = AutoModelForSequenceClassification.from_pretrained(
#     "nlptown/bert-base-multilingual-uncased-sentiment",
#     device_map="cpu"
# )
# count_model_parameters(model)
# 
# classify_text(tokenizer, model, text)

"""> Nota: Actualmente estamos cargando los modelos en memoria RAM (cpu), puedes cargar el modelo directamente en VRAM (cuda) usando la opción `device_map="cuda"` dentro del método `from_pretrained`.

### Paso 2: Primera Cuantización - FP32 → FP16

Como vemos, el modelo usa por defecto el tipo `torch.float32`, es decir, 32 bits para representar cada número decimal. El modelo ocupa alrededor de **638 MB** de memoria.

¿Podemos reducir memoria sacrificando poco rendimiento?

Realizamos la cuantización más simple: cambiar la representación de **TODOS** los pesos a `torch.float16` (16 bits). Esto reduce exactamente a la mitad el tamaño:

- **FP32**: 32 bits por número = 638 MB
- **FP16**: 16 bits por número = ~319 MB (aprox.)

¿Pero qué pasa con la calidad?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# model = AutoModelForSequenceClassification.from_pretrained(
#     "nlptown/bert-base-multilingual-uncased-sentiment",
#     dtype=torch.float16
# )
# count_model_parameters(model)
# 
# classify_text(tokenizer, model, text)

"""Como se puede observar, la clasificación de sentimiento es idéntica (mismo score), las probabilidades de salida son prácticamente idénticas y todo esto reduciendo el tamaño exactamente a la mitad.

Bueno... y si la mitad funciona... ¿por qué no un cuarto?

Veamos qué ocurre con FP8 (8 bits):
"""

try:
  model = AutoModelForSequenceClassification.from_pretrained(
      "nlptown/bert-base-multilingual-uncased-sentiment",
      dtype=torch.float8
  )
  count_model_parameters(model)

  classify_text(tokenizer, model, text)
except Exception as e:
  print(e)

"""Parece que no existe dicho tipo de datos. Sin embargo, Pytorch sí que define los tipos `float8_e4m3` y `float8_e5m2` que son dos formas distintas de implementar un número decimal dependiendo de cuantos bits incluyas en el exponente o en la mantisa. El problema con estos tipos es que no admite varias operaciones básicas como sumas o restas:"""

a = torch.tensor([1., 2.]).to(torch.float8_e5m2)
b = torch.tensor([1., 2.]).to(torch.float8_e5m2)

try:
  a@b
except Exception as e:
  print(e)

"""No existe un tipo `torch.float8` estándar en PyTorch y, aunque sí existen `float8_e4m3` y `float8_e5m2`, hay dos limitaciones críticas:

1. **No soporta operaciones básicas**: Estos tipos tienen un soporte parcial para operaciones básicas (sumas, restas, multiplicación) que depende del hardware/kernel.
2. **Hardware limitado**: Pocas tarjetas gráficas ofrecen operaciones nativas en FP8. Por ejemplo, las tarjetas gráficas de escritorio no la soportan, mientras que las gráficas para centros de computación como la serie H100 sí que tienen soporte.

Por lo tanto, no podemos usar FP8 de forma nativa en pytorch.

### Paso 3: BitsAndBytes


Para resolver la limitación mencionada, usaremos [**BitsAndBytes**](https://github.com/bitsandbytes-foundation/bitsandbytes), una librería que implementa cuantización dinámica mediante kernels de CUDA escritos en C++ altamente optimizados. Esta librería aprovecha el hecho de que gran parte de los transformers tienen cierta redundancia inherente por lo que muchos parámetros contribuyen poco a la predicción final y pueden cuantizarse.


En resumen, la librería:
1. Analiza la importancia de cada parámetro del modelo de las capas lineales.
2. Mantiene los parámetros "críticos" en FP16 (los que más afectan la calidad).
3. Cuantiza el resto a 8 o 4 bits inteligentemente.

El único requisito de esta librería es que los modelos deben contener capas lineales/densas (Linear en Pytorch). Dado que la implementación estándar de los Transformers contiene una gran cantidad de capas lineales en las capas self attention (pesos de proyección Q, K y V), el ahorro en memoria es considerable. Ten en cuenta que, por ejemplo, capas convolucionales (las conocerás en el futuro) o embedding no serán cuantizadas.

**Referencias:**
- Dettmers et al., 2022: "8-bit Optimizers via Block-wise Quantization"
- Dettmers et al., 2023: "QLoRA: Efficient Finetuning of Quantized LLMs"

> Nota: HuggingFace implementa más técnicas de cuantización aparte de la usada en este notebook, cada una con sus fortalezas/limitaciones. Para más información puedes visitar: https://huggingface.co/docs/transformers/main/quantization/overview.

Para aplicar la cuantización el proceso es bastante sencillo, solo necesitamos definir la configuración de cuantización y añadir el parámetro `quantization_config` al modelo. La librería se encarga del resto:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# quantization_config = BitsAndBytesConfig(load_in_8bit=True)
# 
# model = AutoModelForSequenceClassification.from_pretrained(
#     "nlptown/bert-base-multilingual-uncased-sentiment",
#     quantization_config=quantization_config
# )
# count_model_parameters(model)
# classify_text(tokenizer, model, text, device='cuda')

"""> Nota: Ten en cuenta que `BitsAndBytes` es una librería diseñada para realizar la cuantización en la GPU (de hecho, el modelo se ha cargado en VRAM directamente sin que lo especifiquemos), por lo que debemos cargar la tokenización del texto también en VRAM.

Como puedes observar, un modelo cuantizado a 8 bits sigue ofreciendo buena calidad

Observa lo siguiente:
- El modelo NO ocupa exactamente un cuarto del tamaño original dado que BitsAndBytes mantiene **parámetros críticos en FP16** mientras cuantiza el resto.
- Tiempo de inferencia aumenta ligeramente (aunque menos que usando la cuantización nativa de Pytorch) pero memoria se reduce significativamente

¿Podemos ir más allá y usar solo 4 bits?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# quantization_config = BitsAndBytesConfig(load_in_4bit=True)
# 
# model = AutoModelForSequenceClassification.from_pretrained(
#     "nlptown/bert-base-multilingual-uncased-sentiment",
#     quantization_config=quantization_config
# )
# count_model_parameters(model)
# classify_text(tokenizer, model, text, device='cuda')

"""De nuevo, los modelos son muy buenos en general con un tamaño es aproximadamente de ~200 MB.

¿Puedes encontrar un texto donde el modelo cuantizado produzca una salida muy distinta con respecto el modelo sin cuantizar?

### Cuantización de Modelos Generativos (LLMs)

Aunque la cuantización es muy útil, el método que hemos empleado presenta un problema. Dado que la cuantización se produce en tiempo de inferencia, el modelo sigue ocupando bastante memoria RAM hasta que el modelo es cuantizado completamente y se carga en VRAM.

Además, en el caso de los modelos generativos tenemos otro problema adicional. Debido a que los modelos generativos deben inferir múltiples veces para generar una respuesta, el tiempo requerido puede ser prohibitivo en muchos casos. Incluso la cuantización juega en nuestra contra dado que los modelos deben descuantizarse progresivamente en cada inferencia.



Como solución, podemos usar modelos en formato [**GGUF**](https://huggingface.co/docs/hub/gguf) en lugar de [Safetensors](https://huggingface.co/docs/safetensors/index) (Estándar de HuggingFace). Estos modelos precuantizados:
- Se cargan ya comprimidos (sin descuantización en carga).
- Consumen muy poca memoria desde el minuto 0.
- Nos permite usar un motor de inferencia especializado (llama-cpp) que optimizan la generación de texto al máximo.

Para demostrar los beneficios de usar el formato GGUF y generar texto mediante un motor de inferencia, generaremos un ejemplo con el conocimiento adquirido hasta ahora. Pero antes de ello, debemos preguntarnos ¿Qué modelo debemos escoger?

A la hora de escoger el modelo, la fuente empleada comúnmente es [HuggingFace Hub](https://huggingface.co/models). Aquí podemos encontrar todo tipo de modelos almacenados en distintos repositorios, estos vienen descritos por un nombre con una sintaxis no demasiado uniforme... aun así podemos encontrar ciertos patrones. Por ejemplo, para el modelo `unsloth/Llama-3.2-1B-Instruct` identificamos las siguientes partes.


| Parte del nombre | Significado | Explicación |
|-----------------|------------|--------------------|
| unsloth | Repositorio | Usuario o entidad que aloja el modelo (ej. meta-llama, google, TheBloke). |
| Llama-3.2 | Arquitectura | La familia tecnológica. Define la estructura de capas y atención. |
| 1B | Parámetros | Escala del modelo (1×10⁹ pesos). A mayor número, más capacidad pero requiere más VRAM. |
| Instruct | Ajuste (Fine-tune) | Refinado para seguir órdenes. Si es Base, solo completa texto. |

Otros modelos pueden incluir otros sufijos para detalles sobre el proceso de entrenamiento:

| Término | Descripción |
|--------|-------------|
| Chat / Instruct | Optimizado para diálogo y seguimiento de instrucciones (el más usado para chat). |
| Base | Modelo “crudo”. Adecuado para seguir entrenando, deficiente para conversación. |
| Coder | Especializado en lenguajes de programación (ej. DeepSeek-Coder). |
| Math | Ajustado para resolución de problemas lógicos y matemáticos. |
| Vision / VL | Modelo multimodal; acepta imágenes como entrada (Vision-Language). |
| Thinking/CoT/Reasoning | El modelo ha sido ajustado (fine-tuned) para emitir explícitamente su cadena de razonamiento (chain-of-thought). |

Tipo de optimización empleada:

| Metodología | Descripción |
|------------|-------------|
| DPO (Direct Preference Optimization) | Entrenado para alinearse mejor con preferencias humanas sin RL clásico. |
| RLHF | Entrenamiento por refuerzo usando feedback humano. |
| Uncensored | Modelos con filtros de seguridad o negativas de respuesta reducidos o eliminados. |

Nivel de cuantización empleada:

| Nivel de Cuantización | Descripción |
|----------------------|-------------|
| Q2_K (GGUF) | Muy comprimido (2-bit). Alta pérdida de capacidad. |
| Q4_K_M (GGUF) | Estándar recomendado (4-bit). Buen equilibrio calidad/rendimiento. |
| Q6_K (GGUF) | Alta fidelidad (6-bit). Casi indistinguible del modelo original. |
| Q8_0 (GGUF) | Máxima calidad en GGUF (8-bit), con archivos muy pesados. |
| GPTQ / AWQ | Diseñados para GPUs NVIDIA; usados con librerías como vLLM o AutoGPTQ. |
| EXL2 | Formato extremadamente rápido, optimizado para ExLlamaV2. |

> **Nota**: Los nombres no siguen un estándar y que puede haber diversas variaciones o incluso nombres que no correspondan correctamente con la descripción.

A continuación vamos a cargar el modelo en formato estándar (no GGUF), vamos a cuantizarlo y a contar sus parámetros como hemos realizado anteriormente.
"""

from transformers import pipeline

quantization_config = BitsAndBytesConfig(load_in_4bit=True)

model_id = "unsloth/Llama-3.2-1B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id,
                                             device_map="cuda",
                                             quantization_config=quantization_config)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, dtype=torch.bfloat16, device_map="auto")

count_model_parameters(model)

"""Ahora, probemos a generar una respuesta a la consulta indicada. Aunque el modelo es multilingüe, a partir de aquí usaremos el inglés como el idioma principal para realizar las consultas dado que el modelo alucina bastante más en español que en inglés (puedes probarlo)."""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# query = "Enumerate the first 50 most common names in Spain."
# 
# outputs = pipe(query,
#                 do_sample=False, # Deterministic output
#                 max_new_tokens=512 # Limit the response length to avoid excessive generation
#                 )
# outputs_text = outputs[0]['generated_text']
# print(outputs_text)

"""Vaya, nuestro modelo ha "alucinado", esto es bastante común en los modelos que han sido entrenados para seguir una estructura determinada. No siempre tiene que pasar, pero no seguir el formato incrementa en gran medida la probabilidad de que ocurra.

### Plantillas

En los modelos generativos (LLMs), no basta con enviar una pregunta sin más. Los modelos han sido entrenados para reconocer una estructura específica de texto que les ayuda a distinguir qué partes son instrucciones del usuario, qué partes son contexto y cuándo les toca a ellos hablar.

Cada arquitectura (Llama 3, Mistral, Gemma) utiliza tokens especiales (como <|im_start|>, [INST] o <|begin_of_text|>) para delimitar tanto las distintas partes como el inicio y fin de la generación. Si no usamos el formato exacto con el que el modelo fue entrenado, su rendimiento caerá drásticamente (alucinaciones, respuestas en otros idiomas o fallos al seguir reglas, ignorar instrucciones).

Para evitar que tengamos que memorizar los delimitadores de cada modelo, la librería transformers introdujo los Chat Templates. Estos son archivos Jinja2 almacenados en los metadatos del tokenizador que convierten una lista de mensajes (diccionarios) en un único string formateado. Para más información: https://huggingface.co/docs/transformers/chat_templating.

A continuación, realizaremos exactamente la misma pregunta pero con el formato necesario para dicho modelo.
"""

messages = [
    {"role": "user", "content": query},
]
prompt = pipe.tokenizer.apply_chat_template(
    messages,
    tokenize=False,            # Returns text, not numeric IDs (useful for inspection)
    add_generation_prompt=True # Adds the final token indicating to the model that it is its turn to respond
)

"""Como habrás observado, la función `apply_chat_template` facilita la creación de prompts para modelos de chat al estructurar los mensajes según el formato esperado por el modelo. Los argumentos que reciben son:
- `messages`: una lista de diccionarios que representan los mensajes en la conversación, donde cada diccionario tiene un rol y el contenido del mensaje. El rol puede ser "user" para mensajes del usuario, "assistant" para respuestas del modelo, o "system" para instrucciones del sistema.
- `tokenize`: indica si se debe tokenizar el prompt (convertir a IDs numéricos) o devolverlo como texto. En este caso, se establece en False para obtener el prompt en formato de texto, lo que es útil para inspección y depuración.
- `add_generation_prompt`: indica si se debe agregar un token final que indique al modelo que es su turno de responder.

> Nota: En el futuro, ten en cuenta que hay funciones que admiten texto en crudo o una lista de diccionarios con la conversación.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# outputs = pipe(prompt,
#                 do_sample=False, # Deterministic output
#                 max_new_tokens=512 # Limit the response length to avoid excessive generation
#                 )
# outputs_text = outputs[0]['generated_text']
# print(outputs_text)

"""Como se puede observar, la salida tiene más sentido pero no está libre de errores. Aparecen nombres repetidos con ocurrencias distintas.

Esto puede deberse a que hemos especificado una instrucción "vaga" al modelo, sin dar más detalles. Podríamos intentar ser más específicos en la instrucción, por ejemplo pidiendo que el resultado esté en formato de lista numerada.
Además, ten en cuenta que el modelo es relativamente pequeño (1.2B parámetros) por lo que sus capacidades son limitadas. Existe una clara relación entre el tamaño del modelo y su capacidad para procesar y generar texto coherente y preciso.

Probemos ahora a hacer lo mismo pero empleando el mismo modelo en formato GGUF.

### Formato GGUF: Almacenamiento Eficiente de Modelos
(GPT-Generated Unified Format) es un formato binario especializado en almacenar modelos de IA originalmente pensado para modelos Llama, pero extendido a varios tipos de modelos en la actualidad. Entre sus características podemos encontrar:

- **Contenedor único**: Agrupa pesos, metadatos, configuración y vocabulario en un archivo.
- **Carga rápida**: Optimizado para memoria mapeada, sin necesidad de parsing complejo.
- **Precuantizado**: El modelo ya viene comprimido desde HuggingFace.
- **Portabilidad**: Funciona en CPU y GPU sin cambios.

<img src="https://cdn-gcs.ngxson.com/nuiblog2/2025/2/1740654134405_d5d7fc3c.jpg" alt="Diagrama" width="800"/>

Descargaremos Llama-3.2 en formato GGUF cuantizado a 4-bits (Q4_K_M):
- **Q4**: Cuantización a 4 bits
- **K_M**: Variante de mayor calidad (mantiene más información)
"""

from huggingface_hub import hf_hub_download

model_path = hf_hub_download(
    repo_id="unsloth/Llama-3.2-1B-Instruct-GGUF",
    filename="Llama-3.2-1B-Instruct-Q4_K_M.gguf"
)

model_path

"""A continuación, instanciaremos el motor de inferencia de `llama-cpp`."""

llm = Llama(
    model_path=model_path,
    n_gpu_layers=-1, # Use all available GPU memory
    seed=123, # For reproducibility
    n_ctx=2048, # Context window size
)

"""Finalmente, generaremos la respuesta de la consulta. Fíjate que en este caso la plantilla la aplica automáticamente el motor de inferencia.

Fíjate como, en este caso, la función `create_chat_completion` admite el parámetro `messages` con la conversación (listado de diccionarios) ya que llama.cpp aplica el formato correspondiente internamente.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# output = llm.create_chat_completion(
#     messages=[
#         {"role": "user", "content": query}
#     ],
#     temperature=0.0, # Deterministic output
#     max_tokens=512
# )
# print(output["choices"][0]["message"]["content"])

"""## **☞ Ejercicio entregable**: Parámetros de Inferencia.

Los modelos de lenguaje usan muestreo estocástico para seleccionar el siguiente token. Esto es crucial porque modelos con una generación NO determinista suelen dar respuestas más cercanas a como las personas nos expresamos.

Los modelos combinan tres técnicas para controlar el muestreo estocástico:

1. **Top-k Sampling**
- El modelo calcula probabilidades para todos los tokens del vocabulario.
- Mantiene solo los k más probables (ej: top-40).
- Muestrea aleatoriamente de estos k tokens.

2. **Top-p Sampling (Nucleus Sampling)**
- En lugar de fijar número de tokens, fija probabilidad acumulada.
- Selecciona los tokens cuya suma de probabilidades ≥ p (ej: p=0.9).
- El número de tokens varía dinámicamente.

3. **Temperature Sampling**
- Parámetro que modifica el "pico" de la distribución de probabilidades antes de muestrear:
    - `T=0`: Siempre el token más probable (determinista).
    - `T=1`: Usa probabilidades originales.
    - `T>1`: Aplana la distribución (más aleatorio, más creativo).

En la siguiente celda, modifica `temperature`, `top_k` y `top_p` y observa cómo cambia la respuesta.
"""

output = llm.create_chat_completion(
    messages=[
        {"role": "user", "content": query}
    ],
    temperature=0.8,
    top_k=40,
    top_p=0.9,
    max_tokens=512
)
print(output["choices"][0]["message"]["content"])

"""## **☞ Ejercicio Opcional**: Motores de Inferencia Alternativos (Opcional)

Existen diversos motores de inferencia optimizados para diferentes casos de uso:

- **llama-cpp-python**: Optimizado para CPU y pequeñas GPUs, muy portable.
- **vLLM**: Excelente para GPU con batching y paralelización.
- **TensorRT**: Optimización específica de NVIDIA.

En este ejercicio, exploraremos [**vLLM**](https://docs.vllm.ai/en/stable/serving/offline_inference/), que es especialista en servir múltiples consultas simultáneamente con alta throughput (especialmente útil en producción). Aunque es un poco más complicado que `llama-cpp-python`, ofrece mejor rendimiento en escenarios de múltiples usuarios.

Prueba vLLM con el modelo anterior y compara velocidad/calidad con el motor anterior.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install vllm

# TODO: Completa la configuración y el uso de vLLM para generar texto con el modelo GGUF descargado anteriormente

"""> [!NOTE]
> Recomendación: Reinicia el servidor de colab en este punto para liberar toda la VRAM empleada hasta ahora.

# Chatbot Inteligente con RAG (Retrieval-Augmented Generation)
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain langchain-huggingface langchain-community sentence-transformers langchain-chroma lxml

"""Una vez hemos aprendido a desplegar modelos de forma eficiente mediante cuantización, podemos mejorar significativamente su utilidad. Un problema fundamental de los modelos de lenguaje es que tienen conocimiento limitado al período de entrenamiento.

**RAG** (Generación Aumentada por Recuperación) resuelve este problema combinando:
1. Un motor de búsqueda (base de datos vectorial) que recupera información relevante.
2. Un modelo que utiliza esa información para responder preguntas específicas del dominio.

Nuestro chatbot se construirá en dos fases claramente diferenciadas:

**Fase 1: Preparación de la Base de Datos Vectorial**
- Identificar y descargar las fuentes de datos.
- Seleccionar un modelo "codificador".
- Codificar todos los documentos en vectores.
- Almacenarlos en Chroma para búsqueda rápida por similitud.

**Fase 2: Construcción del Chatbot**
- Integrar el modelo generador cuantizado.
- Definir funciones para recuperar el contexto y generar la respuesta.
- Definir el grafo de ejecución que orqueste el flujo de ejecución.

Ambas fases se usarán empleando [LangChain](https://docs.langchain.com/oss/python/langchain/overview). LangChain es framework de orquestación diseñado para facilitar la creación de aplicaciones que combinan Modelos de Lenguaje (LLMs) con fuentes de datos externas y lógica de programación. Podemos ver a LangChain como el elemento central que conecta todos los elementos que vamos a ir empleando durante este y el siguiente ejercicio.

### Fase 1: Preparación de la Base de Datos Vectorial

En notebooks anteriores, aprendimos que un embedding es una representación numérica densa de un texto en un espacio multidimensional donde las "distancias" entre palabras/frases capturan un significado semántico.

Podemos usar cualquier modelo para calcular dichos embeddings, sin embargo, es mejor escoger un modelo especializado en capturar lo más fielmente la semántica. La librería [sentence-transformers](https://sbert.net/index.html) ofrece cientos de modelos del estado del arte que podemos emplear para ello. En concreto, usaremos `intfloat/multilingual-e5-large` un modelo multilingüe que define un espacio de 1024 dimensiones para codificar las palabras/frases.

En este caso, en lugar de usar la librería `sentence-transformers` directamente para cargar el modelo de embeddings, usaremos la librería langchain que nos permite una integración más sencilla con los demás componentes.

En el siguiente código puedes observar que usamos el módulo `langchain_huggingface`, este módulo es el encargado de conectar HuggingFace con LangChain. A su vez, `HuggingFaceEmbeddings` carga los modelos de embedding de la librería `sentence-transformers`.
"""

from langchain_huggingface import HuggingFaceEmbeddings
import numpy as np

def cosine_similarity(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

model_kwargs = {"device": "cpu"}
embedding_model = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-large", model_kwargs=model_kwargs)

"""Los modelos de embeddings transforman palabras/frases en vectores numéricos multidimensionales de forma que palabras/frases similares semánticamente tengan vectores cercanos en el espacio. Esto se mide usando similitud de coseno, que calcula el ángulo entre dos vectores.

En el siguiente ejemplo, veremos cómo "Rey" es más similar a "King" (su traducción al inglés) que a "Puchero", demostrando que el modelo captura significado semántico.
"""

embedding_rey = embedding_model.embed_query("Rey")
embedding_king = embedding_model.embed_query("King")
embedding_puchero = embedding_model.embed_query("Puchero")

embedding_rey = np.array(embedding_rey)
embedding_king = np.array(embedding_king)
embedding_puchero = np.array(embedding_puchero)

similarity_king_rey = cosine_similarity(embedding_rey, embedding_king)
similarity_rey_puchero = cosine_similarity(embedding_rey, embedding_puchero)

print(f"Similitud entre 'Rey' y 'King': {similarity_king_rey:.4f}")
print(f"Similitud entre 'Rey' y 'Puchero': {similarity_rey_puchero:.4f}")

"""### Base de Datos Vectorial: Chroma

Una vez contamos con un modelo capaz de convertir texto en embeddings, necesitamos una forma eficiente de almacenarlos y recuperarlos. **Chroma** es una base de datos vectorial especializada que ofrece múltiples ventajas:

- **Búsqueda por similitud rápida**: Utiliza índices especializados para encontrar rápidamente los vectores más cercanos a una consulta.
- **Escalabilidad**: Maneja millones de vectores sin pérdida significativa de rendimiento.
- **Metadatos asociados**: Permite almacenar información adicional (fuente, fecha, etc.) junto con cada vector.
- **Integración con LangChain**: Ofrece una API sencilla compatible con el ecosistema de procesamiento de lenguaje.
- **Persistencia en disco**: Puede guardar los datos de forma permanente en la máquina local.

Chroma funciona recibiendo un modelo de embeddings (función) que se encarga de codificar automáticamente todos los documentos cuando se agregan a la base de datos.
"""

from langchain_chroma import Chroma

vector_store = Chroma(embedding_function=embedding_model, collection_name="aine_docs")

"""Una vez definido la base de datos vectorial, podemos añadir documentos y realizar búsquedas semánticas.

En este caso, cargaremos la información asociada a las "releases" de Pytorch en su repositorio oficial de GitHub y la almacenaremos en la base de datos vectorial. Para ello, usaremos el módulo `WebBaseLoader`, un "Wrapper" de `BeautifulSoup` que facilita la extracción de texto desde páginas web.
"""

from langchain_community.document_loaders import WebBaseLoader
from bs4 import SoupStrainer


loader = WebBaseLoader("https://github.com/pytorch/pytorch/releases",
                       bs_kwargs={
                            "parse_only": SoupStrainer("div", {"class": "Box-body"}),
                        })

docs = loader.load()

docs[0]

"""Como resultado, obtenemos un objeto de tipo Document que contiene el contenido extraído de la página web especificada junto con sus metadatos.

LangChain define el tipo estándar `Document` para representar cualquier fuente de información:

```python
Document(
    page_content="...",      # El texto actual
    metadata={"source": ...} # Información adicional
)
```

La misma clase encapsula tanto archivos HTML, como PDFs, Páginas web, Bases de datos, etc.

Esta abstracción es la clave para construir sistemas agnósticos a la fuente de datos.

### Estructura de Documentos en LangChain

LangChain define un tipo estándar `Document` que encapsula:
- **`page_content`**: El texto actual del documento
- **`metadata`**: Información adicional (fuente, página, autor, etc.)

Esta abstracción permite **intercambiabilidad**: el mismo código funciona con PDFs, webs, bases de datos, etc.

Veamos qué información se extrae automáticamente al cargar HTML:
"""

docs[0].metadata

docs[0].page_content[:100]

docs[0].to_json()

"""A continuación, podríamos codificar el contenido del documento en un embedding y almacenarlo en el vector store para futuras consultas. Sin embargo, codificar todo el contenido de la web no sería eficiente en términos de memoria y rendimiento. En su lugar, es recomendable dividir el contenido en fragmentos más pequeños (por ejemplo, párrafos o secciones) y luego codificar cada fragmento por separado antes de almacenarlo en el vector store. De esta manera, se optimiza el uso de recursos y se mejora la capacidad de recuperación de información relevante en consultas futuras.

Esta división, se conoce como chunking. En el siguiente ejemplo, dividimos el documento en fragmentos de 1000 caracteres con un solapamiento de 200 caracteres entre fragmentos consecutivos. El solapamiento evita frases cortadas a la mitad que pierden contexto y preserva información sobre las relaciones entre chunks.
"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, chunk_overlap=200, add_start_index=True
)
all_splits = text_splitter.split_documents(docs)
all_splits[:10]

print(f"Last part first document:\n\n {all_splits[1].page_content[-200:]}\n\n")
print(f"First part second document:\n\n {all_splits[2].page_content[:200]}")

"""### Almacenamiento en la Base de Datos Vectorial

La función `add_documents()` es el último paso de preparación:
1. Toma cada chunk
2. Calcula su embedding usando nuestro modelo multilingüe
3. Almacena el vector en Chroma junto con metadata
4. Crea índices para búsqueda rápida
5. Como resultado, obtenemos el UUID de cada documento almacenado.
"""

vector_store.add_documents(documents=all_splits)

"""### Búsqueda por Similitud: Recuperación de Información Relevante

Ahora que tenemos la base de datos vectorial lista, podemos hacer consultas que comparan el embedding del texto introducido con cada uno de los vectores almacenados retornando los k documentos más similares.
"""

vector_store.similarity_search("which version of Python is required by Pytorch 2.9.0?", k=3)

"""### Integración del Chatbot RAG

Hasta ahora hemos aprendido a recuperar documentos relevantes, ahora es el momento de integrar esta capacidad con un modelo generador para crear un chatbot funcional.

El resultado será un sistema capaz de responder preguntas sobre el contenido de la asignatura de forma contextualizada y confiable.

#### Paso 1: Cargar el Modelo generativo Cuantizado

Para completar esta parte, seleccionamos el modelo previamente descargado en formato GGUF (Llama 3.2) e integramos con LangChain.

LangChain proporciona un wrapper (`ChatLlamaCpp`) que simplifica la integración de modelos de Llama con el resto del ecosistema.
"""

from huggingface_hub import hf_hub_download

model_path = hf_hub_download(
    repo_id="unsloth/Llama-3.2-1B-Instruct-GGUF",
    filename="Llama-3.2-1B-Instruct-Q4_K_M.gguf"
)

from langchain_community.chat_models import ChatLlamaCpp

llm = ChatLlamaCpp(
    model_path=model_path,
    n_gpu_layers=-1,
    seed=123,
    n_ctx=2048,
)

"""El método empleado para generar la respuesta es `invoke` del objeto `llm`, y no el método `create_chat_completion` del paquete `llama_cpp`.

LangChain define un tipo [`BaseChatModel`](https://reference.langchain.com/python/langchain_core/language_models/) que engloba a diversos proveedores de modelos a través de una interfaz unificada, incluyendo clases como: `ChatHuggingFace`, `ChatLlamaCpp`, `ChatOpenAI`, etc . Esto permite cambiar entre diferentes proveedores sin modificar demasiado nuestra implementación.

Probemos a generar una respuesta tal y como hemos realizado anteriormente:
"""

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("unsloth/Llama-3.2-1B-Instruct")

messages = [
    {"role": "user", "content": "List the main new features of Pytorch 2.9.0."},
]
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)


response = llm.invoke(
  prompt,
    temperature=0.0, # Deterministic output
    max_tokens=512
)

response

"""El objeto response devuelve un objeto con el contenido generado con un objeto de tipo `AIMessage` con el atributo `content` que contiene el texto generado.

### Paso 2: Definición del Estado del Sistema RAG

Para construir un flujo de procesamiento en LangGraph (librería para crear grafos de ejecución), necesitamos definir el estado que se pasará entre cada nodo del grafo.

En nuestro caso, el estado contiene:
- `question`: La pregunta del usuario que necesita respuesta.
- `context`: Los documentos recuperados de la base de datos vectorial que son relevantes para la pregunta.
- `answer`: La respuesta generada por el modelo de lenguaje basada en el contexto.

Esta estructura permite que cada función en el flujo pueda leer del estado, procesar la información, y escribir nuevos valores que serán consumidos por la siguiente función.
"""

from langchain_core.documents import Document
from typing import List, TypedDict

class State(TypedDict):
    question: str
    context: str
    answer: str

"""### Paso 3: Función de Recuperación

La función `retrieve()` es el primer paso del pipeline RAG. Su objetivo es:

1. Tomar la pregunta del usuario del estado.
2. Buscar en la base de datos vectorial los documentos más similares a la pregunta.
3. Filtrar solo aquellos documentos con una puntuación de relevancia suficientemente alta (≥ 0.75) para evitar incluir información irrelevante.
4. Actualizar el estado con los documentos recuperados.

Este paso es crucial porque el modelo generador solo usará estos documentos para responder, por lo que la calidad de la recuperación determina directamente la calidad de la respuesta final.
"""

def retrieve(state: State):
    retrieved_docs = vector_store.similarity_search_with_relevance_scores(state["question"], k=4)
    filtered_docs = [doc for doc, score in retrieved_docs if score >= 0.75]
    return {"context": filtered_docs}

"""### Paso 4: Función de Generación

La función `generate()` es el **segundo paso del pipeline RAG**. Su responsabilidad es:

1. Extraer el contexto recuperado del estado (los documentos relevantes).
2. Si no existe contexto, se proporciona una respuesta por defecto.
3. Si sí existe contexto, construir un prompt estructurado que incluya en la conversación:
   - Instrucciones generales.
   - El contexto (fragmentos de documentos recuperados).
   - La pregunta del usuario.
4. Pasar este prompt al modelo de lenguaje cuantizado.
5. Actualizar el estado con la respuesta proporcionada.


"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("unsloth/Llama-3.2-1B-Instruct")

def generate(state: State):
    docs_content = "\n\n".join(doc.page_content for doc in state["context"])

    if not docs_content: # If no context is retrieved
        return {"answer": "There is no information available in the text to answer this question.", "context": docs_content}

    # Prepare the conversation messages for the chat model
    messages = [
        {"role": "system", "content": "You are a helpful assistant that answers questions based solely on the provided context."}, # system prompt
        {"role": "assistant", "content": "Using the following context, answer the question clearly, paraphrasing the context and in English. If the information does not appear in the context, respond: 'There is no sufficient information in the text to answer this question.' Do not invent data or use external knowledge."},
        {"role": "assistant", "content": f"CONTEXT:{docs_content}"},
        {"role": "user", "content": state["question"]},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    response = llm.invoke(prompt,
                          temperature=0.0, # Deterministic output
                          )
    # The response contains an object with the generated content
    return {"answer": response.content, "context": docs_content}

"""### Paso 5: Grafo de Ejecución

Ahora integraremos los componentes anteriores en un **grafo de ejecución** usando LangGraph. Este grafo define:

1. **Estructura**: Las funciones `retrieve` y `generate` se ejecutan secuencialmente.
2. **Flujo de datos**: El estado se pasa automáticamente de una función a la siguiente, enriquecido con nueva información en cada paso.
3. **Compilación**: La función `compile()` optimiza el grafo para ejecución eficiente.

Cuando ejecutamos el grafo:
- Primero se ejecuta `retrieve()` que busca documentos relevantes.
- Luego se ejecuta `generate()` que produce la respuesta final.
- El usuario obtiene tanto la respuesta como el contexto utilizado para transparencia.
"""

from langgraph.graph import START, StateGraph

graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
graph = graph_builder.compile()

graph

"""Realicemos una consulta al chatbot sin emplear el RAG. En concreto, preguntaremos cuál es la versión mínima de Python requerida por Pytorch que fue actualizada en las últimas releases:

> * Min supported Python version is now 3.10 (#162310)
> * The minimum version of Python required for PyTorch 2.9.0 is 3.10. We also have 3.14 and 3.14t available as preview with this release.

"""

messages = [
        {"role": "system", "content": "You are a helpful assistant that answers questions based solely on the provided context."},
        {"role": "user", "content": "What is the required Python version to use Pytorch 2.9?"},
]
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
response = llm.invoke(prompt,
                      temperature=0.0,
                      )
print("\nAnswer:", response.content, "\n")

"""Respuesta con RAG:"""

question = "What is the required Python version to use Pytorch 2.9?"
response = graph.invoke({"question": question})
print("\nQuestion:", question, "\n")
print("\nAnswer:", response["answer"], "\n")
print("-"*100)
print("Context used:\n", response["context"], "\n")

question = "Does the ONNX exporter in Pytorch 2.9 support caffe2?"
response = graph.invoke({"question": question})
print("\nQuestion:", question, "\n")
print("\nAnswer:", response["answer"], "\n")
print("-"*100)
print("Context used:\n", response["context"], "\n")

"""## **☞Ejercicio Entregable**: Ampliación del Contexto RAG

Añade a la base de datos vectorial fuentes externas relevantes para que el modelo tenga en cuenta.

Considera agregar documentación y recursos algunas librerías como:

   - [Hugging Face Transformers](https://huggingface.co/docs/transformers)
   - [LangChain Documentation](https://python.langchain.com)
   - [Sentence Transformers](https://www.sbert.net)
   - [Python](https://www.python.org/)

Crea la función `build_vector_store()` para:
- Descargar documentos desde URLs (usando `WebBaseLoader`)
- Actualizar incrementalmente la base de datos, teniendo en cuenta aquellos elementos ya incluidos ([Pista](https://docs.trychroma.com/docs/querying-collections/full-text-search)).
"""

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import WebBaseLoader
import hashlib

web_pages = [
    "https://huggingface.co/docs/transformers/index",
    "https://python.langchain.com/docs/introduction/"
]

def build_vector_store(web_pages=[]):
    if not web_pages:
        print("No hay páginas web para procesar.")
        return

    print(f"Descargando contenido de {len(web_pages)} páginas...")
    loader = WebBaseLoader(web_pages)
    docs = loader.load()

    print("Dividiendo el texto en fragmentos...")
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        add_start_index=True
    )
    all_splits = text_splitter.split_documents(docs)

    ids = [hashlib.sha256(doc.page_content.encode('utf-8')).hexdigest() for doc in all_splits]

    print(f"Añadiendo {len(all_splits)} fragmentos a la base de datos...")
    vector_store.add_documents(documents=all_splits, ids=ids)

    print("Completado")

build_vector_store(web_pages)

"""# Agentes Inteligentes: Interacción con Herramientas Externas

La clave para que un modelo generativo interaccione con herramientas externas reside en su capacidad de identificar cuándo y cómo utilizar dichas herramientas para mejorar la calidad y precisión de sus respuestas. Esto se logra entrenando a dichos modelos con ejemplos específicos donde se les muestra cómo y cuándo deben invocar herramientas externas, como motores de búsqueda, bases de datos o APIs especializadas. Al proporcionarles un contexto adecuado y ejemplos claros, los modelos aprenden a reconocer patrones en las preguntas que sugieren la necesidad de información adicional que no está contenida en su conocimiento preexistente.

Actualmente, Llama 3.2 es un modelo pequeño (~1B parámetros) y su capacidad para usar herramientas no es del todo confiable. Los modelos más confiables suelen ser bastante más grandes:
- GPT-4, Claude, Gemini (modelos cerrados)
- Llama 2/3 70B+ (modelos abiertos)

Para este ejercicio, necesitamos un modelo un poco más grande, por lo que no usaremos un despliegue local*. En su lugar, emplearemos la API de HuggingFaceHub para proveernos de un modelo un poco más grande, que contiene diversas opciones totalmente gratuitas**.

Para ello:
* Crea una cuenta en huggingface en el siguiente enlace: https://huggingface.co/join
* Expande el menú del perfil en la esquina superior derecha.
* Accede a la opción "access tokens".
* Crea un nuevo token pulsando en "create new token".
* Establece que será un token de lectura pulsando sobre "read".
* Añade un nombre a dicho token.
* Almacena el token en un lugar seguro, ten en cuenta que solo aparecerá una vez.

\* Es posible realizar este ejercicio con un despliegue local si dispones de los recursos necesarios. Puedes encontrar comentado el código en caso de que lo necesites.

\*\* HuggingFace establece un límite más que superior para los ejercicios de la asignatura. NO es necesario realizar ningún pago o incluir una tarjeta de crédito. Por favor no lo hagas.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain[openai]

"""En este caso, usaremos `Qwen/Qwen3-Next-80B-A3B-Instruct` para realizar el experimento a través de la clase `HuggingFaceEndpoint`. Como siempre, siéntete libre de cambiar el modelo (ten cuidado, algunos requieren permisos adicionales)."""

"""
Despliegue local de Qwen 3 usando LangChain y ChatOpenAI
-------------------------------------------------------------------------------
Para el despliegue local de Qwen 3 usando LangChain y ChatOpenAI, asegúrate de tener un servidor local que sirva el modelo a través de una API compatible con OpenAI (VLLM o llama.cpp son opciones populares).

En terminal: vllm serve --model Qwen/Qwen3-Next-80B-A3B-Instruct

from langchain_openai import ChatOpenAI

model = ChatOpenAI(model="Qwen/Qwen3-Next-80B-A3B-Instruct",
                   base_url="http://localhost:8000/v1",
                   temperature=0.,
                   max_completion_tokens=2048,
                   api_key="DUMMY") # No es necesario un API key real para un servidor local
"""

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] = "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" # Replace with your actual token

llm = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen3-Next-80B-A3B-Instruct",
    max_new_tokens=256,
    temperature=0,
)

model = ChatHuggingFace(llm=llm, temperature=0)

"""LangChain define un tipo [`BaseChatModel`](https://reference.langchain.com/python/langchain_core/language_models/) que engloba a todos los modelos de chat compatibles, incluyendo `ChatHuggingFace` y `ChatOpenAI`. Esto permite cambiar entre diferentes proveedores de modelos de lenguaje sin modificar el código que interactúa con el modelo.

A continuación, usaremos el método `invoke` para realizar una llamada al modelo con un ejemplo de consulta
"""

response = model.invoke("Which library is used for data manipulation and analysis in Python?")

print(response.content)

"""### Instanciación de Herramientas

Definiremos una serie de herramientas para manipular y consultar una base de datos vectorial, calcular similitud entre palabras, y realizar operaciones de procesamiento de lenguaje natural.

Estas herramientas son:
- calcular_similitud: Calcula la similitud entre dos palabras utilizando embeddings.
- almacenar_embedding: Almacena el embedding de una palabra en la base de datos.
- eliminar_embedding: Elimina el embedding que contienen una palabra de la base de datos.
- consultar_documentos: Consulta los documentos que contienen una palabra en la base de datos y devuelve su contenido.
- modificar_elementos: Modifica los elementos que contienen una palabra en la base de datos, reemplazándola por otra.
- separa_palabras: Separa un texto en palabras individuales.
- tipo_palabras: Devuelve el tipo gramatical de cada palabra en un texto (opcionalmente filtrado por tipo: DET, ADP, NOUN,...).
- separa_frases: Separa un texto en frases individuales.
- contar_elementos: Cuenta el número de elementos en una lista.
"""

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
import numpy as np
import spacy

embedding_model = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-large", model_kwargs={"device": "cpu"})

vector_store = Chroma(embedding_function=embedding_model, collection_name="aine_docs")

if spacy.util.is_package("es_core_news_lg") is False:
    spacy.cli.download("es_core_news_lg")

"""La forma más sencilla de definir herramientas en LangChain es utilizando el decorador @tool. A continuación, se muestran varias herramientas avanzadas que interactúan con el vector store y procesan texto utilizando spaCy.

> Nota: Es muy importante definir los tipos de las funciones para que LangChain los pueda interpretar correctamente, además de añadir descripciones claras de lo que hacen las funciones y sus parámetros. Esto es parte del "prompt engineering" que mejora la interacción con el modelo.
"""

from langchain.tools import tool
from langchain_core.documents import Document

def cosine_similarity(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

nlp = spacy.load('es_core_news_lg')
@tool("calcular_similitud")
def calcular_similitud(palabra1: str, palabra2: str) -> str:
    """
    Calcula la similitud entre dos palabras utilizando embeddings.
    """

    embedding_1 = np.array(embedding_model.embed_query(palabra1))
    embedding_2 = np.array(embedding_model.embed_query(palabra2))

    similarity = cosine_similarity(embedding_1, embedding_2)

    return f"La similitud entre '{palabra1}' y '{palabra2}' es {similarity:.4f}"

@tool("almacenar_embedding")
def almacenar_embedding(palabra: str) -> str:
    """
    Almacena el embedding de una palabra en la base de datos.
    """

    vector_store.add_documents([Document(page_content=palabra, metadata={"source": "user_input"})])

    return f"Embedding de la palabra '{palabra}' almacenado."

@tool("eliminar_embedding")
def eliminar_embedding(palabra: str) -> str:
    """
    Elimina el embedding que contienen una palabra de la base de datos.
    """

    vector_store.delete(where_document={"$contains": palabra})

    return f"Embedding de la palabra '{palabra}' eliminado."

@tool("consultar_documentos")
def consultar_documentos(palabra: str) -> list:
    """
    Consulta los documentos que contienen una palabra en la base de datos y devuelve su contenido.
    """
    results = vector_store.get(where_document={"$contains": palabra})
    return results["contents"]

@tool("modificar_elementos")
def modificar_elementos(palabra_origen: str, palabra_nueva: str) -> str:
    """
    Modifica los elementos que contienen una palabra en la base de datos, reemplazándola por otra.
    """
    results = vector_store.get(where_document={"$contains": palabra_origen})
    for doc_id, content in zip(results["ids"], results["documents"]):
        nuevo_contenido = content.replace(palabra_origen, palabra_nueva)
        vector_store.update_document(document_id=doc_id, document=Document(page_content=nuevo_contenido, metadata={"source": "user_update"}))
    return f"Elementos modificados: {results['ids']}"

@tool("separa_palabras")
def separa_palabras(texto: str) -> list:
    """
    Separa un texto en palabras individuales devolviendo una lista de elementos.
    """
    doc = nlp(texto)
    return [token.text for token in doc if token.is_alpha]

@tool("tipo_palabras")
def tipo_palabras(texto: str, tipo:str|None=None) -> list:
    """
    Devuelve el tipo gramatical de cada palabra listado de elementos (opcionalmente filtrado por tipo: DET, ADP, NOUN,...).
    """
    doc = nlp(texto)
    return [token.text + "-" + token.pos_ for token in doc if tipo is None or token.pos_ == tipo]

@tool("separa_frases")
def separa_frases(texto: str) -> list:
    """
    Separa un texto en frases individuales devolviendo una lista de elementos.
    """
    doc = nlp(texto)
    return [sent.text for sent in doc.sents]

@tool("contar_elementos")
def contar_elementos(elementos: list) -> int:
    """
    Cuenta el número de elementos en una lista.
    """
    return len(elementos)

tools = [calcular_similitud, almacenar_embedding, separa_palabras, tipo_palabras, separa_frases, eliminar_embedding, consultar_documentos, modificar_elementos, contar_elementos]

"""### Creación del Agente

Una vez definidas las herramientas, hay que registrarlas para que puedan ser utilizadas por los agentes o flujos de trabajo en LangChain. Para ello, LangChain proporciona la función `create_agent`, que nos simplifica mucho el trabajo.

Ten en cuenta que esta función hace algo parecido a lo que ya hemos realizado al construir el chatbot RAG, definiendo el siguiente flujo de ejecución.

![](https://mintcdn.com/langchain-5e9cc07a/-_xGPoyjhyiDWTPJ/oss/images/agent.png?fit=max&auto=format&n=-_xGPoyjhyiDWTPJ&q=85&s=bd8da41dbf8b5e6fc9ea6bb10cb63e38)

Podríamos definir dicho flujo de forma manual, dándonos la libertad de personalizar cada paso, incluir comprobaciones de seguridad, manejo de errores, etc. De nuevo, por simplicidad, usaremos la función  `create_agent`.

La función `create_agent` recibe principalmente tres parámetros: el modelo de lenguaje (llm), las herramientas disponibles (tools) y "prompt".

Es esencial definir un "prompt" adecuado que guíe al agente en el uso de las herramientas para responder preguntas de manera efectiva. Recomendaciones comunes incluyen:
- Proporcionar contexto sobre el objetivo del agente.
- Proporcionar instrucciones claras sobre cómo y cuándo utilizar cada herramienta.
- Incluir ejemplos de uso de las herramientas en el prompt (Few-shot).
- Proporcionar ciertas reglas para el agente, como no inventar respuestas o números, y utilizar las herramientas para obtener la información necesaria.
"""

from langchain.agents import create_agent

system_prompt = """
Eres un asistente inteligente.
Posees una serie de herramientas para ayudarte a responder a sus preguntas.
Utiliza las herramientas cuando sea necesario para responder a las preguntas de los usuarios.

Las herramientas disponibles son:
- calcular_similitud: Calcula la similitud entre dos palabras utilizando embeddings.
- almacenar_embedding: Almacena el embedding de una palabra en la base de datos.
- eliminar_embedding: Elimina el embedding que contienen una palabra de la base de datos.
- consultar_documentos: Consulta los documentos que contienen una palabra en la base de datos y devuelve su contenido.
- modificar_elementos: Modifica los elementos que contienen una palabra en la base de datos, reemplazándola por otra.
- separa_palabras: Separa un texto en palabras individuales.
- tipo_palabras: Devuelve el tipo gramatical de cada palabra en un texto (opcionalmente filtrado por tipo: DET, ADP, NOUN,...).
- separa_frases: Separa un texto en frases individuales.
- contar_elementos: Cuenta el número de elementos en una lista.

Reglas:
- No inventes respuestas o números. Si no sabes la respuesta, utiliza las herramientas para obtener la información necesaria.
- Proporciona respuestas claras y concisas en español.
- No inventes datos ni utilices conocimiento externo.
- Si el usuario requiere contar elementos o el número de elementos, utiliza la herramienta cuenta_elementos, no cuentes manualmente.


Sigue estos pasos para responder a las preguntas de los usuarios:
1. Analiza la pregunta del usuario.
2. Decide si necesitas utilizar alguna herramienta para obtener la información necesaria.
3. Si es así, utiliza la herramienta adecuada y obtén el resultado.
4. Vuelve al paso 1 con el resultado obtenido hasta que tengas toda la información necesaria.
5. Utiliza el resultado de la herramienta para formular una respuesta clara y concisa en español.
"""

agent = create_agent(model, tools=tools, system_prompt=system_prompt)

"""Una vez definido el agente, puedes invocarlo mediante el método `agent.invoke()` pasando la pregunta del usuario como argumento en formato diccionario. Como respuesta, el agente devuelve un diccionario con una única clave llamada "messages" con todos los mensajes generados por el usuario/agente/herramientas."""

response = agent.invoke({"messages": [{"role": "user", "content": "¿Cómo de similares son las palabras 'Rey' y 'King'? ¿Y 'Rey' y 'Puchero'? "}]})

response["messages"]

"""También existe el método `stream` que permite obtener las respuestas de forma incremental, tal y como se generan para dar una mayor sensación de interactividad.


Por ejemplo, podemos pedir que almacene nuevas palabras en la base de datos vectorial.
"""

for step in agent.stream(
    {"messages": [{"role": "user", "content": "Almacena el embedding para la palabra 'Reina'."}]},
    stream_mode="values",
):
    last_message = step["messages"][-1]

    last_message.pretty_print()

"""Comprobemos que, efectivamente se ha almacenado en la base de datos."""

vector_store.get(where_document={"$contains": "Reina"})

"""Ahora eliminemos dicha palabra:"""

for step in agent.stream(
    {"messages": [{"role": "user", "content": "Eliminar el embedding para la palabra 'Reina'."}]},
    stream_mode="values",
):
    last_message = step["messages"][-1]

    last_message.pretty_print()

"""Y comprobémoslo:"""

vector_store.get(where_document={"$contains": "Reina"})

"""Probemos a modificar la base de datos:"""

for step in agent.stream(
    {"messages": [{"role": "user", "content": "Modifica los elementos que contienen la palabra 'Python', reemplazándola por 'Java'."}]},
    stream_mode="values",
):
    last_message = step["messages"][-1]

    last_message.pretty_print()

"""Y, finalmente, a probar el uso de las herramientas de procesamiento de lenguaje:"""

for step in agent.stream(
    {"messages": [{"role": "user", "content": "Cuenta las palabras en el siguiente texto: 'El procesamiento del lenguaje natural es una rama de la inteligencia artificial que se centra en la interacción entre las computadoras y el lenguaje humano.'"}]},
    stream_mode="values",
):
    last_message = step["messages"][-1]

    last_message.pretty_print()

for step in agent.stream(
    {"messages": [{"role": "user", "content": "Cuántos determinantes hay en el siguiente texto: 'El procesamiento del lenguaje natural es una rama de la inteligencia artificial que se centra en la interacción entre las computadoras y el lenguaje humano.'"}]},
    stream_mode="values",
):
    last_message = step["messages"][-1]

    last_message.pretty_print()

"""A continuación, prueba el agente con tus propias preguntas y tareas relacionadas con el procesamiento del lenguaje natural y la gestión de embeddings ¿detectas algún patrón en sus respuestas?

## **☞Ejercicio Entregable**: Creación de una calculadora con memoria

Para practicar los conocimientos adquiridos, vamos a crear un agente sencillo (e inútil): Una calculadora que acepta texto natural.

Para ello:
* Crea las herramientas que consideres necesarias correspondientes a las operaciones matemáticas.
* El agente actual no incluye una memoria sobre el historial de mensajes. Investiga la forma de incluir esta funcionalidad en el chatbot.
* Comprueba el funcionamiento con varias operaciones.
"""

# TODO: Completa con el código necesario para crear tu agente personalizado usando LangChain y las herramientas definidas anteriormente. Usa varias celdas si es necesario.

from langchain.tools import tool
from langgraph.checkpoint.memory import MemorySaver
from langchain.agents import create_agent

# 1. Herramientas matemáticas básicas
@tool("sumar")
def sumar(a: float, b: float) -> float:
    """Suma dos números."""
    return a + b

@tool("restar")
def restar(a: float, b: float) -> float:
    """Resta el segundo número al primer número (a - b)."""
    return a - b

@tool("multiplicar")
def multiplicar(a: float, b: float) -> float:
    """Multiplica dos números."""
    return a * b

@tool("dividir")
def dividir(a: float, b: float) -> str | float:
    """Divide el primer número por el segundo (a / b)."""
    if b == 0:
        return "Error: No se puede dividir por cero."
    return a / b

tools_calc = [sumar, restar, multiplicar, dividir]

# 2. Prompt del sistema instruyendo a la calculadora
system_prompt_calc = """
Eres una calculadora inteligente. Tu único objetivo es realizar operaciones matemáticas
utilizando las herramientas proporcionadas (sumar, restar, multiplicar, dividir).
Reglas:
- Debes usar SIEMPRE las herramientas para hacer los cálculos, no intentes hacerlos mentalmente.
- Responde de forma clara, directa y en español.
- Recuerda el contexto de la conversación si el usuario hace referencia a un resultado anterior.
"""

# 3. Inicializamos el gestor de memoria
memoria = MemorySaver()

# 4. Creamos el agente pasándole la memoria
agente_calculadora = create_agent(
    model,
    tools=tools_calc,
    system_prompt=system_prompt_calc,
    checkpointer=memoria
)

# 5. Función para facilitar la prueba de la memoria
config_sesion = {"configurable": {"thread_id": "sesion_calculadora_1"}}

def usar_calculadora(pregunta: str):
    print(f"Usuario: {pregunta}")
    respuesta = agente_calculadora.invoke(
        {"messages": [{"role": "user", "content": pregunta}]},
        config=config_sesion
    )
    print(f"Calculadora: {respuesta['messages'][-1].content}\n")
    print("-" * 50)

# 6. Comprobamos el funcionamiento con memoria encadenando operaciones
print("--- PRUEBA DEL AGENTE CALCULADORA CON MEMORIA ---\n")
usar_calculadora("¿Cuánto es 12 más 28?")
usar_calculadora("Multiplica ese resultado por 2.")
usar_calculadora("Ahora divide el número que te ha dado entre 4.")
usar_calculadora("Réstale 10 a eso último.")