# -*- coding: utf-8 -*-
"""AINE 2026 - AUD.2 - Senales (ESCRIBE AQUI TU UVUS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONmcFPEDCE_7MpsWYoXuuGnMI1-vJQHc

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

**Escriba aquí su nombre y apellidos:**

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:
* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable")

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**

---



---

# AUDIO 2: SEÑALES
Última modificación: 19 de marzo de 2026

# Dependencias

- **Numpy**: Manipulación de arrays en entornos científicos (ej. representación de señales de audio)
    - https://numpy.org/
- **Matplotlib**: Representación gráfica de datos (señales del audio, espectogramas)
    - https://matplotlib.org/
- **IPython**: Reproducción de audio
    - https://ipython.readthedocs.io/
- **Librosa**: Paquete especializado en el análisis de señales de audio
    - https://librosa.org/

En el apartado de E/S de audio:
- **Wave**: Lectura y escritura de audios en formato WAV (no requiere instalación)
- **SoundDevice**: Grabación y reproducción de audio
"""

# Bibliotecas de python
import numpy as np
import matplotlib.pyplot as plt
import IPython.display as ipd
import librosa

"""# Introducción a las señales de audio

## Sonido

El sonido es una vibración mecánica que se propaga en un medio elástico que permite la compresión y rarefacción de las partículas.

La compresión/rarefacción se manifiesta en una mayor o menor intensidad de la presión.

- Las ondas que provocan el sonido tienen una carácter eminentemente periódico
- La función seno (coseno) es el prototipo de representación gráfica del sonido.


<img width=600 height="200" src="./images/ondaSonora.png">

## Señal de audio

Una señal de audio suele modelarse como $s(t)=A \cdot \sin(2\pi f t + \phi)$.

La ventaja del ajuste $\sin(2\pi ft)$ es que unifica la unidad temporal de modo que:
- el número de muestras se mide en segundos
- la frecuencia (número de ciclos por periodo) se mide en segundos

Parámetros principales:
- Frecuencia $f$: número de periodos por segundo (Hz)
- Amplitud $A$: intensidad de la señal
- Fase $\phi$: desplazamiento temporal de la onda

Notas:
- Frecuencias bajas y altas se perciben como tonos graves y agudos
- Mayor amplitud implica mayor volumen

PCM toma esta señal continua y la convierte en una secuencia de muestras en instantes discretos.
"""

# Representación de una señal de audio
sr=1000
duration=1
t = np.arange(0,duration,1/sr)

# -->  Modifica los valores de frecuencia, amplitud y fase para ver los cambios
# Frecuencia: al aumentar, la onda oscila más rápido y el tono se vuelve más agudo
frecuencia=10
# Amplitud: al aumentar, la onda alcanza valores más altos y el sonido tiene más intensidad
amplitud=1
# Fase: desplaza la onda en el tiempo sin cambiar ni su amplitud ni su frecuencia
fase=2*np.pi

x= 2*np.pi*frecuencia*t
signal=amplitud*np.sin(x + fase)

plt.figure(figsize=(10,5))
# Señal con frecuencia uno, amplitud uno y fase 0
plt.plot(t,np.sin(2*np.pi*t),color="#F00",alpha=0.3,label="Señal de referencia")
# Señal definida por frecuencia, amplitud y fase
plt.plot(t, signal, label="Señal modelada")
plt.legend()
plt.show()

"""## Señal PCM

PCM (Pulse Code Modulation) es la técnica estándar para digitalizar la señal de audio.

- Se toman muestras a intervalos regulares (tasa de muestreo, Hz)
- Cada muestra se cuantiza según la profundidad de bits
  - int16: rango [-32768, 32767]
  - float32/64: valores normalizados en [-1, 1]
- Número de muestras = tasa de muestreo x duración

En resumen: la sección anterior describe la forma continua de la señal; PCM explica cómo almacenarla digitalmente.

"""

# PCM: Representanción de una función sinsuoidal mediante muestras
# Sample Rate (número de muestras por segundo)
sr=4
# Duración total (en sgs)
duration=8

# Representación de la señal con Numpy
#  --  Eje X (Tiempo) : https://numpy.org/doc/stable/reference/generated/numpy.arange.html
#  --  Eje Y (Muestras):     https://numpy.org/doc/stable/reference/generated/numpy.sin.html
#  --  np.linspace(start,stop,num): Genera num valores en el rango [start,stop]
#  --  np.arange(start,stop,step): Genera valores en [start,stop) espaciados según step

# Parámetros de la señal continua que luego será muestreada
frecuencia=1
amplitud=1
fase=0

# Eje X: Genera instantes de tiempo en el rango [0,duration) espaciados según la cantidad 1/sr
t = np.arange(start=0,stop=duration,step=1/sr)
# Eje Y: Muestras obtenidas de la señal de audio en cada instante de t
y = amplitud*np.sin(2*np.pi*frecuencia*t + fase)

print("Forma de la señal:", y.shape)
print("Tipo de las muestras:",y.dtype)
print("Extracto de t=",t[0:3]," ... ",t[-4:])
print(f"Extracto de y= {y[0:3]} ... {y[-4:]}")

# Representación gráfica de la señal con matplotlib
plt.figure(figsize=(10,3))
plt.stem(t,y)
plt.plot()

"""## Rango auditivo y duración mínima

Rango auditivo aproximado: 20 Hz - 22000 Hz.

Teorema de Nyquist: para una señal de frecuencia $f$, la tasa de muestreo debe cumplir $sr \geq 2f$.

Por eso se usa con frecuencia $sr=44100$, que permite representar señales de hasta ~22000 Hz.

Duración de una muestra: $1/sr$.

"""

# Rango auditivo y duración mínima
# --> Modifica sr con distintos valores
sr=10000

duration=2
# --> Modifica la frecuencia con 1, 20, 50, 100, 200,sr/2
frecuencia=100

print(f"SR={sr}  muestras por segundo")
print(f"Duración de una muestra={1/sr:0.6f} sgs")
print(f"Frecuencia Nyquist: {int(sr/2)}")

t = np.arange(0,duration,1/sr)
signal=np.sin(2*np.pi*frecuencia*t)

ipd.Audio(signal,rate=sr)

"""# Librosa

El paquete de Python librosa.py (https://librosa.org/) está especializado en la manipulación y análisis de audio.

Se apoya en *numpy* para representar las señales de audio mediante numpy.ndarrays

La biblioteca está dividida en varios paquetes dedicados a distintos aspectos:
- Core IO
- Display  (waveshow, specshow)
- Onset detection
- Beat and tempo
- Spectograma decomposition
- Effects
- Temporal segmentation
- Sequential modeling
- Utilities

## Generación de señales
"""

# Librosa: generación de señales (elige UNA opción y descoméntala)
import librosa

sr=22050

# Opción 1: Tono sinusoidal
# https://librosa.org/doc/latest/generated/librosa.tone.html
signal = librosa.tone(221, duration=1.6, sr=sr)

# Opción 2: Chirp (pío)
# https://librosa.org/doc/latest/generated/librosa.chirp.html
# signal = librosa.chirp(fmin=200, fmax=600, duration=1, sr=sr)

# Opción 3: Clics
# https://librosa.org/doc/latest/generated/librosa.clicks.html
# times = np.array([0.1, 0.2, 0.5, 0.8])
# signal = librosa.clicks(times=times, sr=sr)

print("Tipo de la señal", type(signal))
print("Tipo de las muestras", signal.dtype)
print("--- Señal")
print(signal)
ipd.Audio(signal, rate=sr)

"""## Visualización de audio"""

# Librosa Waveshow
# https://librosa.org/doc/latest/generated/librosa.display.waveshow.html
# El paquete display incluye la función display.waveshow para mostrar señales de audio (se apoya en matplotlib)
import librosa

signal =librosa.tone(221,duration=1.6, sr=22050)
librosa.display.waveshow(signal[0:400])
plt.show()

"""## Carga de audios"""

# Librosa: load
# https://librosa.org/doc/latest/generated/librosa.load.html

# La función .load devuelve la señal (numpy) y la tasa de muestreo (int) de un fichero de audio
# Admite varios formatos de audio (los soportados por soundfile)
# librosa usa por defecto:
#  - una tasa de muestreo sr=22050 (para conservar la original sr=None)
#  - transforma la señal en mono (salvo que mono=False)

import librosa

name="brahms"
audio_file=librosa.ex(name)
print("Fichero de audio: ",audio_file)


# signal, sr = librosa.load(audio_file,sr=22050,mono=False)
signal, sr = librosa.load(audio_file)
print("Tipo de la señal:", type(signal))
print("Tipo de la tasa:", type(sr))

print("Tasa de muestreo",sr)
print("Tipo de las muestras:", signal.dtype)
print("Forma:", signal.shape)
print("Número total de muestras:", signal.shape[0])
print("Valores mínimos y máximos:",signal.min(),signal.max())

# Duracion = numero_total_de_muestras/tasa_de_muestreo
print("Duración:",signal.shape[0]/sr)

plt.figure(figsize=(7,3))
v0=0
v1=-1
librosa.display.waveshow(signal[v0:v1],color='red')
plt.show()

ipd.Audio(signal,rate=sr)

"""## Características de las señales de audio"""

# Librosa: Duracion y tasa de muestreo

# https://librosa.org/doc/latest/generated/librosa.get_samplerate.html
import librosa
name='brahms'
audio_file=librosa.ex(name)

sr = librosa.get_samplerate(audio_file)
sample_duration = 1/sr
print(f"Sample Rate={sr} - Duración de una muestra: {sample_duration:0.6f}")


# https://librosa.org/doc/latest/generated/librosa.get_duration.html

signal, sr = librosa.load(audio_file)
duracion= librosa.get_duration(y=signal)
print(f"Duracion del audio {duracion:0.2f}")

"""# Caracterización del sonido

El sonido se caracteriza fundamentalmente por tres parámetros:
- altura
- volumen
- timbre

Veremos la vinculación de estas características con el modelo matemático.

## Tono musical y frecuencia

La altura o tono de una nota está relacionada con la frecuencia de la señal: a mayor frecuencia, más agudo percibimos el sonido.

En música occidental las notas se nombran como A, B, C, D, E, F, G (o la, si, do, re, mi, fa, sol). Entre notas consecutivas suele haber un tono, salvo entre mi-fa y si-do, donde hay medio tono.

La escala cromática incluye las doce notas dentro de una octava.

Las notas se organizan en octavas: al pasar de una octava a la siguiente, la frecuencia se duplica, pero la nota se percibe como una versión más aguda de la misma.

Por eso una misma nota aparece repetida en distintas octavas, por ejemplo A0, A1, A2, ..., A4. El número indica la octava en la que está situada la nota.

Por convenio, la nota A4 corresponde a 440 Hz.

<img width="600" height="200" src="./images/octavas.png">
"""

# Libros: Conversión entre Frecuencia y Nota musical
import librosa

sr=22050

notaMusical='a4'
frecuencia=librosa.note_to_hz(notaMusical)
print(f"Frecuencia de la nota {notaMusical}: {frecuencia:0.4f}")

tone=librosa.tone(frecuencia,duration=2, sr=sr)
librosa.display.waveshow(tone[0:400],color='red')
plt.show()
ipd.Audio(tone, rate=sr)

"""## MIDI

El estándar MIDI (Musical Instrument Digital Interface ) es un protocolo especializado en el intercambio de información musical.

El protocolo MIDI asocia a cada nota musical un código (p) que nos permite formalizar la relación entre tono (pitch) y frecuencia.

En particular, la nota A4 tiene asociado el código 69.

$$F(p) = 440 \times 2^{\frac{p-69}{12}}$$

<img  width="400" height="600" src="./images/midi-note.jpg">
"""

# Relación entre nota musical, nota MIDI y frecuencia
import librosa

def f(pitch):
  exp =  (pitch-69)/12
  return 440 * 2 ** exp

codigoMIDI=69
print(f"La frecuencia de la nota MIDI {codigoMIDI} es {f(codigoMIDI)}")
print("Código MIDI:",librosa.midi_to_hz(codigoMIDI))

frecuencia=440
print("--- Frecuencia:",frecuencia)
print("Nota Musical:" ,librosa.hz_to_note(frecuencia))
print("Código MIDI:",librosa.hz_to_midi(frecuencia))

"""# Entrada/Salida

## Formatos de audio

Un formato de audio guarda la señal y su metainformación principal:
- canales (mono, estéreo, ...)
- profundidad de bits
- frecuencia de muestreo. Teléfono=8000 Radio=22050 CD=44100 DVD=48000  HD-DVD= 96000

Formatos comunes: WAV, FLAC, AAC, MP3, OGG.

La señal puede almacenarse:
- Sin comprimir (ej. WAV)
- Comprimida: sin pérdida (FLAC) o con pérdida (MP3, OGG)

WAV: gran fidelidad, pero mayor tamaño de archivo.

<img width=500 height=500 src="./images/WAVEformat.png">

## Wave.py (E/S de ficheros WAV)

El módulo `wave` permite leer y escribir archivos WAV en Python.

La señal se maneja como `bytes` y normalmente se convierte a `int16` para procesarla con NumPy.

Puntos clave:
- lectura/escritura por bloques (`frames`)
- acceso a metadatos del audio (canales, frecuencia de muestreo, profundidad)
- conversión entre `bytes` y arrays numéricos

### Apertura y metadatos
"""

# Apertura de un archivo WAV con wave.py
# https://docs.python.org/3/library/wave.html#wave.open

import wave

RUTA="./audio/"
nombre="debussy.wav"
fichero_wav=RUTA+nombre

print("Fichero:",nombre)
# open en modo r devuelve un objeto Wave_read
wr_obj=wave.open(fichero_wav,'r')
print("Tipo:",type(wr_obj))

# Los objetos Wave_read tienen métodos para recurperar metainformación
print("Número de canales: ",wr_obj.getnchannels())
print("Profundidad de las muestras: ",wr_obj.getsampwidth(), " bytes")
print("Frecuencia de muestreo: ",wr_obj.getframerate(), "(Hz) muestras por segundo")
print("Total de frames: ",wr_obj.getnframes())

wr_obj.close()

"""### Lectura de frames"""

import wave
RUTA="./audio/"
nombre="debussy.wav"
fichero_wav=RUTA+nombre

wr_obj=wave.open(fichero_wav,'r')

nframes=wr_obj.getnframes()
print("Total frames leidos",nframes)

# Wave_read.setpos(pos) sitúa la posición del frame desde la que se realizará la lectura
pos=int(nframes/2)
wr_obj.setpos(pos)

# Wave_read.readframes(n) lee un máximo de n frames desde la posición de lectura
#               devuelve la señal con tipo bytes
byte_signal=wr_obj.readframes(int(nframes/4))
wr_obj.close()

print("--- Señal obtenida con Wave_read.readframes()")
print("Tipo",type(byte_signal))
print("Tamaño (frame) ",len(byte_signal))
print("Extracto: ",byte_signal[0:10])


# Reproducción de la señal

# https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html
# Transforma una cadena de tipo bytes a un array de tipo int16 (un entero por cada dos bytes consecutivos)
signal=np.frombuffer(byte_signal,dtype=np.int16)

print("--- Señal modificada para IPython.Audio")
print("Tipo",type(signal))
print("Tamaño (frame) ",len(signal))
print("Extracto: ",signal[0:10])

# ipd.Audio(fichero_wav)
sr=wr_obj.getframerate()
ipd.Audio(signal,rate=sr)

"""### Escritura de WAV"""

# Escritura de un archivo WAV con wave.py
# https://docs.python.org/3/library/wave.html#wave.open

import wave

RUTA="./audio/"
nombre_fichero_wav="nuevo.wav"
fichero_wav=RUTA+nombre_fichero_wav

sr=22050

# open en modo r devuelve un objeto Wave_write
ww_obj=wave.open(fichero_wav,'w')
print("Tipo:",type(ww_obj))

# Métodos para establecer las características de la señal
ww_obj.setnchannels(1)
ww_obj.setsampwidth(2)
ww_obj.setframerate(sr)


# Construcción de la señal a partir de una señal generada por librosa

# Las muestras generadas por librosa son float64 en el rango [-1,1]
tone =librosa.tone(421,duration=1.6, sr=sr)
print("--- Señal original\n",tone.dtype,tone[0:3])

# Normaliza las muestras de la señal tone a int16 con valores entre [-32767,32767]
signal=np.int16(tone * 32767)
print("--- Señal reescalada\n",signal.dtype,signal[0:3])

# Wave_write.writeframesraw() admite como parámetro numpy arrays
ww_obj.writeframesraw(signal)
ww_obj.close()

ipd.Audio(fichero_wav)

# -----------------------------------------------
# Para almacenar la señal en bytes
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tobytes.html
# Transforma una array de int16 a una cadena de tipo bytes (une 2 bytes en un entero)
# frames=signal.tobytes()
# print("--- Señal wav\n",type(frames),frames[0:3])
# ww_obj.writeframes(frames)
# ww_obj.close()

"""## Grabación

### SoundDevice.py (Grabación y Reproducción)

El módulo de Python sounddevice.py (https://pypi.org/project/sounddevice/) implementa una interfaz para Python de PortAudio  
- ofrece funciones para la reproducción y grabación de arrays Numpy cuyo contenido son señales de audio

NOTA: PortAudio https://www.portaudio.com/ es una biblioteca en C/C++ dedicada a la E/S de audio (es gratis, de libre distribución y multiplataforma)
"""

# Grabación de audio con SoundDevice
import sounddevice as sd

sr = 22100  # Sample rate
duration = 6  # Duration of recording
muestras=int(sr*duration)

print("**** Comienzo de la grabación")
#  https://python-sounddevice.readthedocs.io/en/0.4.6/api/convenience-functions.html#sounddevice.rec

# sd.rec comienza la grabación (frames se refiere al total de muestras)
#        devuelve un array numpy
signal = sd.rec(frames=muestras,samplerate=sr, channels=1)
sd.wait()  # Existe un método sd.stop() para traspasar el control al locutor
print("**** Fin de la grabación")

# Detalles sobre la señal grabada por sounddevice.py
print("Tipo de la señal grabada", type(signal))
print("Forma:",signal.shape)
print("Tipo de las muestras:",signal.dtype)
print("Extracto",signal[0:4])

# Recuperamos la primera columna de cada elemento (muestras del canal 0)
muestras_canal_cero=signal[...,0]
print("Extracto",muestras_canal_cero)

# Reproducción de audio con SoundDevice
import matplotlib.pyplot as plt

plt.figure(figsize=(10,2))
t = np.linspace(0,duration,int(sr*duration))
plt.plot(t,signal)
plt.show()
sd.play(signal,sr)

# display.Audio acepta entradas mono o estéreo (pero en este caso la forma es (canal,muestras)
# Reducimos la señal estéreo a una señal mono seleccionando para cada muestra su primera columna
# ipd.Audio(signal[...,0],rate=sr)

"""# **☞ Ejercicio entregable**: Segmentación

Mediante el paquete librosa (effects.split), segmentar un audio en fragmentos que no contienen silencio.
Seleccionar uno de los intervalos para reproducirlo.

Para este ejercicio, por comodidad puede usarse alguno de los audios que ofrece librosa (ej: brahms)

A partir de este ejercicio realizar los siguientes:
- Grabar un locutor contando de forma pausada del 1 al 9.
- Segmentar el audio para cada número.

# **☞ Ejercicio entregable**: Melodía

Podemos representar una melodía mediante una lista de tuplas (nota, duración).
- Ejemplo: [("c4",3),("d4",2),("c4",2),("e4",3),("f4",3) ]

Definir una funcion audio_melodia(melodia) que devuelva una señal de audio para la melodia dada como parámetro.

NOTA: Hacer uso del paquete librosa para la generación de la señal de cada uno de los componentes de la melodía.
"""