# -*- coding: utf-8 -*-
"""AINE 2025 - AUD.1 - Recetario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ac42rl-RBJAnCFJ2E2cBgfRMP4KLssg

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

# AUDIO 1: RECETARIO
Última modificación: 19 de marzo de 2026
"""

import numpy as np
import matplotlib.pyplot as plt
import torch
import torchaudio
import librosa
import os

CARPETA="./audio/"

# El fichero Debussy es una grabación mono (un canal)
NAME_01="debussy.wav"
# El fichero piano_c es una grabación estéreo (dos canales)
NAME_02="piano_c.wav"

# Seleccionamos entre NAME_01, NAME_02
NAME=NAME_02
audio_file = os.path.join(CARPETA,NAME)

"""# Carga

Dado un fichero de audio, la carga devuelve la señal y la tasa de muestreo (sr)

Veremos dos alternativas: librosa y torchaudio.
- librosa devuelve un array numpy y torchaudio un tensor
- librosa aplica por defecto mezcla y reajusta la señal con un tasa de muestreo (mono=True y sr=22050)
    - Si queremos obtener la señal original con librosa (mono=False y sr=None)

### Nota de soporte (Windows): error al usar torchaudio.load

Si aparece un error al cargar `torchcodec` o DLLs en `torchaudio.load`, instala FFmpeg en versión **shared** (no la versión estática).

Enlace recomendado:
- https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-8.0.1-full_build-shared.7z

Pasos rápidos:
1. Descargar y descomprimir en una carpeta (por ejemplo `C:\ffmpeg_shared`).
2. Comprobar que en `C:\ffmpeg_shared\bin` existen DLLs como `avcodec-*.dll`, `avformat-*.dll`, `avutil-*.dll`.
3. Añadir `C:\ffmpeg_shared\bin` al PATH de Windows.
   - PowerShell: `setx PATH "$([Environment]::GetEnvironmentVariable('Path','User'));C:\ffmpeg_shared\bin"`
4. Cerrar y abrir VS Code, y reiniciar el kernel del notebook.
5. Verificar en terminal: `ffmpeg -version`.
"""

# Carga de audio

# Mediante librosa:
# dado un audio devuelve la señal en un array numpy
# parámetros por defecto:  mono=True sr=22050
signal_librosa,sr_librosa=librosa.load(audio_file,mono=False,sr=None)
print(f"{type(signal_librosa)} -- {sr_librosa} -- {signal_librosa.shape}")


# Mediante torchaudio:
# dado un audio devuelve la señal en un tensor (y cada canal de audio en un tensor)
signal_torchaudio, sr_torchaudio=torchaudio.load(audio_file)
print(f"{type(signal_torchaudio)} -- {sr_torchaudio} -- {signal_torchaudio.shape}")

"""# Mezcla

# Reproducción


Una de los métodos más usados para la reproducción de un audio es IPython.display.Audio

- Admite la reproducción de señales mono y multicanal:
- Parámetros:
    - Una señal (array numpy)
    - rate (tasa de muestreo sr)
"""

import IPython.display as ipd

# Señal procedente de librosa (numpy)
signal=signal_librosa
sr=sr_librosa

# Señal procedente de torchaudio (tensor)
# ---  Cambiar la señal de tensor a numpy
# signal=signal_torchaudio.numpy()
# sr=sr_torchaudio


ipd.Audio(signal,rate=sr)

"""# Visualización

Para la visualización de la señal (dominio temporal), el paquete librosa ofrece display.waveshow (que se apoya en matplotlib)

- Admite representación de señales mono y estéreo (el paquete mezcla de forma interna las señales)
- La señal debe ser un array numpy
"""

signal=signal_librosa
signal=signal_torchaudio.numpy()

plt.figure(figsize=(10,2))
librosa.display.waveshow(signal)
plt.title(NAME)
plt.show()

"""# Transformada de Fourier

La Transformada de Fourier (TF) devuelve la representación frecuencial de una señal.

- Determina la aportación de cada frecuencia en el total de la señal
- Esa aportación se representa con un número **complejo**  (denominado coeficiente)

El método que usaremos es la implementación de la TF ofrecida en el paquete scipy (fft.fft)
- Este método requiere que la señal sea un array numpy
- Admite señales mono y estéreo

Representación del dominio frecuencial de la señal
- A la hora de representar la Transformada de Fourier se muestra la *magnitud* de los coeficentes (valor absoluto del número complejo)
- Por el teorema de Nyquist, el diagrama es simétrico
- Si la señal es estéreo, es conveniente mezclar la señal antes de calcular su Transformada (para facilitar la representación con matplotlib)

"""

import scipy as sc

signal=signal_librosa
signal=signal_torchaudio.numpy()


# Mezcla de la señal si es estéreo: no es necesario para sc.fft.fft pero si es conveniente para matplotlib
print(type(signal))
print(signal.shape)
if signal.shape[0]==2:
    signal=np.mean(signal,axis=0)
print(signal.shape)


ft_signal=sc.fft.fft(signal)
print("Tipo de los valores de la señal:",signal.dtype)
print("Tipo de los valores de la transformada:",ft_signal.dtype)

# Representación de la transformada
# Se obtiene la magnitud de cada uno de los coeficientes
magnitudes=np.abs(ft_signal)

plt.figure(figsize=(10,4))
v0=0
v1=-1
plt.plot(magnitudes[v0:v1])
plt.title(NAME)
plt.show()

"""# Espectrogramas

La transformada de Fourier calcula la aportación de cada frecuencia en el global de la audio.

El espectrograma refleja esa aportación en cada instante.

- La técnica habitual es calcular la transformada de Fourier sobre franjas (frames) de audio que se desplazan de izquierda a derecha hasta cubrir todo el audio.
- Por tanto, se debe fijar el número de muestras contenida en una franja (frame size) y el número de muestras que avanza (hop size) cada franja durante el desplazamiento.
- El valor hop suele ser menor estricto que el valor frame con idea de que las franjas sucesivas se solapen.

Ejemplo: Un audio con 100 muestras y un tamaño de franja de 20 muestras.
- Si el desplazamiento hop es de 20 muestras se aplicará 5 veces las transformada de Fourier (cinco franjas que no se solapan)
- Si el desplazamiento hop es de 10 se aplicará 10 veces las transformada de Fourier (las franjas se solapan)

Para calcular el espectograma usaremos librosa y torchaudio.
- librosa (stft): (de Short Time Fourier Transform)
- torchaudio (transforms.Spectrogram)

Ambos se aplican sobre la señal e internamente calculan la transformada.

Opcionalmente se puede indicar (ambos tienen valores prefijados por defecto):
- el número de muestras que incluye cada franja (frame) (ej: 2024)
- el número de muestras de desplazamiento (hop) (ej: 214)
- la tasa de muestreo sr

El espectrograma devuelve una estructura bidimensional: (frecuencia, numero_de_frame) -> coeficiente

Representación del espectrograma
- Para la representación del espectrograma se dispone de librosa.display.specshow
    - requiere que el espectrograma de entrada sea un array numpy
    - el espectrograma debe proceder de una señal mono (por lo que debe mezclarse la señal antes)
- A la hora de representar el espectrograma se muestra la *magnitud* de los coeficentes (valor absoluto del número complejo)
    - En librosa, las magnitudes se obtienen mediainte numpy.abs()
    - En torchaudio, la salida del espectrograma se determina con el parámetro _power_

- En el caso de los espectrogramas es habitual potenciar el resultado aplicando una escala logarítmica (amplitud_to_db) para reflejar nuestra percepción logarítmica de la frecuencias






"""

# Espectrograma mediante librosa

# OJO: mono=True para obtener la señal mezclada (y evitar tenerla que mezclar después)
signal_librosa,sr_librosa=librosa.load(audio_file,mono=True,sr=None)

# Se obtienen los coeficientes del espectrograma de la señal
spec_librosa=librosa.stft(signal_librosa)
# Se calculan las magnitudes de los coeficientes
magnitudes=np.abs(spec_librosa)
# Se reescala logarítmicamente las magnitudes
spec_librosa=librosa.amplitude_to_db(magnitudes)

spec=spec_librosa

plt.figure(figsize=(10,2))
librosa.display.specshow(spec)
plt.title(NAME)
plt.show()

# Espectrograma mediante torchaudio
signal_torchaudio, sr_torchaudio=torchaudio.load(audio_file)

# Se mezcla la señal a mono (para facilitar su visualización)
signal_torchaudio=torch.mean(signal_torchaudio,dim=0)

# Se definen dos transformaciones
#   - Calculo del espectograma
#   - Reescala logarítmica de las magnitudes
spectrogram_transform = torchaudio.transforms.Spectrogram(power=2)
spec_amplitud_to_db_transform = torchaudio.transforms.AmplitudeToDB()

spec_torchaudio = spectrogram_transform(signal_torchaudio)
spec_torchaudio=spec_amplitud_to_db_transform(spec_torchaudio)

print(spec_torchaudio.shape)
spec=spec_torchaudio.squeeze().numpy()


plt.figure(figsize=(10,2))
librosa.display.specshow(spec)
plt.title(NAME)
plt.show()