# -*- coding: utf-8 -*-
"""AINE 2026 - IMG.1 - Introduccion (ESCRIBE AQUI TU UVUS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBUPRY_H-I_RFO54pXtgfY8Rx-SiPg24

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

**Escriba aquí su nombre y apellidos:**

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:
* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable")

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**

# IMÁGENES 1: Introducción

Última modificación: 9 de marzo de 2026

Este cuaderno es una revisión de las capacidades que ofrecen la biblioteca PyTorch y Pillow en el terreno del procesamiento de imágenes. Los subsecuentes cuadernos profundizarán sobre los conceptos que figuran en este primer cuaderno.


Existen un conjunto de bibliotecas especializadas en redes neuronales para diversas modalidades:
- Imagen (torchvision)
- Audio (torchaudio)
- Texto (torchtext)

Estas bibliotecas auxiliares son independientes de Pytorch, pero dependen de ella para su ejecución.

URLs:
- https://pytorch.org
- https://pytorch.org/vision/stable/index.html


Para la instalación:
https://pytorch.org/get-started/locally/

---
**Contenido**

1. Ecosistema PyTorch — `torch`, `torchvision`
2. Preparación de los datos — `Dataset`, `DataLoader`, MNIST
3. Definición de la red — `torch.nn.Module`, capas, `Sequential`
4. Ejecución de la red — forward pass, `softmax`, `argmax`
5. Entrenamiento y validación — `CrossEntropyLoss`, `SGD`, épocas
6. ☞ **Ejercicio**: Red MLP multicapa con tensores
7. Pillow (PIL) — manipulación de imágenes: creación, recorte, dibujo, filtros, composición
8. Formato HWC vs CHW — puente PIL ↔ Tensor
9. ☞ **Ejercicio**: Tablero de ajedrez con PIL

---
"""

import torch
import torchvision

# ¿Qué métodos ofrece el objeto torch?
print(dir(torch))

# Muestra la versión instalada de pytorch y la carpeta donde está instalado
# El contenido de la carpeta es un medio para hacerse una idea de la arquitectura utilizada por la biblioteca
print(torch.__version__)
print(torch.__path__)

# ¿Qué métodos ofrece el objeto torchvision?
print(dir(torchvision))

# Muestra la versión instalada de torchvision y la carpeta donde está instalado
# El contenido de la carpeta es un medio para hacerse una idea de la arquitectura utilizada por la biblioteca
print(torchvision.__version__)
print(torchvision.__path__)

"""## Preparación de los datos

Para la definición y gestión de los datos, Pytorch ofrece las clases Datasets y Dataloader.

Torchvision ofrece un conjunto de corpus de imágenes ya preparados (Ej: MNIST)
"""

# Carga de los datos almacenados en un dataset (corpus etiquetado)
PATH_ROOT="./datasets"

training_data=torchvision.datasets.MNIST(
   root=PATH_ROOT,
   train=True,
   download=True,
   transform=torchvision.transforms.ToTensor(),
   target_transform=None
)

test_data=torchvision.datasets.MNIST(
   root=PATH_ROOT,
   train=False,
   download=True,
   transform=torchvision.transforms.ToTensor(),
   target_transform=None
)

# Acceso a los ejemplares del corpus (imagen, etiqueta) del corpus
# Visualización de las imagénes mediante pyplot
import matplotlib.pyplot as plt

index=3
imagen,etiqueta=training_data[index]

plt.figure(figsize=(1,1))
plt.title(f"Etiqueta: {etiqueta}")
plt.imshow(imagen.squeeze())
plt.show()

# División en tandas de los ejemplares del corpus (Dataloader)
batch_size=32

train_dataloader=torch.utils.data.DataLoader(
  training_data,batch_size=batch_size)


test_dataloader=torch.utils.data.DataLoader(
  test_data,batch_size=batch_size)

# Acceso y recorrido de las tandas
X,y = next(iter(train_dataloader))
print(f"Primera tanda: Forma X",X.shape)
print(f"Primera tanda: Forma y",y.shape)

for i,(X,y) in enumerate(train_dataloader):
    if (i% 400==0): print("Tanda",i)

for i,(X,y) in enumerate(test_dataloader):
    if(i>=5):
        break
    print(y)

# Selección del dispositivo en el que se realizarán los cálculos
device = (
  "cuda"
  if torch.cuda.is_available()
  else "cpu" )

print(f"Dispositivo {device}")

"""## Definición de la red

El espacio de nombres torch.nn es donde se concentran todos los elementos necesarios para trabajar con redes neuronales

"""

# La red se organiza como un conjunto de módulos (contenedor de capas)
class NeuralNetwork(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten=torch.nn.Flatten()
    self.linear_relu_stack=torch.nn.Sequential(
      torch.nn.Linear(28*28,512),
      torch.nn.ReLU(),
      torch.nn.Linear(512,512),
      torch.nn.ReLU(),
      torch.nn.Linear(512,10)
    )

  def forward(self,x):
      x0=self.flatten(x)
      logits=self.linear_relu_stack(x0)
      return logits

"""## Ejecución de la red"""

import torch.nn.functional as F

# Creación de un modelo y su posterior ejecución
model=NeuralNetwork().to(device)

#  Ejecución sobre un ejemplar
index=0
xx,yy=training_data[index]
yy_pred=model(xx)
yy_pred_softmax = F.softmax(yy_pred, dim=1)
predicted_category = torch.argmax(yy_pred_softmax)
print(f"---- Categoria  ----\nEsperada {yy}\nSalidas {yy_pred_softmax}\nObtenida {predicted_category}")

# Ejecución sobre un conjunto de ejemplares (tanda)
X,y = next(iter(train_dataloader))
y_pred=model(X)
y_pred_softmax = F.softmax(y_pred, dim=1)
predicted_categories = torch.argmax(y_pred_softmax, dim=1)
print(f"---- Categorias  ----\nEsperada {y[:4]}\nSalidas {y_pred_softmax[:4]}\nObtenida {predicted_categories[:4]}")

"""## Entrenamiento y Validación

Los parámetros de la red neuronal pueden ser ajustados (torch.optim) para obtener mejores resultados en la clasificación.

"""

# Valoración de los resultados
loss_fn=torch.nn.CrossEntropyLoss()

# Método aplicado para reajustar los parámetros de la red
parametros=model.parameters()
optimizer=torch.optim.SGD(params=parametros,lr=1e-3)

# Ejecución, valoración y reajueste del modelo sobre los ejemplares de entrenamiento
def train(dataloader,model,loss_fn,optimizer):

  size=len(dataloader.dataset)
  model.train()


  for batch, (X,y) in enumerate(dataloader):
    X,y = X.to(device),y.to(device)

    pred=model(X)
    loss=loss_fn(pred,y)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if (batch % 100 ==0):
      loss = loss.item()

      current = (batch+1)*len(X)
      print(f"loss={loss:>7f} [{current:>5d}/{size:>5d}]")

# Ejecución y valoración del modelo sobre los ejemplares de validación
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)

            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

# Ciclo de ejecuciones de entranamiento y verificación
epochs = 3
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Fin de entrenamiento")

"""## **☞ Ejercicio entregable**: Red MLP multicapa con tensores

En la sección anterior hemos definido una red neuronal utilizando `torch.nn.Linear` y `torch.nn.ReLU`. Internamente, cada capa `Linear` realiza la operación $y = x \cdot W^T + b$ (un producto matricial más un sesgo) y `ReLU` aplica $\max(0, x)$ elemento a elemento.

El objetivo de este ejercicio es **reproducir manualmente con tensores** una red multicapa similar, para comprender qué sucede internamente en cada capa.

Modela con tensores aleatorios un **Perceptrón Multicapa (MLP)** con la siguiente arquitectura:

| Capa | Entrada | Salida |
|------|---------|--------|
| Capa 1 (oculta) | `num_atributos_entrada` | `num_neuronas_capa1` |
| Capa 2 (oculta) | `num_neuronas_capa1` | `num_neuronas_capa2` |
| Capa 3 (salida)  | `num_neuronas_capa2` | `num_clases` |

Para cada capa $l$, la salida se calcula como:

$$h^{(l)} = \text{ReLU}(h^{(l-1)} \cdot W^{(l)} + b^{(l)})$$

En la **última capa no se aplica ReLU** (se devuelven directamente los _logits_).

**Se pide:**
1. Crea los tensores de pesos $W$ y sesgos $b$ de cada capa con valores aleatorios y las dimensiones adecuadas.
2. Aplica la red a un conjunto de `num_entradas` de ejemplo (tensor aleatorio).
3. Muestra la salida de cada capa intermedia y la predicción final (`argmax`) para cada entrada.

**Pista**: La operación `torch.clamp(x, min=0)` implementa la función ReLU, y el operador `@` realiza el producto matricial.

## Pillow (PIL Fork)

https://pillow.readthedocs.io/en/stable/index.html

Aunque `torchvision.transforms` ofrece muchas operaciones sobre imágenes, **PIL (Pillow) es la capa que está por debajo**: es la biblioteca que `torchvision` utiliza internamente para abrir y manipular las imágenes. Conocer PIL es necesario en la práctica por varios motivos:

- **Datasets personalizados**: cuando se construyen datasets propios, las imágenes llegan como ficheros (`.jpg`, `.png`...) y es PIL quien las abre. Si una imagen está corrupta, tiene un modo inesperado (RGBA, CMYK, paleta) o requiere preprocesamiento, se necesita PIL para diagnosticar y resolver el problema.
- **Operaciones sin equivalente en torchvision**: dibujar formas, trazar bounding boxes, escribir texto sobre imágenes o generar datos sintéticos requiere `ImageDraw`, que no tiene equivalente directo en torchvision.
- **Inspección y depuración**: cuando el modelo produce resultados extraños, lo primero es visualizar las imágenes que recibe. Saber convertir entre PIL, tensores y matplotlib es esencial para depurar.
- **Interoperabilidad**: PIL es el formato común entre bibliotecas de Python (matplotlib, OpenCV, Gradio, Streamlit, ONNX...). Muchas APIs externas esperan objetos PIL como entrada o salida.

---

PIL es una biblioteca en Python especializada en la manipulación de imágenes.

- La imagen se almacena en un (objeto PIL)
- El objeto PIL representa las imágenes con un modelo HWC (Height, Width, Channel)
- La imagen es una estructura bidimensional (HxW) donde cada pixel es:
    - un número (monocromo)
    - o una tupla de números (valores de los canales)
- PIL denomina banda (_band_) a cada uno de los canales
- Admite diversos formatos de imágenes: .png, jpeg,...
- Admite diversos _modos_ que básicamente determinan
    - Profundidad (tamaño en bits del pixel):  1-bit, 8-bit, 16-bits
    - Esquemas de color:  L (Monocromo), RGB, HSV,

Tutorial: https://pillow.readthedocs.io/en/stable/handbook/tutorial.html
"""

import PIL
print(dir(PIL))
print(PIL.__version__)
print(PIL.__path__)

from PIL import Image
print(dir(Image))

from PIL import Image
from PIL import ImageFilter
import matplotlib.pyplot as plt

# La imagen torreDelOro.jpg (de uso público) es cortesía de pixabay:
# URL https://pixabay.com/es/photos/torre-oro-sevilla-espa%C3%B1a-andaluc%C3%ADa-2064129/

# Apertura de una imagen (fichero) y almacenamiento en un objeto PIL
img=Image.open("./img/torreDelOro.jpg")
print("Tipo: ",type(img))
print("Detalles: ", img.format, img.size, img.mode)
print(" ----------------")

# Operaciones con el objeto PIL
img_rot=img.rotate(45)
img_blur= img.filter(ImageFilter.BoxBlur(radius=9))


# Visualización del objeto PIL mediante matplotlib
plt.figure(figsize=(10,4))
plt.subplot(1,3,1)
plt.imshow(img)
plt.subplot(1,3,2)
plt.imshow(img_rot)
plt.subplot(1,3,3)
plt.imshow(img_blur)
plt.show()

"""### Creación de imágenes desde cero

`Image.new(mode, size, color)` crea una imagen vacía. Los píxeles se pueden manipular individualmente con `putpixel` y `getpixel`.
"""

from PIL import Image
import matplotlib.pyplot as plt

# Crear una imagen negra de 100x100 en modo RGB
img = Image.new("RGB", (100, 100), (0, 0, 0))

# Dibujar una línea diagonal blanca píxel a píxel
for i in range(100):
    img.putpixel((i, i), (255, 255, 255))

# Crear una imagen con color de fondo
img_azul = Image.new("RGB", (100, 100), (30, 100, 200))

plt.figure(figsize=(8, 3))
plt.subplot(1, 2, 1)
plt.title("Diagonal")
plt.imshow(img)
plt.subplot(1, 2, 2)
plt.title("Fondo azul")
plt.imshow(img_azul)
plt.show()

"""### Recorte, redimensión y conversión de modo

- `crop((left, upper, right, lower))` extrae una región rectangular de la imagen.
- `resize((width, height))` cambia el tamaño de la imagen.
- `convert(mode)` convierte entre modos de color (ej: `"RGB"` → `"L"` para escala de grises).
"""

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open("./img/torreDelOro.jpg")

# Recorte: extraer una región (left, upper, right, lower)
w, h = img.size
img_crop = img.crop((w//4, h//4, 3*w//4, 3*h//4))

# Redimensión
img_small = img.resize((64, 64))

# Conversión a escala de grises
img_gray = img.convert("L")

plt.figure(figsize=(12, 3))
plt.subplot(1, 4, 1)
plt.title(f"Original {img.size}")
plt.imshow(img)
plt.subplot(1, 4, 2)
plt.title(f"Recorte {img_crop.size}")
plt.imshow(img_crop)
plt.subplot(1, 4, 3)
plt.title(f"Redimensión {img_small.size}")
plt.imshow(img_small)
plt.subplot(1, 4, 4)
plt.title(f"Grises ({img_gray.mode})")
plt.imshow(img_gray, cmap="gray")
plt.tight_layout()
plt.show()

"""### Dibujo con ImageDraw

El módulo `ImageDraw` permite dibujar formas geométricas y texto directamente sobre una imagen PIL.

https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html
"""

from PIL import Image, ImageDraw
import matplotlib.pyplot as plt

img = Image.new("RGB", (200, 200), (240, 240, 240))
draw = ImageDraw.Draw(img)

# Rectángulo relleno
draw.rectangle([20, 20, 90, 90], fill="red", outline="darkred", width=2)

# Elipse rellena
draw.ellipse([110, 20, 180, 90], fill="blue", outline="navy", width=2)

# Línea
draw.line([(20, 130), (180, 130)], fill="green", width=3)

# Polígono (triángulo)
draw.polygon([(100, 110), (60, 180), (140, 180)], fill="orange", outline="black")

# Texto
draw.text((20, 182), "PIL ImageDraw", fill="black")

plt.figure(figsize=(4, 4))
plt.title("Dibujo con ImageDraw")
plt.imshow(img)
plt.axis("off")
plt.show()

"""### Convolución con filtros Kernel

`ImageFilter.Kernel(size, kernel)` permite aplicar operaciones de convolución definiendo un kernel personalizado.

https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.Kernel

<img witdth="300" height="300" src="./img/convolucion.png">
"""

from PIL import Image, ImageFilter
import matplotlib.pyplot as plt

img = Image.open("./img/torreDelOro.jpg")

# Kernel de enfoque (sharpen)
kernel_sharpen = (0, -1, 0,
                  -1,  5, -1,
                   0, -1, 0)

# Kernel de detección de bordes (Sobel horizontal)
kernel_bordes = (-1, -1, -1,
                  0,  0,  0,
                  1,  1,  1)

img_sharpen = img.filter(ImageFilter.Kernel((3, 3), kernel_sharpen))
img_bordes = img.filter(ImageFilter.Kernel((3, 3), kernel_bordes, scale=1, offset=128))

plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.title("Original")
plt.imshow(img)
plt.subplot(1, 3, 2)
plt.title("Enfoque (Sharpen)")
plt.imshow(img_sharpen)
plt.subplot(1, 3, 3)
plt.title("Detección de bordes")
plt.imshow(img_bordes)
plt.tight_layout()
plt.show()

"""### Composición: pegar y combinar imágenes

`paste(img, box)` permite pegar una imagen sobre otra. Combinado con `crop` y `resize`, permite componer imágenes a partir de fragmentos.
"""

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open("./img/torreDelOro.jpg")

# Crear un lienzo (canvas) más grande
canvas = Image.new("RGB", (img.width * 2, img.height), (200, 200, 200))

# Pegar la imagen original a la izquierda
canvas.paste(img, (0, 0))

# Pegar una versión en espejo a la derecha
img_flip = img.transpose(Image.FLIP_LEFT_RIGHT)
canvas.paste(img_flip, (img.width, 0))

plt.figure(figsize=(10, 4))
plt.title("Composición: original + espejo")
plt.imshow(canvas)
plt.axis("off")
plt.show()

"""### Formato de imagen: HWC vs CHW

Las imágenes en color se representan como arrays tridimensionales, pero existen dos convenciones para ordenar las dimensiones:

| Formato | Forma | Usado por |
|---------|-------|-----------|
| **HWC** (Height × Width × Channels) | `(alto, ancho, 3)` | PIL, matplotlib, numpy, OpenCV |
| **CHW** (Channels × Height × Width) | `(3, alto, ancho)` | **PyTorch** |

Es fundamental tener clara esta diferencia porque:
- Al cargar una imagen con PIL se obtiene formato HWC.
- PyTorch espera tensores en formato CHW para sus redes convolucionales.
- Al visualizar con matplotlib se necesita HWC de nuevo.

La transformación `torchvision.transforms.ToTensor()` realiza automáticamente la conversión HWC → CHW (y normaliza los valores de 0-255 a 0.0-1.0).
"""

from PIL import Image
import torch
import numpy as np

img_pil = Image.open("./img/torreDelOro.jpg")

# PIL → numpy (HWC)
img_np = np.array(img_pil)
print(f"Numpy (HWC): shape={img_np.shape}, dtype={img_np.dtype}, rango=[{img_np.min()}, {img_np.max()}]")

# PIL → Tensor PyTorch (CHW, float 0-1) mediante ToTensor()
to_tensor = torchvision.transforms.ToTensor()
img_tensor = to_tensor(img_pil)
print(f"Tensor (CHW): shape={img_tensor.shape}, dtype={img_tensor.dtype}, rango=[{img_tensor.min():.2f}, {img_tensor.max():.2f}]")

# Acceso a los canales individuales del tensor
canal_R = img_tensor[0]  # Primera "capa" = rojo
canal_G = img_tensor[1]  # Segunda "capa" = verde
canal_B = img_tensor[2]  # Tercera "capa" = azul
print(f"Canal R: shape={canal_R.shape}")

"""### Puente PIL ↔ Tensor

En la práctica necesitamos convertir entre PIL y tensores constantemente:
- **PIL → Tensor**: para alimentar la red neuronal (`transforms.ToTensor()`)
- **Tensor → PIL**: para visualizar resultados o guardar imágenes (`transforms.ToPILImage()`)

`permute(1, 2, 0)` convierte manualmente CHW → HWC (necesario para `matplotlib.imshow`).
"""

from PIL import Image
import torch
import torchvision
import matplotlib.pyplot as plt

img_pil = Image.open("./img/torreDelOro.jpg")

# ---- PIL → Tensor (CHW) ----
to_tensor = torchvision.transforms.ToTensor()
img_tensor = to_tensor(img_pil)
print(f"PIL → Tensor: {img_tensor.shape}  (CHW, float 0-1)")

# ---- Tensor → PIL ----
to_pil = torchvision.transforms.ToPILImage()
img_recuperada = to_pil(img_tensor)
print(f"Tensor → PIL: {img_recuperada.size}, modo={img_recuperada.mode}")

# ---- Visualización: tensor CHW → HWC con permute ----
img_hwc = img_tensor.permute(1, 2, 0)  # CHW → HWC
print(f"Tensor permutado (HWC): {img_hwc.shape}")

plt.figure(figsize=(12, 3))
plt.subplot(1, 3, 1)
plt.title("Original (PIL)")
plt.imshow(img_pil)
plt.axis("off")
plt.subplot(1, 3, 2)
plt.title("Tensor → permute → imshow")
plt.imshow(img_hwc)
plt.axis("off")
plt.subplot(1, 3, 3)
plt.title("Tensor → ToPILImage")
plt.imshow(img_recuperada)
plt.axis("off")
plt.tight_layout()
plt.show()

"""## **☞ Ejercicio entregable**: Tablero de ajedrez con PIL

Crea una imagen PIL en modo RGB de tamaño $n \times n$ que represente un **tablero de ajedrez** de $k \times k$ casillas.

**Se pide:**

1. Crea la imagen utilizando `Image.new` y `ImageDraw.rectangle` (o `putpixel`).
2. Las casillas deben alternar entre dos colores a elegir (por ejemplo, blanco y negro, o blanco y verde).
3. Dibuja un **borde** alrededor del tablero utilizando `ImageDraw`.
4. Guarda la imagen resultante en un fichero PNG con `img.save(...)`.
5. Muestra el resultado con `matplotlib`.

**Parámetros sugeridos:** $n = 400$, $k = 8$ (tablero estándar de 8x8).

**Pista:** El tamaño de cada casilla es $n / k$. Una casilla en la fila $i$, columna $j$ es "clara" si $(i + j)$ es par, y "oscura" si es impar.
"""