# -*- coding: utf-8 -*-
"""AINE 2026 - AUD.3 - Torchaudio (ESCRIBE AQUI TU UVUS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao8WEMRJXSfz7fHwhpSwJ4yx4iBXoHrB

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

**Escriba aquí su nombre y apellidos:**

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:
* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable")

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**

# AUDIO 3: TORCHAUDIO
Última modificación: 19 de marzo de 2026
"""

import numpy as np
import matplotlib.pyplot as plt
import IPython.display as ipd
import torch
import torchaudio

"""# Torchaudio

https://pytorch.org/audio/stable/index.html

El paquete de Python _torchaudio_ está especializado en la manipulación de redes neuronales para la modalidad de audio.

<img width="600" height="200" src="./images/clasificacion.png">

# Representación de una señal

Podemos representar las señales de audio mediante tres gráficas:
- Dominio temporal
- Dominio frecuencial (FT=Fourier Transform, FFT = FastFT, DFT=Discrete Fast Fourier)
- Espectrogramas: Dominio temporal-frecuencial (STFT= Short Time FT)

<img width=500 height=200 src="./images/signal-domains.png">

## Dominio temporal

La gráfica muestra para cada instante de tiempo la intensidad de la señal (amplitud)

El método torchaudio.load devuelve una tupla[Tensor, int] donde se  almacena
la señal y su tasa de muestreo.

https://pytorch.org/audio/main/generated/torchaudio.load.html
"""

# Representación del una señal respecto al dominio temporal
import os
import librosa
CARPETA="./audio/"
# NAME="debussy.wav"
NAME="piano_c.wav"
audio_file = os.path.join(CARPETA,NAME)


# El resultado obtenido por torchaudio.load es un tensor que contiene un tensor con la señal de cada canal
# https://pytorch.org/audio/main/generated/torchaudio.load.html

signal,sr = torchaudio.load(audio_file)
print(type(signal))
print(signal.dtype)
print(signal.shape)
print(signal)
print("Tasa de muestreo",sr)

# Alternativa con paquete librosa:
# Por defecto librosa devuelve la señal:
#   - mono  (salvo que se indique lo contrario mediante mono=False)
#   - con tasa sr 22050 (salvo que se indique lo contrario en el parámetro sr)
mono=False
# signal_librosa,sr_librosa=librosa.load(audio_file,mono=mono)
signal_librosa,sr_librosa=librosa.load(audio_file,mono=mono,sr=sr)


print("Forma señal (librosa):",signal_librosa.shape)
print("Forma señal (librosa):",signal_librosa)
print("Tasa de muestreo (librosa):",sr_librosa)

# Para representar gráficamente la señal en librosa o matplotlib
# la señal debe ser un array numpy (no admite tensores pytorch)
signal=signal.numpy()

# OJO:
# - librosa.display.waveshow admite señales multicanal(mono, estéreo, etc)
# - matplotlib sólo admite señales mono

plt.figure(figsize=(5,7))
plt.title(NAME)
plt.subplot(2,1,1)

librosa.display.waveshow(signal,sr=sr,color="#f44",alpha=0.8)
plt.subplot(2,1,2)
librosa.display.waveshow(signal_librosa,sr=sr,color="#f44",alpha=0.8)
plt.show()

ipd.Audio(signal,rate=sr)
# ipd.Audio(signal_librosa,rate=sr)

"""## Dominio frecuencial

La transformada de Fourier $FT$ es una función que asocia a cada frecuencia un número complejo que refleja la aportación _global_ de dicha frecuencia en la señal de audio.

El paquete scipy incluye una implementación de la Transformada Rápida de Fourier (FFT).
"""

# FFT de una señal: carga, paso a mono y representación
import os
import scipy as sc
CARPETA="./audio/"
# NAME="debussy.wav"
NAME="piano_c.wav"
audio_file = os.path.join(CARPETA, NAME)

signal, sr = torchaudio.load(audio_file)
signal = torch.mean(signal, dim=0)  # Mono para simplificar FFT y visualización
signal = signal.numpy()

ft = sc.fft.fft(signal)
magnitude = np.absolute(ft)

print("Shape señal:", signal.shape)
print("Shape FT:", ft.shape)
print("Shape magnitud FT:", magnitude.shape)

plt.figure(figsize=(10, 5))
plt.plot(magnitude[: len(magnitude) // 2])
plt.xlabel("Frequency (Hz)")
plt.ylabel("Magnitude")
plt.show()

"""## Espectrogramas

El espectrograma es una representación en el dominio tiempo-frecuencia que nos informa del impacto de cada frecuencia en cada instante de tiempo.

La transformada STFT (Short Time Fourier Transform) se basa en dividir la señal de audio en bloques (_frames_) y aplicar la Transformada de Fourier en cada bloque.

<img width="400" height="200" src="./images/frame.jpg">

Los paquetes librosa y torchaudio disponen métodos para calcular el espectrograma de una señal:
- librosa: https://librosa.org/doc/latest/generated/librosa.stft.html
- torchaudio: https://pytorch.org/audio/stable/generated/torchaudio.transforms.Spectrogram.html

"""

# Espectrograma STFT

import os
import librosa

CARPETA="./audio/"
NAME="duke.wav"
NAME="noise.wav"
NAME="scale.wav"
NAME="piano_c.wav"
NAME="debussy.wav"

audio_file = os.path.join(CARPETA,NAME)

# https://pytorch.org/audio/stable/generated/torchaudio.transforms.Spectrogram.html
# https://pytorch.org/audio/stable/generated/torchaudio.transforms.AmplitudeToDB.html
signal,sr = torchaudio.load(audio_file)

# Transformamos la señal a mono (remix) para acelerar los cálculos
print("Señal original")
print(signal.shape)
print(signal)
signal=torch.mean(signal,dim=0)
print("Señal mezclada (mono)")
print(signal.shape)
print(signal)


# power=2: Calcula la POTENCIA del espectrograma (magnitud al cuadrado)
# Acentúa más las frecuencias con mayor energía, mejorando la distinción visual
spec_transform = torchaudio.transforms.Spectrogram(power=2)

# AmplitudeToDB: Convierte a escala logarítmica (decibelios, dB)
# Los humanos percibimos el sonido de forma logarítmica, no lineal
# También comprime el rango dinámico para mejor visualización
spec_amplitud_to_db_transform = torchaudio.transforms.AmplitudeToDB()

# Versión 1: Potencia (power=2)
spectrogram=spec_transform(signal)
# Versión 2: Conversión a dB (escala logarítmica perceptualmente relevante)
spectrogram=spec_amplitud_to_db_transform(spectrogram)

print("Formas (shape)")
print("Señal: ",signal.shape)
print("Espectrograma: ",spectrogram.shape)

# El resultado obtenido es un tensor que contiene el espectograma de cada canal
# Mediante squeeze() recuperamos el espectograma del primer (y único canal)
spectrogram=spectrogram.squeeze().numpy()


plt.figure(figsize=(10,5))
librosa.display.specshow(spectrogram, y_axis="log")

plt.colorbar(format="%+2.0f dB")
plt.show()

ipd.Audio(signal,rate=sr)

"""# Corpus de audio  

UrbanSound8k es una colección de 8732 ejemplos de audio (<=4s) de sonidos urbanos etiquetados (10 clases)

https://urbansounddataset.weebly.com/urbansound8k.html

Corpus:
https://towardsdatascience.com/40-open-source-audio-datasets-for-ml-59dc39d48f06

Utiizaremos una versión reducida de este corpus.

### Definición  

Se crea una subclase de torch.utils.data.Dataset donde se completan los métodos: \__len__ y \__getitem__

Para la creación del corpus se requiere:
- un fichero csv con las anotaciones que informan (entre otros aspectos) la etiqueta correspondiente a cada audio
- una carpeta donde localizar los audios que conformarán el corpus
- un parámetro que recoge las transformaciones que serán aplicadas a los audios previamente al proceso de clasificacion o entrenamiento.
"""

from torch.utils.data import Dataset

import os
import csv

class UrbanSoundDataset(Dataset):


    def __init__(self,annotations_file,audio_dir,transformations=None):
        super().__init__
        self.annotations=self._leer_csv(annotations_file)
        self.audio_dir=audio_dir
        self.transformations=transformations

    def __len__(self):
        return len(self.annotations)

    def __getitem__(self,index):

        signal,sr = self._recupera_signal(index)
        label=self._recupera_label(index)


        if self.transformations:
            signal = self.transformations(signal,sr)


        return signal, label

    def mapa_label_classes(self):
        pares=set([(id_label,label) for [_,id_label,label] in self.annotations])
        mapa={}
        for (a,b) in pares:
            mapa[a]=b

        return mapa

    def label_class(self,index):
        return self.annotations[index][2]

    def get_audio_file(self,index):
        fold="audio"
        name=self.annotations[index][0]
        return os.path.join(self.audio_dir,fold,name)

    def _leer_csv(self,annotations_file):
        with open(annotations_file, 'r', encoding='utf-8') as f:
            lector = csv.reader(f)
            next(lector)  # Para ignorar la cabecera (primera línea del fichero de datos)
            data = [ (file_name,classID,classLabel)
                for file_name,fsID,classID,classLabel in lector]
        return data


    def _recupera_signal(self,index=0):

        audio_file=self.get_audio_file(index)
        signal,sr = torchaudio.load(audio_file)

        return signal,sr

    def _recupera_label(self, index):
        return torch.tensor(int(self.annotations[index][1]))

"""### Corpus: Versión Inicial"""

# Creacion de un corpus
import librosa
sr=44200

ANNOTATIONS_FILE = "./audio/MiniUrbanSound8K/train/MiniUrbanSound8K.csv"
AUDIO_DIR = "./audio/MiniUrbanSound8K/train"


data = UrbanSoundDataset(ANNOTATIONS_FILE, AUDIO_DIR)
print(f"Hay {len(data)} ejemplares en el corpus")

index=np.random.randint(0,len(data))
signal,label=data[index]

print("---- Ejemplar ", index)
print(data.get_audio_file(index))
print("Forma señal:", signal.shape)
print(signal)
print(label)

plt.figure(figsize=(5,2))
numpy_signal=signal.numpy()
librosa.display.waveshow(numpy_signal,sr=sr,color="#f44",alpha=0.8)
plt.title(data.label_class(index))
plt.show()

ipd.Audio(signal,rate=sr)

"""### Corpus: Uniformidad de la señal

https://pytorch.org/audio/stable/transforms.html

Torchaudio ofrece un conjunto de transformaciones de señales de audio por defecto.

Para uniformar todas las señales antes de usarlas, se aplican estas transformaciones en orden:
- `mix_down`: reduce la señal a formato mono (mezcla canales)
- `resample`: unifica la tasa de muestreo (`SAMPLE_RATE`)
- `cut_signal`: recorta la señal si supera `NUM_SAMPLES`
- `right_pad`: rellena con ceros por la derecha si faltan muestras hasta `NUM_SAMPLES`
"""

import librosa

ANNOTATIONS_FILE = "./audio/MiniUrbanSound8K/train/MiniUrbanSound8K.csv"
AUDIO_DIR = "./audio/MiniUrbanSound8K/train"


SAMPLE_RATE = 22050
NUM_SAMPLES = 22050


def resample(signal, sr,target_sr=SAMPLE_RATE):
    if sr != target_sr:
        resampler = torchaudio.transforms.Resample(sr, target_sr)
        signal = resampler(signal)
    return signal

def mix_down(signal):
    if signal.shape[0] > 1:
        signal = torch.mean(signal, dim=0, keepdim=True)
    return signal

def cut_signal(signal,num_samples):
    if signal.shape[1] > num_samples:
        signal = signal[:, :num_samples]
    return signal

def right_pad(signal,num_samples):
    length_signal = signal.shape[1]
    if length_signal < num_samples:
        num_missing_samples = num_samples - length_signal
        last_dim_padding = (0, num_missing_samples)
        signal = torch.nn.functional.pad(signal, last_dim_padding)
    return signal

def transformations(signal,sr,target_sr=SAMPLE_RATE,num_samples=NUM_SAMPLES):

    signal = mix_down(signal)
    signal = resample(signal, sr,target_sr)
    signal = cut_signal(signal,num_samples)
    signal = right_pad(signal,num_samples)
    return signal


data = UrbanSoundDataset(ANNOTATIONS_FILE, AUDIO_DIR,transformations)


index=np.random.randint(0,len(data))
signal,label=data[index]

print("---- Ejemplar ", index)
print(data.get_audio_file(index))
print("Forma señal:", signal.shape)
print(signal)
print(label)

plt.figure(figsize=(5,2))
numpy_signal=signal.numpy()
librosa.display.waveshow(numpy_signal,sr=sr,color="#f44",alpha=0.8)
plt.title(data.label_class(index))
plt.show()

sr=22100
ipd.Audio(signal,rate=SAMPLE_RATE)

"""### Corpus: Uso de Espectrogramas

En esta sección se aplican las mismas transformaciones de uniformidad definidas en el apartado anterior (`mix_down`, `resample`, `cut_signal`, `right_pad`) y, además:
- `Spectrogram(power=2)`: calcula el espectrograma de potencia
- `AmplitudeToDB()`: convierte la escala lineal a decibelios (escala logarítmica perceptual)
"""

import librosa

ANNOTATIONS_FILE = "./audio/MiniUrbanSound8K/train/MiniUrbanSound8K.csv"
AUDIO_DIR = "./audio/MiniUrbanSound8K/train"

SAMPLE_RATE = 22050
NUM_SAMPLES = 22050


def resample(signal, sr,target_sr=SAMPLE_RATE):
    if sr != target_sr:
        resampler = torchaudio.transforms.Resample(sr, target_sr)
        signal = resampler(signal)
    return signal

def mix_down(signal):
    if signal.shape[0] > 1:
        signal = torch.mean(signal, dim=0, keepdim=True)
    return signal


def cut_signal(signal,num_samples):
    if signal.shape[1] > num_samples:
        signal = signal[:, :num_samples]
    return signal

def right_pad(signal,num_samples):
    length_signal = signal.shape[1]
    if length_signal < num_samples:
        num_missing_samples = num_samples - length_signal
        last_dim_padding = (0, num_missing_samples)
        signal = torch.nn.functional.pad(signal, last_dim_padding)
    return signal


def get_spectrogram(signal):
    spectrogram_transform = torchaudio.transforms.Spectrogram(power=2)
    spec_amplitud_to_db_transform = torchaudio.transforms.AmplitudeToDB()

    spect = spectrogram_transform(signal)
    spect=spec_amplitud_to_db_transform(spect)
    return spect

def transformations(signal,sr,target_sr=SAMPLE_RATE,num_samples=NUM_SAMPLES):

    signal = mix_down(signal)
    signal = resample(signal, sr,target_sr)
    signal = cut_signal(signal,num_samples)
    signal = right_pad(signal,num_samples)
    spect = get_spectrogram(signal)
    return spect


data = UrbanSoundDataset(ANNOTATIONS_FILE, AUDIO_DIR,transformations)

index=np.random.randint(0,len(data))
spectrogram,label=data[index]

print("---- Ejemplar ", index)
print(data.get_audio_file(index))
print("Forma espectrograma: ", spectrogram.shape)
print(spectrogram)
print(label)

spectrogram=spectrogram.squeeze().numpy()

plt.figure(figsize=(15,5))
librosa.display.specshow(spectrogram,x_axis="time")
plt.colorbar(format="%+2.f dB")
plt.title(data.label_class(index))
plt.show()

sr=22100
signal,sr=librosa.load(data.get_audio_file(index))
ipd.Audio(signal,rate=SAMPLE_RATE)

"""# Red Neuronal"""

from torch import nn

class NeuralNetwork(nn.Module):

    def __init__(self, num_classes=4):
        super().__init__()

        _canales_audio=1

        self.conv1 = nn.Sequential(
            nn.Conv2d(
                in_channels=_canales_audio,
                out_channels=16,
                kernel_size=3,
                stride=1,
                padding=2
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )

        self.conv2 = nn.Sequential(
            nn.Conv2d(
                in_channels=16,
                out_channels=32,
                kernel_size=3,
                stride=1,
                padding=2
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )
        self.flatten = nn.Flatten(1,-1)

        # El espectrograma de entrada tiene shape [1, 201, 111]:
        #   - 201 bins de frecuencia  (n_fft/2 + 1 = 400/2 + 1)
        #   - 111 frames temporales   (NUM_SAMPLES / hop_length + 1 = 22050/200 + 1)
        #
        # Tras conv1 (kernel=3, padding=2) + MaxPool2d(2):
        #   frecuencia: floor((201 + 4 - 2) / 2) = 101
        #   tiempo:     floor((111 + 4 - 2) / 2) = 56
        #
        # Tras conv2 (kernel=3, padding=2) + MaxPool2d(2):
        #   frecuencia: floor((101 + 4 - 2) / 2) = 51
        #   tiempo:     floor(( 56 + 4 - 2) / 2) = 29
        #
        # => 32 canales × 51 frecuencias × 29 tiempos = 47488 neuronas
        self.linear = nn.Linear(32*51*29, num_classes)

    def forward(self, input):

        # print(input.shape)
        x = self.conv1(input)
        # print(x.shape)
        x = self.conv2(x)
        # print(x.shape)
        x = self.flatten(x)
        logits= self.linear(x)

        # CrossEntropyLoss espera logits, no probabilidades softmax
        return logits

"""## Entrenamiento"""

num_classes = len(data.mapa_label_classes())
modelo = NeuralNetwork(num_classes=num_classes)

BATCH_SIZE = 100

# shuffle=True para no repetir siempre el mismo orden de lotes
dataloader = torch.utils.data.DataLoader(data, batch_size=BATCH_SIZE, shuffle=True)


def train_single_epoch(model, dataloader, loss_fn, optimiser):

    model.train()
    running_loss = 0.0
    for inputs, targets in dataloader:

        # CNN 2D espera [batch, canales, frecuencias, tiempo]
        if inputs.ndim != 4 or inputs.shape[1] != 1:
            raise ValueError(
                f"Shape de entrada no válido para CNN: {inputs.shape}. "
                "Ejecuta antes la sección 'Corpus: Uso de Espectrogramas'."
            )

        print('.', end='')
        logits = model(inputs)
        loss = loss_fn(logits, targets)

        optimiser.zero_grad()
        loss.backward()
        optimiser.step()

        running_loss += loss.item()

    return running_loss / len(dataloader)


def train(model, dataloader, loss_fn, optimiser, epochs):
    print("Inicio del entrenamiento")
    for i in range(epochs):
        print(f"Época {i+1} ", end='')
        print('.', end='')
        loss = train_single_epoch(model, dataloader, loss_fn, optimiser)
        print(f"\nLoss medio: {loss:.4f}")
    print("Fin del entrenamiento")

EPOCHS = 5
LEARNING_RATE = 0.001

loss_fn = nn.CrossEntropyLoss()
optimiser = torch.optim.Adam(modelo.parameters(),
                                 lr=LEARNING_RATE)

train(modelo, dataloader, loss_fn, optimiser, EPOCHS)

"""## Clasificación"""

index=np.random.randint(0,len(data))
spectrogram,label=data[index]

num_classes = len(data.mapa_label_classes())
modelo=NeuralNetwork(num_classes=num_classes)
modelo.eval()
with torch.no_grad():
    logits=modelo(torch.unsqueeze(spectrogram,dim=0))
    pred=torch.softmax(logits, dim=1)

print("---- Ejemplar ", index)
print(data.get_audio_file(index))
print(spectrogram.shape)
print(spectrogram)
print(label)
print("--- Prediccion")
print("Probabilidades:",pred)
v_argmax=torch.argmax(pred)
mapa=data.mapa_label_classes()
mapa_ordenado = dict(sorted(mapa.items(), key=lambda kv: int(kv[0])))
print("Mapa ordenado:", mapa_ordenado)
print("Etiqueta:",mapa_ordenado[str(v_argmax.item())])

# Obtiene el espectograma (incluido en el tensor) y los convierte a un array Numpy para visulizarlo con Matplotlib
spectrogram=spectrogram.squeeze().numpy()

plt.figure(figsize=(15,5))
librosa.display.specshow(spectrogram,x_axis="time")
plt.colorbar(format="%+2.f dB")
plt.title(data.label_class(index))
plt.show()

sr=22100
signal,sr=librosa.load(data.get_audio_file(index))
ipd.Audio(signal,rate=SAMPLE_RATE)

"""# **☞ Ejercicio entregable**: FFT vs espectograma

Partiendo de tres señales de audio $tono_A$, $tono_B$ y $tono_C$ que emiten una frecuencia fija durante toda la señal.
Construye dos nuevas señales $s_1$ y $s_2$ formadas por la concatenación de de las anteriores.
- $s_1=tono_Atono_Btono_C$
- $s_2=tono_Btono_Atono_C$

Muestra la transformada de Fourier y el espectograma de las señales $s_1$ y $s_2$.

¿Qué conclusiones podemos sacar de ambos diagramas?

# **☞ Ejercicio entregable**: Corpus vocales

Crea un corpus de audio con vocales.

- Graba a tres locutores diciendo las cinco vocales una tras otra con una pausa entre las mismas (usando por ejemplo la grabadora del móvil).
- Separa la señal gobal de audio (con effects.split de librosa) en las señales asociadas a cada vocal
- Almacena cada señal en ficheros wav
- Crea un fichero de anotaciones para los audios indicando su clase (vocal a, e, i, o, u)
- Crea una red con arquitectura convolucional para entrenar el corpus.
"""