# -*- coding: utf-8 -*-
"""AINE 2026 - IMG.5 - Arquitecturas Avanzada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkL99lHEQ4metDsEYfNtEDRKYGkR1qxO

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

# IMÁGENES 5: Arquitecturas Avanzadas

Última modificación: 12 de marzo de 2026

Este cuaderno cubre técnicas de visión por computadora más allá de las CNNs básicas. Los notebooks anteriores sentaron las bases (datasets, modelos, entrenamiento, transfer learning); aquí aplicamos esos fundamentos a problemas y arquitecturas del estado del arte.

---
**Contenido**

1. Vision Transformer (ViT) — parches, atención multi-cabeza, carga e inferencia
2. Detección de objetos — Faster R-CNN, bounding boxes, anchor boxes, visualización
3. Detección con YOLO — Ultralytics YOLO11

---
"""

import torch
import torchvision
from torchvision import models
from torchvision.models.detection import fasterrcnn_resnet50_fpn, FasterRCNN_ResNet50_FPN_Weights
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Dispositivo: {device}")
print(f"PyTorch    : {torch.__version__}")
print(f"Torchvision: {torchvision.__version__}")

"""## Vision Transformer (ViT)

Presentado en [_An Image is Worth 16×16 Words_](https://arxiv.org/abs/2010.11929) (Dosovitskiy et al., 2020), el Vision Transformer aplica el mecanismo de atención de los Transformers de NLP directamente a imágenes.

### Idea clave: parches como tokens

En lugar de procesar píxeles individualmente, la imagen se divide en **parches** fijos (p. ej. 16×16 píxeles) que se proyectan linealmente a un vector de _embedding_. Cada parche es el equivalente visual de una palabra en un Transformer de texto.

```
Imagen (224×224)  →  196 parches de 16×16  →  secuencia de 196 tokens
```

A estos tokens se añade:
- Un token especial **[CLS]** cuya representación final se usa para clasificar
- **Embeddings posicionales** aprendidos, para preservar la información espacial (los Transformers no son invariantes al orden)

### Bloque Transformer

Cada bloque aplica:
1. **Multi-Head Self-Attention (MSA)**: cada parche puede "prestar atención" a cualquier otro, capturando dependencias globales desde la primera capa (a diferencia de las CNN, que tienen receptivo campo local)
2. **Feed-Forward Network (FFN)**: dos capas lineales con GELU
3. **Layer Norm** antes de cada operación + **conexiones residuales**

### Comparación CNN vs ViT

| Aspecto | CNN | ViT |
|---------|-----|-----|
| Inductive bias | Localidad, equivarianza traslacional | Ninguno (más flexible, necesita más datos) |
| Receptivo campo | Crece capa a capa | Global desde la primera capa |
| Datos necesarios | Menos | Más (o preentrenamiento en ImageNet-21k) |
| Escalabilidad | Buena | Excelente (ViT-L, ViT-H) |

En `torchvision.models` están disponibles `vit_b_16`, `vit_b_32`, `vit_l_16`, `vit_l_32` y `vit_h_14`.
"""

### Visualización del proceso de parcheo

from torchvision.models import vit_b_16, ViT_B_16_Weights

# ── Cargar ViT_B_16 con pesos preentrenados en ImageNet ────────────────────
pesos_vit = ViT_B_16_Weights.DEFAULT
modelo_vit = vit_b_16(weights=pesos_vit).to(device)
modelo_vit.eval()

# Parámetros
params_total = sum(p.numel() for p in modelo_vit.parameters())
params_train = sum(p.numel() for p in modelo_vit.parameters() if p.requires_grad)
print(f"Parámetros totales     : {params_total:,}")
print(f"Parámetros entrenables : {params_train:,}")
print(f"\nArquitectura:")
print(modelo_vit)

### Visualización de la división en parches (16×16)

img_pil = Image.open("./img/torreDelOro.jpg").convert("RGB")
img_pil_224 = img_pil.resize((224, 224))
img_np = np.array(img_pil_224)

patch_size = 16
n_patches   = 224 // patch_size   # 14 parches por lado

fig, axes = plt.subplots(1, 2, figsize=(12, 6))

# Imagen original con rejilla de parches
axes[0].imshow(img_np)
for i in range(n_patches + 1):
    axes[0].axhline(i * patch_size, color="yellow", linewidth=0.5)
    axes[0].axvline(i * patch_size, color="yellow", linewidth=0.5)
axes[0].set_title(f"Imagen 224×224 dividida en {n_patches}×{n_patches} = {n_patches**2} parches de {patch_size}×{patch_size}", fontsize=9)
axes[0].axis("off")

# Mosaico de algunos parches
n_mostrar = 8
parches = []
for i in range(n_mostrar):
    for j in range(n_mostrar):
        y0, x0 = i * patch_size, j * patch_size
        parches.append(img_np[y0:y0+patch_size, x0:x0+patch_size])

mosaico = np.concatenate([np.concatenate(parches[row*n_mostrar:(row+1)*n_mostrar], axis=1)
                           for row in range(n_mostrar)], axis=0)
axes[1].imshow(mosaico)
axes[1].set_title(f"Primeros {n_mostrar}×{n_mostrar} parches como secuencia de tokens", fontsize=9)
axes[1].axis("off")

plt.suptitle("ViT: la imagen como secuencia de parches visuales", fontsize=11)
plt.tight_layout()
plt.show()

### Inferencia con ViT preentrenado en ImageNet

transform_vit = pesos_vit.transforms()   # preprocesado estándar del modelo

img_pil = Image.open("./img/torreDelOro.jpg").convert("RGB")
x_vit = transform_vit(img_pil).unsqueeze(0).to(device)

with torch.no_grad():
    logits_vit = modelo_vit(x_vit)

probs = torch.softmax(logits_vit, dim=1)
top5  = probs.topk(5)

# Etiquetas de ImageNet incluidas en los metadatos de los pesos
categorias = pesos_vit.meta["categories"]
print("Top-5 predicciones (ViT-B/16 en ImageNet):")
for prob, idx in zip(top5.values[0], top5.indices[0]):
    print(f"  {categorias[idx]:40s}  {prob.item()*100:.2f}%")

"""## Detección de objetos — Faster R-CNN

La **detección de objetos** no solo clasifica la imagen, sino que localiza cada objeto mediante una **caja delimitadora** (_bounding box_). La salida del modelo es un conjunto de tuplas (clase, confianza, caja).

### Arquitectura Faster R-CNN

Faster R-CNN (Ren et al., 2015) consta de tres bloques principales:

```
Imagen  →  Backbone  →  Feature Pyramid Network (FPN)  →  RPN  →  RoI Align  →  Detection Head
```

| Bloque | Función |
|--------|---------|
| **Backbone** (ResNet-50) | Extrae mapas de características a distintas escalas |
| **FPN** (Feature Pyramid Network) | Combina características de alta y baja resolución para detectar objetos de distintos tamaños |
| **RPN** (Region Proposal Network) | Propone ~2000 regiones candidatas que pueden contener un objeto (_anchors_) |
| **RoI Align** | Extrae un vector fijo por cada región propuesta |
| **Detection Head** | Clasifica cada región y refina las coordenadas de la caja |

### Salida

Para cada objeto detectado el modelo devuelve:
- `boxes`: tensor `[N, 4]` con coordenadas `[x_min, y_min, x_max, y_max]`
- `labels`: tensor `[N]` con el índice de clase en COCO (91 clases)
- `scores`: tensor `[N]` con la confianza de cada detección (0-1)

En `torchvision.models.detection` están disponibles `fasterrcnn_resnet50_fpn`, `fasterrcnn_mobilenet_v3_large_fpn` y `fasterrcnn_resnet50_fpn_v2`.
"""

### Cargar Faster R-CNN preentrenado en COCO

pesos_rcnn   = FasterRCNN_ResNet50_FPN_Weights.DEFAULT
modelo_rcnn  = fasterrcnn_resnet50_fpn(weights=pesos_rcnn).to(device)
modelo_rcnn.eval()

categorias_coco = pesos_rcnn.meta["categories"]
print(f"Clases COCO ({len(categorias_coco)}):")
print("  " + ", ".join(categorias_coco[:20]) + " ...")

params_rcnn = sum(p.numel() for p in modelo_rcnn.parameters())
print(f"\nParámetros totales: {params_rcnn:,}")

### Inferencia y visualización de detecciones

import requests
from pathlib import Path
from io import BytesIO

def detectar_y_visualizar(ruta_imagen, modelo, categorias, umbral=0.5, device=device):
    """Ejecuta Faster R-CNN sobre una imagen y dibuja las detecciones."""
    img_pil = Image.open(ruta_imagen).convert("RGB")
    transform_det = pesos_rcnn.transforms()
    x = transform_det(img_pil).unsqueeze(0).to(device)

    with torch.no_grad():
        predicciones = modelo(x)[0]

    mascara      = predicciones["scores"] >= umbral
    cajas        = predicciones["boxes"][mascara].cpu()
    etiquetas    = predicciones["labels"][mascara].cpu()
    puntuaciones = predicciones["scores"][mascara].cpu()

    fig, ax = plt.subplots(1, 1, figsize=(10, 8))
    ax.imshow(img_pil)

    colores = plt.cm.tab20.colors
    for caja, lbl, score in zip(cajas, etiquetas, puntuaciones):
        x0, y0, x1, y1 = caja.tolist()
        color = colores[lbl.item() % len(colores)]
        rect = patches.Rectangle((x0, y0), x1 - x0, y1 - y0,
                                  linewidth=2, edgecolor=color, facecolor="none")
        ax.add_patch(rect)
        ax.text(x0, y0 - 4, f"{categorias[lbl.item()]} {score:.2f}",
                fontsize=8, color="white",
                bbox=dict(facecolor=color, alpha=0.7, pad=2, edgecolor="none"))

    ax.set_title(f"Faster R-CNN — {mascara.sum().item()} detecciones (umbral={umbral})", fontsize=11)
    ax.axis("off")
    plt.tight_layout()
    plt.show()
    print(f"Detecciones: {mascara.sum().item()}")
    for lbl, score in zip(etiquetas, puntuaciones):
        print(f"  {categorias[lbl.item()]:20s}  score={score:.3f}")


# ── Imagen de muestra con objetos COCO (personas, bicis, coches) ───────────
RUTA_DEMO = "./img/coco_sample.jpg"
if not Path(RUTA_DEMO).exists():
    URL = "http://images.cocodataset.org/val2017/000000000632.jpg"
    print("Descargando imagen de muestra desde COCO...")
    resp = requests.get(URL, timeout=15)
    resp.raise_for_status()
    Image.open(BytesIO(resp.content)).convert("RGB").save(RUTA_DEMO)
    print(f"Guardada en {RUTA_DEMO}")

detectar_y_visualizar(RUTA_DEMO, modelo_rcnn, categorias_coco, umbral=0.5)

"""### Anchor boxes y propuestas del RPN

Antes de que el detection head clasifique y refine las cajas, el pipeline pasa por dos etapas de filtrado:

```
Anchor boxes (brutas)  →  RPN scoring + NMS  →  Proposals  →  RoI Align  →  Detecciones finales
```

**Anchor boxes** son cajas predefinidas que se colocan densa y sistemáticamente sobre cada posición de cada mapa de características del FPN. Para cada posición se generan cajas con distintos tamaños y proporciones (_aspect ratios_). En `fasterrcnn_resnet50_fpn` el `AnchorGenerator` usa:

- **5 escalas FPN** (P2–P6): tamaños de anchor `(32², 64², 128², 256², 512²)` píxeles
- **3 aspect ratios** por escala: `0.5, 1.0, 2.0`
- Resultado: **~200 000 anchors** para una imagen de 800×600

El **RPN** puntúa cada anchor (¿contiene objeto?) y aplica NMS con `rpn_nms_thresh=0.7`, reduciendo las ~200k anchors a ~1000–2000 **proposals** que se pasan al RoI Align.

"""

### Visualización: anchors brutos vs. proposals del RPN

from torchvision.models.detection.image_list import ImageList

img_pil_demo = Image.open(RUTA_DEMO).convert("RGB")
transform_det = pesos_rcnn.transforms()
x_det = transform_det(img_pil_demo).unsqueeze(0).to(device)

# ── 1. Anchors brutos del AnchorGenerator ─────────────────────────────────
with torch.no_grad():
    features = modelo_rcnn.backbone(x_det)                     # FPN features (dict P2–P6)

img_list = ImageList(x_det, [(x_det.shape[-2], x_det.shape[-1])])
all_anchors = modelo_rcnn.rpn.anchor_generator(img_list, list(features.values()))
anchors_img = all_anchors[0].cpu()   # (N_total, 4) — todas las anchors de la imagen

print(f"Total anchors generados : {len(anchors_img):,}")
print(f"  → escalas FPN × aspect ratios × posiciones espaciales")

# Escala imagen original → escala de entrada del modelo
w_orig, h_orig = img_pil_demo.size
h_model, w_model = x_det.shape[2], x_det.shape[3]
sx, sy = w_orig / w_model, h_orig / h_model

# ── 2. Proposals del RPN (tras scoring + NMS) ─────────────────────────────
proposals_capturadas = []

def _hook_rpn(module, input, output):
    # output = (proposals_list, losses_dict)
    proposals_capturadas.append(output[0][0].detach().cpu())

handle = modelo_rcnn.rpn.register_forward_hook(_hook_rpn)
with torch.no_grad():
    _ = modelo_rcnn(x_det)
handle.remove()

proposals = proposals_capturadas[0]   # (M, 4) en coordenadas del modelo
print(f"Proposals tras RPN NMS  : {len(proposals):,}")

# ── 3. Visualización ───────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# — Izquierda: muestra aleatoria de anchors brutos (escalados a la imagen original)
N_MUESTRA = 150
idx_muestra = np.random.choice(len(anchors_img), N_MUESTRA, replace=False)
axes[0].imshow(img_pil_demo)
for idx in idx_muestra:
    x0, y0, x1, y1 = anchors_img[idx].tolist()
    x0, x1 = x0 * sx, x1 * sx
    y0, y1 = y0 * sy, y1 * sy
    rect = patches.Rectangle((x0, y0), x1 - x0, y1 - y0,
                              linewidth=0.5, edgecolor="yellow", facecolor="none", alpha=0.5)
    axes[0].add_patch(rect)
axes[0].set_title(f"Anchors brutos (muestra {N_MUESTRA} de {len(anchors_img):,})", fontsize=10)
axes[0].axis("off")

# — Derecha: proposals del RPN (escalados a la imagen original)
N_PROP = min(200, len(proposals))
axes[1].imshow(img_pil_demo)
for i in range(N_PROP):
    x0, y0, x1, y1 = proposals[i].tolist()
    x0, x1 = x0 * sx, x1 * sx
    y0, y1 = y0 * sy, y1 * sy
    rect = patches.Rectangle((x0, y0), x1 - x0, y1 - y0,
                              linewidth=0.7, edgecolor="cyan", facecolor="none", alpha=0.4)
    axes[1].add_patch(rect)
axes[1].set_title(f"Proposals RPN tras NMS (primeras {N_PROP} de {len(proposals):,})", fontsize=10)
axes[1].axis("off")

plt.suptitle("Antes vs. después del RPN: de ~200k anchors a ~1000 proposals", fontsize=11)
plt.tight_layout()
plt.show()

"""### YOLO con Ultralytics

**YOLO** (_You Only Look Once_) es la familia de detectores de **una sola etapa** más popular. A diferencia de Faster R-CNN (dos etapas: RPN + detection head), YOLO predice cajas y clases en un único paso por la red, lo que lo hace considerablemente más rápido.

La librería **Ultralytics** proporciona YOLOv8 / YOLO11 con una API unificada:

```python
from ultralytics import YOLO
modelo = YOLO("yolo11n.pt")   # n=nano, s=small, m=medium, l=large, x=xlarge
resultados = modelo("imagen.jpg")
```

El modelo se descarga automáticamente la primera vez (~6 MB para el nano). La salida incluye `boxes`, `masks`, `probs` y `keypoints` según la tarea configurada.

| Variante | Parámetros | Velocidad | mAP COCO |
|----------|-----------|-----------|----------|
| `yolo11n` | 2.6 M | ⚡⚡⚡ | 39.5 |
| `yolo11s` | 9.4 M | ⚡⚡ | 47.0 |
| `yolo11m` | 20.1 M | ⚡ | 51.5 |
| `yolo11l` | 25.3 M | — | 53.4 |

> **Nota**: Ultralytics no es parte de torchvision; se instala por separado (`pip install ultralytics`).

"""

### Detección con YOLO11 (Ultralytics)

from ultralytics import YOLO

# ── Cargar modelo YOLO11 nano preentrenado en COCO ─────────────────────────
# Se descarga automáticamente (~6 MB) si no está en caché
modelo_yolo = YOLO("yolo11n.pt")

# ── Inferencia sobre la misma imagen de muestra ───────────────────────────
resultados = modelo_yolo(RUTA_DEMO, conf=0.4, verbose=False)
res = resultados[0]

print(f"Detecciones: {len(res.boxes)}")
for box in res.boxes:
    cls_id = int(box.cls.item())
    nombre = modelo_yolo.names[cls_id]
    conf   = box.conf.item()
    print(f"  {nombre:20s}  conf={conf:.3f}")

# ── Visualización con la API de Ultralytics ────────────────────────────────
img_yolo = res.plot()          # numpy array BGR con cajas dibujadas
img_yolo_rgb = img_yolo[..., ::-1]   # BGR → RGB para matplotlib

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

axes[0].imshow(Image.open(RUTA_DEMO))
axes[0].set_title("Imagen original", fontsize=10)
axes[0].axis("off")

axes[1].imshow(img_yolo_rgb)
axes[1].set_title(f"YOLO11n — {len(res.boxes)} detecciones (conf ≥ 0.4)", fontsize=10)
axes[1].axis("off")

plt.suptitle("Detección con YOLO11 (Ultralytics) vs. imagen original", fontsize=11)
plt.tight_layout()
plt.show()