# -*- coding: utf-8 -*-
"""AINE 2026 - IMG.3 - Modelos (ESCRIBE AQUI TU UVUS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgmnTV1Wk9tL_fihTTKNDFpbjJJ3V8d0

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

**Escriba aquí su nombre y apellidos:**

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:
* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable")

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**

# IMÁGENES 3: MODELOS
Última modificación: 9 de marzo de 2026

---
**Contenido**

1. Red neuronal — definición, ejecución, modos `train()`/`eval()`, dispositivos
2. Parámetros — iteradores, conteo, `state_dict`
3. Almacenamiento y recuperación — `torch.save` / `torch.load`
4. Capas (`torch.nn`) — `Linear`, `Sequential`, `ReLU`, `Flatten`, `Softmax`, `Dropout`, `Conv2d`, `MaxPool2d`, `BatchNorm2d`
5. Modelos preentrenados — familias, inspección de capas, modificar cabeza de clasificación
6. ☞ **Ejercicio**: CNN con submódulos y forward dual
7. ☞ **Ejercicio**: Visualización de convoluciones con modelo preentrenado

---
"""

import torch
import torchvision

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Dispositivo: {device}")

"""## Red neuronal

https://pytorch.org/docs/stable/nn.html

- El espacio de nombres torch.nn suministra los componentes básicos para la construcción de una red neuronal:
- La red se organiza mediante componentes (módulos) de distinta naturaleza:
    - Algunas componentes son los que realizan las transformaciones más relevantes:
        - lineales (Liner), convoluciones (Conv2D), etc
    - Otros componentes son contenedores que facilitan la organización de la red:
        - Module, Sequential
    - Un tercer grupo se encargan de realizar ajustes o normalización de los cálculos:
        - RELU, Softmax, etc,.

### Definición, Creación y Ejecución

Las redes neuronales se definen como subclases de `torch.nn.Module` con dos métodos obligatorios:

- `__init__`: declara los componentes y recibe los hiperparámetros de la red.
- `forward`: define el flujo de información de la entrada a la salida.

La instancia del modelo se invoca como una función — PyTorch llama a `forward` internamente. No usar `modelo.forward(x)` directamente.

```python
class RedNeuronal(torch.nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x
```
"""

class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_entradas, num_salidas, num_ocultas=16):
        super().__init__()
        self.secuencia = torch.nn.Sequential(
            torch.nn.Linear(num_entradas, num_ocultas),
            torch.nn.ReLU(),
            torch.nn.Dropout(p=0.3),
            torch.nn.Linear(num_ocultas, num_salidas),
        )

    def forward(self, x):
        return self.secuencia(x)


# Parámetros globales — reutilizados en el resto de la sección
num_entradas, num_salidas = 4, 3
model = NeuralNetwork(num_entradas, num_salidas)

print("Arquitectura:")
print(model)

# Ejecución: invocar el modelo como función (llama a forward internamente)
num_ejemplares = 2
X = torch.rand(num_ejemplares, num_entradas)
logits = model(X)
print(f"\nEntrada:  {X.shape}")
print(f"Salida:   {logits.shape}")
print(logits)

"""### Modos de ejecución: `train()` y `eval()`

Un modelo en PyTorch puede estar en dos modos:

| Modo | Activación | Efecto |
|---|---|---|
| `model.train()` | entrenamiento | Dropout activo, BatchNorm usa estadísticas del batch |
| `model.eval()` | inferencia | Dropout desactivado, BatchNorm usa estadísticas globales |

Por defecto, al crear un modelo está en modo `train()`. **Siempre** hay que llamar a `model.eval()` antes de usarlo para predicción, o los resultados serán incorrectos.

Además, durante la inferencia no es necesario calcular gradientes. Envolver el código con `torch.no_grad()` ahorra memoria y acelera la ejecución:

```python
model.eval()
with torch.no_grad():
    pred = model(X)
```
"""

# NeuralNetwork incluye Dropout
model = NeuralNetwork(num_entradas, num_salidas)
X = torch.rand(2, num_entradas)

# --- Modo train (por defecto) ---
model.train()
print(f"Modo training: {model.training}")   # True
out_train = model(X)
print("Salida en train (Dropout activo — varía en cada llamada):")
print(out_train)

# --- Modo eval ---
model.eval()
print(f"\nModo training: {model.training}")  # False

# torch.no_grad() desactiva el cálculo de gradientes (más rápido, menos memoria)
with torch.no_grad():
    out_eval = model(X)
print("Salida en eval (Dropout desactivado — estable):")
print(out_eval)

print(f"\n¿Son iguales train y eval? {torch.allclose(out_train, out_eval)}")

"""### Dispositivos

El entrenamiento de redes neuronales involucra una gran cantidad de cálculos matriciales. PyTorch permite ejecutarlos en la CPU o en una GPU (CUDA), eligiendo el dispositivo más potente disponible.

> **Regla fundamental**: modelo y tensores deben residir en el **mismo dispositivo**.

- `model.to(device)` — mueve el modelo.
- `tensor.to(device)` o `torch.rand(..., device=device)` — crea/mueve tensores.
"""

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Dispositivo empleado: {device}")

# Mover el modelo al dispositivo
model = NeuralNetwork(num_entradas, num_salidas).to(device)

# Los tensores de entrada deben estar en el mismo dispositivo
X = torch.rand(1, num_entradas, device=device)

logits = model(X)
print(f"Salida en {device}: {logits}")

"""## Parámetros

Algunas capas transforman la entrada mediante valores ajustables llamados **parámetros**. Por ejemplo, en `nn.Linear` la transformación es $y = xW + b$, donde $W$ (pesos) y $b$ (sesgo) son parámetros.

Al crear el modelo se inicializan aleatoriamente. Durante el entrenamiento se actualizan iterativamente para minimizar el error.

Los parámetros son de tipo [`Parameter`](https://pytorch.org/docs/stable/generated/torch.nn.parameter.Parameter.html), una subclase de `Tensor` con `requires_grad=True` por defecto.

### Iteradores y conteo

`Module` suministra dos iteradores sobre sus parámetros:
- **`parameters()`** — recorre los tensores `Parameter`.
- **`named_parameters()`** — devuelve tuplas `(nombre, Parameter)`.

El número de parámetros es un indicador clave de la complejidad del modelo:
```python
total       = sum(p.numel() for p in model.parameters())
entrenables = sum(p.numel() for p in model.parameters() if p.requires_grad)
```
Los parámetros con `requires_grad=False` (congelados) no se actualizan durante el entrenamiento — útil en Transfer Learning.
"""

model = NeuralNetwork(num_entradas, num_salidas)
model.train()  # modo por defecto tras crear el modelo

# Recorrido con nombre y valor
print("Parámetros (nombre — forma — numel):")
for name, param in model.named_parameters():
    print(f"  {name:<30} {str(list(param.shape)):<15} → {param.numel():>4,}")

# Conteo total y entrenable
total       = sum(p.numel() for p in model.parameters())
entrenables = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\nTotal: {total:,}  |  Entrenables: {entrenables:,}")

# Acceso directo a un parámetro
print(f"\nBias de secuencia.0: {model.get_parameter('secuencia.0.bias')}")

"""### Mapa de estado

El mapa **state_dict()**  es un diccionario que relaciona cada capa con sus parámetros.

Este mapa permite consultar los parámetros de un modelo, pero será el medio para almacenar de forma permanente los parámetros de un modelo.

NOTA: El atributo requires_grad de los parámetros en el mapa de estado se almacena con valor False.


"""

model = NeuralNetwork(num_entradas, num_salidas)

print(model.state_dict())

nombre = "secuencia.0.weight"
parametro = model.state_dict()[nombre]

print("Parámetro", nombre)
print(parametro)
print(parametro.requires_grad)
print(parametro.grad)
print(parametro.grad_fn)
print(parametro.is_leaf)

"""## Almacenamiento y recuperación

El método recomendado es serializar el **`state_dict`** (mapa de parámetros), no el modelo completo — es más portable y no depende de la definición exacta de la clase en disco.

| Operación | Código |
|---|---|
| Guardar | `torch.save(model.state_dict(), "ruta.pth")` |
| Recuperar | `model.load_state_dict(torch.load("ruta.pth"))` |

> **Importante**: el modelo destino debe tener **exactamente la misma arquitectura** que el guardado. Tras cargar, llamar a `model.eval()` antes de hacer inferencia.
"""

import os
ruta = "./modelos/model.pth"
os.makedirs("./modelos", exist_ok=True)

# --- Guardar ---
modelo = NeuralNetwork(num_entradas, num_salidas)
torch.save(modelo.state_dict(), ruta)
print("Guardado:", modelo.state_dict())

# --- Recuperar ---
# El modelo destino debe tener exactamente la misma arquitectura
modelo_cargado = NeuralNetwork(num_entradas, num_salidas)
modelo_cargado.load_state_dict(torch.load(ruta))
modelo_cargado.eval()

X = torch.rand(2, num_entradas)
with torch.no_grad():
    pred = modelo_cargado(X)
print(f"\nPredicción con modelo recuperado:\n{pred}")

# Verificar que los parámetros son idénticos tras el ciclo guardar/cargar
igual = all(torch.equal(p1, p2) for p1, p2 in zip(modelo.parameters(), modelo_cargado.parameters()))
print(f"¿Parámetros idénticos tras guardar/cargar? {igual}")

"""## Capas (Layers)

Pytorch suministra por defecto un conjunto notable de componentes como base para la definición de las redes neuronales.

Los componentes transforman un tensor de entrada en otro tensor de salida atendiendo a distintas estrategias.

Los componentes están preparados para aceptar una o varias entradas:
- entrada única: tensor
- entrada múltiple: tensor de tensores

### Module

https://pytorch.org/docs/stable/generated/torch.nn.Module.html

El módulo es la clase a partir de la cual se definen los componentes de una red neuronal.
De hecho, las propias redes neuronales son subclases de Module.

En la definición del módulo se debe determinar los métodos \__init\__ y _forward_

- El método \__init\__ tiene como comentido:
    - determinar los componentes que integran la red.
    - recibir los parámetros necesarios para construir la red
- El método _forward_ es donde se especifica el orden de ejecución de los componentes

La clase Module ofrece métodos para el acceso y consulta de todos sus subcomponentes
"""

# nn.Module

class Red(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(2,3)
        self.linear2 = torch.nn.Linear(2,3)


    def forward(self, x):
        return self.linear(x)

m=Red()

print(m)
print("--------")
for c in m.children():
    print(c)

print("--------")

for n,p in m.named_parameters():
    print(n)
    print(p)
print("--------")
print(m.get_parameter('linear.weight'))

"""### Inspección de la estructura de capas

Para acceder a capas concretas por nombre (por ejemplo, para registrar hooks o sustituir capas en Transfer Learning) es necesario conocer su nombre exacto en la jerarquía del modelo. `Module` ofrece dos iteradores para esto:

- **`named_children()`** — devuelve tuplas `(nombre, módulo)` del **primer nivel** de la jerarquía.
- **`named_modules()`** — recorre **recursivamente** toda la jerarquía, devolviendo el nombre completo de cada capa (`"secuencia.0"`, `"secuencia.2"`, etc.).

```python
# Acceso directo a una capa por nombre
modelo.conv1                  # atributo si es de primer nivel
modelo.layer3[0].conv1        # índice + atributo para niveles más profundos
```

> La forma práctica de descubrir estos nombres es ejecutar `named_modules()` sobre el modelo e inspeccionar la lista antes de usarlos.

"""

model = NeuralNetwork(num_entradas, num_salidas)

# --- print(model): resumen visual de la arquitectura ---
# Útil para una visión rápida de los bloques de primer nivel y sus tipos.
# No muestra los nombres completos de capas anidadas.
print("── print(model) ──────────────────────────────────────")
print(model)

# --- Capas de primer nivel (named_children) ---
# Muestra solo el primer nivel de la jerarquía con sus nombres.
print("\n── named_children() ──────────────────────────────────")
for name, module in model.named_children():
    print(f"  {name!r:<20} → {module.__class__.__name__}")

# --- Todas las capas, recursivamente (named_modules) ---
# Devuelve los nombres completos de TODAS las capas anidadas.
# Es la forma más precisa de descubrir los nombres exactos para
# hooks, transfer learning, o acceso directo a capas concretas.
print("\n── named_modules() ───────────────────────────────────")
for name, module in model.named_modules():
    print(f"  {name!r:<35} → {module.__class__.__name__}")

"""### Linear

https://pytorch.org/docs/stable/generated/torch.nn.Linear.html


Los parámetros de un componente nn.Linear pueden ser directamente consultados mediantes los atributos: _weight_ y _bias_

<img  width="400" height="200" src="./img/linear.png">

"""

## nn.Linear
num_entradas=3
num_salidas=2

# Entrada única
# inputs = torch.rand(num_entradas)

# Entrada múltiple
num_ejemplares=2
inputs = torch.rand(num_ejemplares,num_entradas)

# linear= torch.nn.Linear(in_features=num_entradas, out_features=num_salidas)
linear= torch.nn.Linear(in_features=num_entradas, out_features=num_salidas)

outputs = linear(inputs)

print("***********************")
print("---  Entrada")
print(inputs.size())
print(inputs)

print("***********************")
print("---  Salida")
print(outputs.size())
print(outputs)

print("-------- PARAMETROS  ------")
iter_par=linear.named_parameters()
for n,m in iter_par:
    print(n,m)

print("-------- Acceso  ------")
# La capa lineal tiene atributos específicos para acceder sus parámetros
print(linear.weight)
print(linear.weight[0][2].item())
print(linear.bias)

print("-------- Acceso/Module  ------")
# La capa lineal es una subclase de Module, por tanto podemos emplear get_parameter()
print(linear.get_parameter('weight'))


print("-------- Modificación  ------")

p=linear.weight
print(p[0][2].item())
# AVISO: a view of a leaf Variable that requires grad is being used in an in-place operation
# p[0][2]=4.4
p.requires_grad=False
p[0][2]=4.4
print(p[0][2].item())

"""### Sequential

https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html

Es una subclase de Module que define un contenedor de componentes interconectados secuencialmente (la entrada de un componente es la salida del anterior).

Este contenedor permite organizar (y nombrar) en bloques los componentes de la red.

Podemos acceder por su posición a cada uno de sus componentes.

Incluye el método Sequential.append() que permite añadir al final (de forma dinámica) nuevos componentes.

"""

# nn.Sequential
num_entradas=3
num_salidas=3
num_ocultas=3

# Entrada única
# inputs = torch.rand(num_ejemplares,num_entradas)

# Entrada múltiple
num_ejemplares=2
inputs = torch.rand(num_ejemplares,num_entradas)

seq = torch.nn.Sequential(
    torch.nn.Linear(num_entradas,num_ocultas),
    torch.nn.Linear(num_ocultas, num_salidas)
)


outputs = seq(inputs)

print("***********************")
print("---  Entrada")
print(inputs.size())
print(inputs)

print("***********************")
print("---  Salida")
print(outputs.size())
print(outputs)

print("-------- PARAMETROS  ------")
iter_par=seq.named_parameters()
for n,m in iter_par:
    print(n,m)

print("---- ACCESO a subcomponentes")
idx=0
print(seq[idx])
print(seq[idx].bias)

"""### RELU

Las capas lineales son incapaces de clasificar modelos no lineales. La solución es añadir una capa que modifique la salida de las neuronas mediante una función de activación.  


PyTorch ofrece varias alternativas para definir funciones de activación no lineales.

https://pytorch.org/docs/stable/nn.html#non-linear-activations

Una de las más empleadas es RELU (REctified Linear Unit)
- La salida consiste en poner a cero los valores no positivos
- No requiere de parámetros

<img width="250" height="200" src="./img/relu.png">

"""

# nn.RELU
num_entradas=7

# Genera una entrada aleatoria
# Dado que la entrada aleatoria sólo genera números reales entre 0 y 1.
# se suman valores en un rango con valores negativos, para que el resultado incluya negativos

# Entrada simple
# inputs = torch.rand(num_entradas)+torch.randint(-1,1,(num_entradas,))

# Entrada múltiple
num_ejemplares=2
inputs = torch.rand(num_ejemplares,num_entradas)+torch.randint(-1,1,(num_ejemplares,num_entradas))


relu=torch.nn.ReLU()
outputs =relu(inputs)

print("Entrada:", inputs.size())
print(inputs)
print("-------------")
print("Salida:",outputs.size())
print(outputs)

"""### Flatten

https://pytorch.org/docs/stable/generated/torch.nn.Flatten.html

Dada una lista de entradas representadas multidimensionalmente, aplana en una dimensión los valores de cada ejemplar.

Esta capa no requiere de parámetros.

Esta capa es ampliamente utilizada en el tratamiento de imágenes.
- La información bidemensional de la imagen es reducida a una dimensión para que sirva de entrada a la red.  


<img width="200" height="200" src="./img/flatten.png">


"""

# nn.Flatten
n=m=2

# Entrada simple
inputs = torch.rand(n,m)

# Entrada múltiple
# num_ejemplares=2
# inputs = torch.rand(num_ejemplares,n,m)

flatten = torch.nn.Flatten()
outputs = flatten(inputs)

print("Entrada:", inputs.size())
print(inputs)
print("-------------")
print("Salida:",outputs.size())
print(outputs)

"""### Softmax

https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html

Transforma los valores de entrada (número reales) en probabilidades [0,1]

Es un componente ubicado habitualmente al final de la red con idea de interpretar probablilísticamente el valor de salida (logits) de las neuronas de la red.

NOTA: En las nuevas versiones se exige la inclusión del argumento dim en Softmax() que indica la dimensión sobre la que se debe aplicar la interpretación.

OJO: Este componenete puede ser innecesario al entrenar las redes con criterio torch.nn.CrossEntropyLoss debido a que ya se efectúa esa interpretación de los resultados.

"""

## nn.Softmax
num_entradas=7

# Genera una entrada aleatoria que incluya valores fuera de [0,1]
num_ejemplares=1
factor=2.5
inputs = factor*torch.rand(num_ejemplares,num_entradas)

softmax = torch.nn.Softmax(dim=1)
outputs =softmax(inputs)

print("Entrada:", inputs.size())
print(inputs)
print("-------------")
print("Salida:",outputs.size())
print(outputs)

print(">> Salida más probable")
print(">> Valor:",outputs.max().item())
print(">> Posición:",outputs.argmax().item())

"""### Dropout

La dilución (_dropout_) consiste en _apagar_ (descartar) aleatoriamente un conjunto de neuronas de una red.
Habitualmente el mecanismo consiste en poner a cero el valor de salida de una neurona

La dilución es un mecanismo empleado para evitar el sobreajuste (_overfitting_) durante el entrenamiento.

La intución detrás de este proceso es la siguiente: al descartar o amortiguar la salida de ciertas neuronas de forma arbitraria obliga al resto de las neuronas a esforzarse para compensar el aprendizaje de las descartadas.

Pytorch ofrece varias mecanismos de dilución:
https://pytorch.org/docs/stable/nn.html#dropout-layers

La capa Dropout es una de las más empleadas. Su efecto consiste en:
- poner a cero las neuronas de una capa de forma aleatoria con una probabilidad $p$.
- compensar la pérdida de información de las neuronas apagadas de forma que el valor de las neuronas encendidas se ajustan proporcionalmente en un factor $\frac{1}{1-p}$


"""

## nn.Dropout
num_entradas=7

# Entrada simple
inputs = torch.rand(num_entradas)

# Entrada múltiple
# num_ejemplares=1
# inputs = torch.rand(num_ejemplares,num_entradas)

p=0.5
dropout = torch.nn.Dropout(p)
outputs =dropout(inputs)

print("Entrada:", inputs.size())
print(inputs)
print("-------------")
print("Salida:",outputs.size())
print(outputs)

# Test para comprobar la compensacion 1/1-p de las neuronas encendidas
# Ver el cambio en el valor de las neuronas encendidas
print("-------------")
print("Comprobación reajuste de valores de salida")
for i in range(len(outputs)):
    if outputs[i]!=0.0:
        inputs_aux=inputs[i]*(1/(1-p))
        print(f"Posicion {i} Inicial {inputs[i].item():0.4f} Ajuste {inputs_aux.item():0.4f}")

"""### Conv2D


Una convolución es un operador matemático que transforma dos funciones $f$ y $g$ en una tercera función que en cierto sentido representa la magnitud en la que se superponen $f$ y una versión trasladada e invertida de $g$.

Esta idea es el soporte que conduce a la noción de convolución en las redes neuronales:  a las entradas de las neuronas $f$ se les aplica un filtro $g$ para obtener una salida que pretende potenciar el efecto que tiene el filtro (kernel) en la entrada.

El filtro se define de tal modo que sólo se aplica en una parte de la entrada. Es necesario _desplazar_ el filtro sobre la entrada para ver su efecto global.

De este modo, tenemos que frente a un  componente lineal que conecta todas las entradas con todas las neuronas, los componentes convolucionales limitan el número de conexiones.

A la hora de limitar las conexiones se aplica un criterio de cercanía o localidad: cada neurona sólo tiene en cuenta las entradas que están _próximas_. Es decir, el filtro se aplica tan sólo a las entradas _próximas_. El efecto total vendrá dado por el desplazamiento del filtro.

Este concepto de proximidad es fácil de identificar en el caso de datos que pueden tener una interpretación espacial (imágenes) o en los que el contexto de los datos es relevante (textos o audios).

<img witdth="300" height="300" src="./img/convolucion.png">


Las convoluciones presentan varias ventajas:
- La reducción de conexiones (frente a las lineales) es una ventaja desde el punto de vista computacional.
- El criterio de proximidad obliga a que la red potencie la información relevante

Pytorch ofrece varios componentes basados en la técnica de la convolución.

https://pytorch.org/docs/stable/nn.html#convolution-layers


Uno de los componentes más empleados es Conv2D (que es una subclase de Module):

https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html#torch.nn.Conv2d


El componente de convolución requiere la definción de los siguientes argumentos:
- in_channels: Número de canales de la imagen (valores típicos son 1 o 3, segun la imagen sea monocroma o no.
- out_channels: Número de filtros que se desean generar.
- kernel_size: Tamaño del filtro. Valores frecuentes son 3x3, 5x5, 7x7.
- stride: el tamaño del desplazamiento del filtro
- padding: número de pixeles de relleno en el borde de la imagen.

Cada filtro se formaliza mediante una transformación lineal, por lo que los parámetros de este componente se corresponden con los pesos y sesgos asociados a cada uno de los filtros (out_channels).

Los parámetros de un componente nn.Conv2D pueden ser directamente consultados mediantes los atributos: _weight_ y _bias_
"""

# nn.Conv2d
num_canales=2
num_filas=5
num_columnas=5

# Entrada
num_ejemplares=1
inputs = torch.ones(num_ejemplares,num_canales, num_filas,num_columnas)
# inputs = torch.rand(num_ejemplares,num_canales, num_filas,num_columnas)

num_salidas=3  ## Número de filtros aplicados a la imagen
kernel_size=2
stride=1
conv2d=torch.nn.Conv2d(
    in_channels=num_canales,
    out_channels=num_salidas,
    kernel_size=kernel_size,
    stride=stride)

outputs = conv2d(inputs)

print("***********************")
print("---  Entrada")
print(inputs.size())
print(inputs)

print("***********************")
print("---  Salida")
print(outputs.size())
print(outputs)

print("-------- PARAMETROS  ------")
iter_par=conv2d.named_parameters()
for n,m in iter_par:
    print(n,m)

print("-------- ACCESO a los parámtros")
print(conv2d.weight[1])

"""### MaxPool2D

https://pytorch.org/docs/stable/nn.html#pooling-layers

Los componentes de reducción (pooling) son mecanismos para la reducción del tamaño de la entrada.

Suelen utilizarse en el tratamiento de imágenes en compañía de las convoluciones para potenciar el aprendizaje de las convoluciones.

https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html

La capa de Maxpol es un mecanismo de reducción que escoge el valor máximo de una zona rectángular (kernel)


<img witdth="300" height="150" src="./img/maxpool2d.png">

"""

## nn.MaxPool2D
num_canales=2
num_filas=6
num_columnas=6

num_ejemplares=1
inputs = torch.rand(num_ejemplares,num_canales, num_filas,num_columnas)

kernel_size=2
maxpool=torch.nn.MaxPool2d(kernel_size)
outputs = maxpool(inputs)

print("***********************")
print("---  Entrada")
print(inputs.size())
print(inputs)

print("***********************")
print("---  Salida")
print(outputs.size())
print(outputs)

"""### BatchNorm2d

https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html

La **normalización por lotes** (_batch normalization_) es una técnica que estabiliza y acelera el entrenamiento de redes profundas.

Se aplica **después de una convolución y antes de la función de activación**, normalizando la salida de cada canal:

$$\hat{x} = \frac{x - \mu_{\text{batch}}}{\sqrt{\sigma^2_{\text{batch}} + \varepsilon}}$$

y luego escala y desplaza con dos parámetros entrenables $\gamma$ y $\beta$:

$$y = \gamma\,\hat{x} + \beta$$

**Ventajas:**
- Reduce la sensibilidad a la tasa de aprendizaje.
- Actúa como regularizador (reduce la necesidad de Dropout en CNNs).
- Permite entrenar redes más profundas con más estabilidad.

**Parámetro principal:** `num_features` = número de canales de salida de la convolución anterior.

> ⚠️ Se comporta diferente según el modo:
> - `model.train()` → normaliza con la media/std del batch actual.
> - `model.eval()` → usa las medias/std acumuladas durante el entrenamiento (`running_mean`, `running_var`).
"""

import torch

num_canales_entrada = 1   # MNIST es monocromo
num_filtros = 8
kernel_size = 3
num_ejemplares = 2
alto = ancho = 28

inputs = torch.rand(num_ejemplares, num_canales_entrada, alto, ancho)

# Bloque típico: Conv2d → BatchNorm2d → ReLU
conv  = torch.nn.Conv2d(in_channels=num_canales_entrada, out_channels=num_filtros, kernel_size=kernel_size, padding=1)
bn    = torch.nn.BatchNorm2d(num_features=num_filtros)
relu  = torch.nn.ReLU()

out_conv = conv(inputs)
out_bn   = bn(out_conv)
out_relu = relu(out_bn)

print(f"Entrada:       {inputs.shape}")
print(f"Tras Conv2d:   {out_conv.shape}")
print(f"Tras BN:       {out_bn.shape}")
print(f"Tras ReLU:     {out_relu.shape}")

print(f"\nParámetros entrenables de BatchNorm2d (gamma y beta por canal):")
for name, param in bn.named_parameters():
    print(f"  {name}: {param.shape} — {param.numel()} parámetros")

print(f"\nEstadísticas acumuladas (no entrenables):")
print(f"  running_mean: {bn.running_mean}")
print(f"  running_var:  {bn.running_var}")

# Uso en un Sequential (patrón habitual en CNNs)
bloque = torch.nn.Sequential(
    torch.nn.Conv2d(1, 16, kernel_size=3, padding=1),
    torch.nn.BatchNorm2d(16),
    torch.nn.ReLU(),
    torch.nn.MaxPool2d(2),
)
print(f"\nBloque Conv+BN+ReLU+Pool: entrada {inputs.shape} → salida {bloque(inputs).shape}")

"""## Modelos preentrenados

### ¿Qué son los modelos preentrenados?

Un **modelo preentrenado** es una red neuronal que ya ha sido entrenada sobre un conjunto masivo de datos — normalmente **ImageNet**, con 1,2 millones de imágenes y 1000 categorías.

En lugar de inicializar sus pesos aleatoriamente, se parte de pesos que ya codifican conocimiento visual:
- **Capas tempranas** → Detectan bordes, colores y texturas simples.
- **Capas intermedias** → Combinan esos primitivos en formas y partes de objetos.
- **Capas finales** → Representan conceptos visuales de alto nivel.

**Ventajas** frente a entrenar desde cero:
- Requieren muchos menos datos etiquetados propios.
- Convergen más rápido durante el ajuste fino (_fine-tuning_).
- Alcanzan mayor precisión cuando el conjunto de datos es pequeño.

TorchVision incluye decenas de arquitecturas listas para usar:

| Familia | Modelos disponibles |
|---------|---------------------|
| **ResNet** | `resnet18`, `resnet34`, `resnet50`, `resnet101` |
| **VGG** | `vgg11`, `vgg16`, `vgg19` |
| **EfficientNet** | `efficientnet_b0` … `efficientnet_b7` |
| **MobileNet** | `mobilenet_v3_small`, `mobilenet_v3_large` |
| **Vision Transformer** | `vit_b_16`, `vit_l_16`, `vit_h_14` |

> 📖 Catálogo completo: https://pytorch.org/vision/stable/models.html
"""

from torchvision.models import resnet50, ResNet50_Weights

# DEFAULT selecciona automáticamente los mejores pesos disponibles
modelo_resnet = resnet50(weights=ResNet50_Weights.DEFAULT).to(device)
modelo_resnet.eval()

total = sum(p.numel() for p in modelo_resnet.parameters())
print(f"Total parámetros ResNet50: {total:,}")

# Vista compacta del primer nivel
print(modelo_resnet)

"""### Inspección de capas

Como vimos en la sección anterior, `print(model)`, `named_children()` y `named_modules()` funcionan igual con cualquier modelo de TorchVision. `named_modules()` es especialmente útil aquí para descubrir la ruta exacta de cada capa (p.ej. `"layer3.0.conv1"`) antes de registrar hooks o congelar pesos.

### Modificar la capa de clasificación

Por defecto, ResNet50 termina en una capa `fc` (_fully connected_) con **1000 salidas**, una por clase de ImageNet. Para adaptar el modelo a un problema propio basta con sustituirla:

```python
in_features = modelo.fc.in_features          # nº de entradas que espera la cabeza original
modelo.fc   = torch.nn.Linear(in_features, num_clases)
```

Una vez sustituida, hay dos estrategias de entrenamiento:

| Estrategia | Qué se entrena | Cuándo usarla |
|-----------|---------------|---------------|
| **Fine-tuning ligero** | Solo la nueva cabeza (`fc`) — congelar el resto | Pocos datos propios; el dominio es similar a ImageNet |
| **Reentrenamiento completo** | Todos los parámetros (backbone + cabeza) | Suficientes datos; dominio muy diferente a ImageNet |

En ambos casos el backbone **empieza** desde los pesos preentrenados, lo que acelera la convergencia respecto a inicializar todo aleatoriamente. En el notebook IMG.4 veremos cómo congelar capas selectivamente para el fine-tuning.

> ⚠️ El nombre del atributo de cabeza varía según la arquitectura:
> | Arquitectura | Atributo |
> |---|---|
> | ResNet | `fc` |
> | VGG, MobileNet, EfficientNet | `classifier` |
> | Vision Transformer (ViT) | `heads` |
>
> Usa `named_children()` para descubrirlo en cualquier modelo desconocido.
"""

# Reemplazar la capa final por una adaptada a nuestro problema (p. ej. 10 clases)
num_clases = 10

# Consultamos el número de entradas que espera la capa fc original
in_features = modelo_resnet.fc.in_features
print(f"Capa fc original:  in_features={in_features}, out_features={modelo_resnet.fc.out_features}")

# Sustitución: pesos del backbone intactos, sólo la nueva cabeza se inicializa
modelo_resnet.fc = torch.nn.Linear(in_features, num_clases)
print(f"Capa fc nueva:     in_features={in_features}, out_features={num_clases}")

# Comprobamos que el total de parámetros apenas cambia (la fc es muy pequeña en proporción)
total_nuevo = sum(p.numel() for p in modelo_resnet.parameters())
print(f"\nParámetros totales tras la sustitución: {total_nuevo:,}")

"""## **☞ Ejercicio entregable**: CNN con submódulos y forward dual

<img witdth="400" height="100" src="./img/cnn.png">

Diseña una red neuronal convolucional que cumpla los siguientes requisitos:

1. **Submódulo reutilizable** (`BloqueConv`): define un bloque Conv2d → BatchNorm2d → ReLU → MaxPool2d como subclase de `nn.Module`. Recibe como parámetros el número de canales de entrada y de salida.

2. **Red dual** (`CNNDual`): contiene **dos ramas independientes**, cada una formada por dos bloques `BloqueConv` apilados (submódulos). El método `forward` acepta **dos entradas** (`x0`, `x1`) y las procesa por su rama correspondiente. Las representaciones de ambas ramas se **concatenan** en la dimensión de canales antes de la capa de clasificación lineal.

3. **Prueba** con el corpus MNIST: para cada imagen del corpus, pasa la misma imagen por ambas ramas, obtén la predicción y muestra con matplotlib:
   - la imagen de entrada
   - los mapas de activación tras la primera capa de la rama 0 (un subplot por filtro)
   - la clase predicha

## **☞ Ejercicio entregable**: Visualización de convoluciones con modelo preentrenado

Usando el modelo **ResNet50** de TorchVision con pesos preentrenados en ImageNet:

1. Carga el modelo en modo `eval()` y muestra su arquitectura.
2. Registra un **forward hook** en dos capas convolucionales de distinto nivel de abstracción:
   - `conv1` — primera convolución (detecta bordes, colores, texturas simples)
   - `layer3[0].conv1` — convolución intermedia (detecta patrones más complejos)
3. Aplica el modelo a la imagen `./img/torreDelOro.jpg` (preprocesada con las transformaciones estándar de ImageNet: resize 224×224, normalización).
4. Muestra con matplotlib tres filas:
   - fila 1: imagen original (repetida para alinear columnas)
   - fila 2: los primeros 8 mapas de activación de `conv1`
   - fila 3: los primeros 8 mapas de activación de `layer3[0].conv1`
5. Compara visualmente ambas filas: ¿qué tipo de patrones extrae cada capa?

---

#### ¿Cómo obtener activaciones intermedias con `register_forward_hook`?

Cuando se ejecuta un modelo preentrenado con `model(x)`, PyTorch recorre todas las capas internamente y devuelve únicamente la salida final. Para acceder a la salida de una capa intermedia es necesario **interceptar** su cálculo durante el forward pass.

El mecanismo para esto son los **forward hooks**: funciones de Python que PyTorch llama automáticamente cada vez que una capa concreta termina su cálculo. Se registran así:

```python
def hook(module, input, output):
    # module: la capa que acaba de ejecutarse
    # input:  tupla con las entradas recibidas por la capa
    # output: tensor de salida producido por la capa  ← lo que nos interesa
    activaciones["nombre"] = output.detach()   # guardar una copia sin gradientes

capa.register_forward_hook(hook)
```

A partir de ese momento, cada vez que se llame a `model(x)`, el hook se ejecuta automáticamente al terminar esa capa y almacena su salida en el diccionario `activaciones`. El resto del forward pass continúa con normalidad.
"""