# -*- coding: utf-8 -*-
"""AINE 2026 - IMG.4 - Entrenamiento (ESCRIBE AQUI TU UVUS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5g-jJVX_Apj2iUb2of-vm0Sf7tIgzqR

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

**Escriba aquí su nombre y apellidos:**

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:
* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable")

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**

# IMÁGENES 4: ENTRENAMIENTO
Última modificación: 10 de marzo de 2026

---
**Contenido**

1. Diferenciación automática — `autograd`, `.backward()`, `torch.no_grad()`
2. Función de pérdida — `CrossEntropyLoss`
3. Optimización — descenso de gradiente, paso de actualización
4. Optimizadores — SGD, Adam
5. Entrenamiento — ciclo por época, planificador del ritmo de aprendizaje
6. Validación
7. Visualización del entrenamiento — curvas de pérdida y accuracy
8. Early stopping
9. ☞ **Ejercicio**: Comparación de optimizadores SGD y Adam
10. ☞ **Ejercicio**: Aprendizaje por transferencia

---
"""

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Dispositivo: {device}")

"""## Diferenciación automática


El método más empleado para el entrenamiento de las redes neuronales es la propagación hacia atrás
utilizando diferenciación automática. La diferenciación automática calcula los gradientes de los parámetros.

El entrenamiento comienza dando valores aleatorios a los parámetros

1. Criterio: Se evalúa los resultados obtenidos con los esperados mediante una función de pérdida (criterion)
2. Autograd: Se aplica diferenciación automática cuyo objetivo es calcular los gradientes (derivada respecto a la función de pérdida de todos los parámetros)
3. Optimización: Se reajustan los parámetros en función de los gradientes calculados

El ciclo criterio-autograd-optimización se repite (épocas) hasta alcanzar un modelo cuyos resultados se consideren óptimos.

### Autograd

https://pytorch.org/docs/stable/autograd.html

El paquete `torch.autograd` construye un grafo dirigido acíclico (DAG) con los cálculos del modelo para calcular gradientes mediante la regla de la cadena.

Los tensores relevantes para autograd disponen de los atributos:
- `requires_grad` — `True` si debe calcularse su gradiente
- `grad_fn` — referencia a la operación que generó el tensor (`None` en nodos hoja)
- `grad` — valor del gradiente (solo significativo en nodos hoja con `requires_grad=True`)
- `is_leaf` — `True` si el tensor es un parámetro (nodo hoja del grafo)

<img width="400" heigh="100" src="./img/grad_fn.png">
"""

# Atributos de los tensores relacionados con autograd
x = torch.randn(3,requires_grad=True)
print("-----------------------")
print("x=",x)
print(x.requires_grad)
print(x.is_leaf)
print(x.grad)
print(x.grad_fn)


# Pytorch sobrecarga operadores típicos (+,*,-, **, ...)
# Esta sobrecarga indirectamentes actualiza atributos (ej: grad_fn) con información necesaria para autograd
y1=2*x

print("-----------------------")
print("y1=",y1)
print(y1.requires_grad)
print(y1.is_leaf)
# AVISO: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed.
print(y1.grad)
print(y1.grad_fn)


y=y1**3+1
print("-----------------------")
print("y=",y)
print(y.requires_grad)
print(y.is_leaf)
# AVISO: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed.
print(y.grad)
print(y.grad_fn)

"""### Backward

El método `backward()` de `torch.autograd` recorre el grafo en sentido inverso y calcula los gradientes de todos los nodos hoja con `requires_grad=True`.

Dado $y=w\cdot x + b$ siendo $x=6$, $w=2$ y $b=3$, los gradientes obtenidos son:
- $dy/dx= w = 2$
- $dy/dw= x = 6$
- $dy/db= 1$

Aspectos clave a tener en cuenta:
- Se aplica sobre un **tensor escalar** (la función de pérdida siempre lo es).
- **Acumula** los gradientes en `.grad` en llamadas sucesivas → hay que ponerlos a cero con `optimizer.zero_grad()` antes de cada época.

"""

# Diferenciación automática (caso simple)
x = torch.tensor(6., requires_grad=True)

w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# y es un nodo intermedio (resultado de una operación) → grad_fn != None
y  = w * x + b

# retain_grad() permite acceder a .grad en tensores no hoja
y.retain_grad()

# Antes de backward: x, w, b son nodos hoja → grad_fn=None, grad=None
#                    y es nodo intermedio  → grad_fn=AddBackward0
print("--- Antes de backward ---")
print("x:  requires_grad=", x.requires_grad, " grad=", x.grad, " grad_fn=", x.grad_fn)
print("w:  requires_grad=", w.requires_grad, " grad=", w.grad, " grad_fn=", w.grad_fn)
print("b:  requires_grad=", b.requires_grad, " grad=", b.grad, " grad_fn=", b.grad_fn)
print("y:  requires_grad=", y.requires_grad, " grad=", y.grad, " grad_fn=", y.grad_fn)

y.backward()

# Después de backward: los gradientes se almacenan en los nodos hoja (x, w, b)
# dy/dx = w = 2,  dy/dw = x = 6,  dy/db = 1,  dy/dy = 1
print("\n--- Después de backward ---")
print("x:  dy/dx =", x.grad, " grad_fn=", x.grad_fn)
print("w:  dy/dw =", w.grad, " grad_fn=", w.grad_fn)
print("b:  dy/db =", b.grad, " grad_fn=", b.grad_fn)
print("y:  dy/dy =", y.grad, " grad_fn=", y.grad_fn)

# OJO: backward() acumular los gradientes en sucesivas ejecuciones
x = torch.tensor(1.0,requires_grad=True)
w = torch.tensor(3.0,requires_grad=True)

epochs = 3

for e in range(epochs):
    y = w*x
    loss = y.sum()
    loss.backward()
    print(x.grad)

    # Pone a cero el valor de los gradientes
    # x.grad.zero_()

"""### Desactivación



Tenemos varias estrategias para controlar el proceso de propagación atrás mediante la desactivación (o activación) de las neuronas. Tenemos varias alternativas que nos permiten modificar el valor de los atributo requires_grad y grad_fn.

- torch.Tensor.requires_grad_(boolean) es un operador _in\_place_ que modifica el valor del atributo requires_grad  
- torch.Tensor.detach() devuelve un tensor con requires_grad=False
- torch.no_grad() evita la construcción del grafo (ignora el valor de los atributos grad y grad_fn)

"""

x = torch.rand(2, requires_grad=False)
linear = torch.nn.Linear(len(x), 2)

# --- requires_grad_(False): desactiva el cálculo del gradiente en un parámetro ---
linear.bias.requires_grad_(False)
y = linear(x)
y.mean().backward()
print("requires_grad_() → w.grad:", linear.weight.grad, "  b.grad:", linear.bias.grad)

# --- detach(): desconecta la salida del grafo ---
linear2 = torch.nn.Linear(len(x), 2)
y2 = linear2(x).detach()        # y2 no tiene grad_fn
print("detach()         → grad_fn:", y2.grad_fn,
      "  w.grad:", linear2.weight.grad, "  b.grad:", linear2.bias.grad)

# --- no_grad(): evita construir el grafo en todo el bloque ---
linear3 = torch.nn.Linear(len(x), 2)
with torch.no_grad():
    y3 = linear3(x)              # grad_fn=None aunque los parámetros tengan requires_grad=True
print("no_grad()        → grad_fn:", y3.grad_fn,
      "  w.grad:", linear3.weight.grad, "  b.grad:", linear3.bias.grad)

"""### Modos

> **Recordatorio** (ver notebook IMG.3): Llamar a `modelo.train()` antes de entrenar y a `modelo.eval()` antes de validar. Esto activa/desactiva componentes como `Dropout` o `BatchNorm` según el contexto.

Durante el entrenamiento usaremos `modelo.train()` al inicio de cada época y `modelo.eval()` + `torch.no_grad()` en el paso de validación.

## Función de pérdida

Para comprobar la calidad de la clasificación de una red se comparan los resultados obtenidos $\text{logits}$ con los esperados $y$ mediante una función de pérdida $f_{loss}$ (criterion).

Ejemplo simple: Dado $y=(y_1,\dots,y_n)$  y $\text{logits}=(l_1,\dots,l_n)$
$$  f_{loss} =\sum (y_i - l_i)^2/n$$

La función de pérdida devuelve un número real. En general, cuanto más próximo sea a cero, será menor el error cometido.

El tensor resultado de esta función de pérdida es un tensor escalar que es el que se emplea en la propagación hacia atras.

Pytorch suministra varias funciones de pérdida (criterion)
https://pytorch.org/docs/stable/nn.html#loss-functions

En el caso de clasificación no binaria es frecuente usar `torch.nn.CrossEntropyLoss()`.

> ⚠️ **`CrossEntropyLoss` aplica `log_softmax` internamente.** Por eso la red devuelve _logits_ crudos (sin activación final) y **nunca** se debe aplicar `softmax` antes de pasarlos a la función de pérdida — hacerlo introduce un error silencioso que degrada el entrenamiento. Para obtener predicciones basta con `logits.argmax()`, sin necesidad de aplicar softmax.

NOTA: Las funciones de pérdida admiten entradas simples o múltiples.
"""

# Entrada
x = torch.rand(3, requires_grad=False)

# Salida deseada
y = torch.rand(2, requires_grad=False)

# Salida obtenida
linear=torch.nn.Linear(len(x),len(y))
logit=linear(x)

print("Entrada",x)
print("Salida obtenida:",logit)
print("Salida deseada:",y)

# Función de pérdida:
fn_loss = torch.nn.CrossEntropyLoss()
loss= fn_loss(logit,y)

print("Pérdida:",loss)

# Calcula la derivada de la función de pérdida respecto de todos los parámetros
loss.backward()

# Gradientes de los parámetros
w=linear.weight
b=linear.bias

print("------------------------------------")
print("w.grad=", w.grad)
print("b.grad =", b.grad)

"""## Optimización

La optimización del modelo consiste en modificar el valor de los parámetros con objeto de mejorar los resultados.

El paquete torch.optim ofrece un conjunto de algoritmos para la optimización.
Estos algoritmos suelen requerir en general dos parámetros:
- params (un iterable con el conjunto de parámetros sobre los que se aplica la optimización)
- lr (learning rate) Un valor real que se emplea para graduar el nivel de aprendizaje

Los optimizadores más comunes difieren en cómo utilizan el gradiente para actualizar los parámetros:

- **SGD** (_Stochastic Gradient Descent_): actualización simple proporcional al gradiente. Predecible y estable, pero requiere ajuste fino del `lr`. (https://pytorch.org/docs/stable/generated/torch.optim.SGD.html)
- **Adam**: combina momentum y tasa de aprendizaje adaptativa por parámetro. Suele converger más rápido con menos ajuste manual. ( https://pytorch.org/docs/stable/generated/torch.optim.Adam.html)


Las funciones de optimización incluyen dos métodos:
- step() actualiza los parámetros
- zero_grad() pone a cero el valor de los gradientes de los parámetros

"""

## Optimizadores

# Entrada
x = torch.rand(3, requires_grad=False)

# Salida deseada
y = torch.rand(2, requires_grad=False)

# Salida obtenida
linear=torch.nn.Linear(len(x),len(y))

# linear.train()
logit=linear(x)

# Función de pérdida
fn_loss = torch.nn.CrossEntropyLoss()
loss= fn_loss(logit,y)

print("Pérdida:",loss.item())

# Calcula la derivada de la función de pérdida respecto de todos los parámetros
loss.backward()

# Gradientes de los parámetros
print("------------------------------------")
w=list(linear.parameters())[0]
b=list(linear.parameters())[1]
print("w =", w)
print("w.grad =", w.grad)
print("b =", b)
print("b.grad = ", b.grad)

# Optimización
lr=1.0
opt=torch.optim.SGD(params=linear.parameters(),lr=lr)
opt.step()
opt.zero_grad()

print("------------------------------------")
w=list(linear.parameters())[0]
b=list(linear.parameters())[1]

print("w =", w)
print("w.grad =", w.grad)
print("b =", b)
print("b.grad =", b.grad)

"""## Entrenamiento

El entrenamiento consiste en ciclos de ejecución, calculo de la función de pérdida, cálculo de gradientes y optimización.

- Hay que tener en cuenta que Pytorch acumula los gradientes obtenidos en .grad por lo que debemos inicializarlos a cero en cada iteración.
- Antes de ejecutar el ciclo es conveniente establecer el modo train()

El valor de pérdida en las sucesivas épocas es un indicador de la mejora del modelo durante el entrenamiento.
"""

import numpy as np
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Subset

# --- Calcular mean y std reales de MNIST sobre píxeles en [0,1] ---
_raw = torchvision.datasets.MNIST(root="../datasets", train=True,
                                   transform=transforms.ToTensor(), download=True)
_loader = DataLoader(_raw, batch_size=1024, shuffle=False)
_mean = sum(X.mean() for X, _ in _loader) / len(_loader)
_std  = (sum(((X - _mean) ** 2).mean() for X, _ in _loader) / len(_loader)) ** 0.5
print(f"MNIST  mean={_mean:.4f}  std={_std:.4f}")

# --- Dataset MNIST normalizado con los valores reales ---
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((_mean.item(),), (_std.item(),))
])

train_dataset = torchvision.datasets.MNIST(root="../datasets", train=True,  transform=transform, download=True)
val_dataset   = torchvision.datasets.MNIST(root="../datasets", train=False, transform=transform, download=True)

# Subconjunto para agilizar la ejecución en clase
train_dataset = Subset(train_dataset, range(5000))
val_dataset   = Subset(val_dataset,   range(1000))

batch_size   = 128
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=batch_size, shuffle=False)

print(f"Entrenamiento : {len(train_dataset)} muestras, {len(train_loader)} lotes")
print(f"Validación    : {len(val_dataset)} muestras, {len(val_loader)} lotes")

# --- Modelo ---
modelo = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.Linear(28*28, 128),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.3),
    torch.nn.Linear(128, 10)     # 10 clases MNIST
).to(device)

fn_loss   = torch.nn.CrossEntropyLoss()
lr        = 1e-2
optimizer = torch.optim.SGD(modelo.parameters(), lr=lr)

# --- Funciones reutilizables en el resto del notebook ---

def train_epoch(loader, modelo, fn_loss, optimizer):
    """Una época de entrenamiento. Devuelve la pérdida media por lote."""
    modelo.train()
    total_loss = 0.0
    for X_batch, y_batch in loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        logit = modelo(X_batch)
        loss  = fn_loss(logit, y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

def eval_accuracy(loader, modelo):
    """Exactitud (accuracy) sobre un DataLoader."""
    modelo.eval()
    aciertos, total = 0, 0
    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            aciertos += (modelo(X_batch).argmax(1) == y_batch).sum().item()
            total    += len(y_batch)
    return aciertos / total

def eval_loss(loader, modelo, fn_loss):
    """Pérdida media sobre un DataLoader."""
    modelo.eval()
    total = 0.0
    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            total += fn_loss(modelo(X_batch), y_batch).item()
    return total / len(loader)

def train(epochs, train_loader, val_loader, modelo, fn_loss, optimizer, scheduler=None):
    """Entrena y devuelve listas de pérdida y exactitud por época."""
    tl = np.zeros(epochs); vl = np.zeros(epochs)
    ta = np.zeros(epochs); va = np.zeros(epochs)
    for epoch in range(epochs):
        tl[epoch] = train_epoch(train_loader, modelo, fn_loss, optimizer)
        if scheduler:
            scheduler.step()
        vl[epoch] = eval_loss(val_loader, modelo, fn_loss)
        ta[epoch] = eval_accuracy(train_loader, modelo)
        va[epoch] = eval_accuracy(val_loader,   modelo)
        print(f"Época {epoch+1}/{epochs}  "
              f"train_loss={tl[epoch]:.4f}  val_loss={vl[epoch]:.4f}  "
              f"train_acc={ta[epoch]:.3f}  val_acc={va[epoch]:.3f}")
    return tl, vl, ta, va

# --- Entrenamiento inicial ---
epochs = 3
train(epochs, train_loader, val_loader, modelo, fn_loss, optimizer)

"""### Planificador del ritmo de aprendizaje

Durante el entrenamiento conviene reducir progresivamente el ritmo de aprendizaje (_learning rate_) conforme el modelo se aproxima a la convergencia. El módulo `torch.optim.lr_scheduler` ofrece varias estrategias:

- `StepLR`: reduce el lr multiplicándolo por `gamma` cada `step_size` épocas.
- `ReduceLROnPlateau`: reduce el lr cuando una métrica (p.ej. la pérdida) deja de mejorar.
- `CosineAnnealingLR`: sigue un ciclo coseno.

El método `scheduler.step()` debe llamarse **al final de cada época**, después de `optimizer.step()`.

https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
"""

# Nuevo optimizador y scheduler sobre el mismo modelo
optimizer_sched = torch.optim.SGD(modelo.parameters(), lr=0.1)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer_sched, step_size=5, gamma=0.5)

# train_epoch ya gestiona modelo.train() internamente
for epoch in range(15):
    loss = train_epoch(train_loader, modelo, fn_loss, optimizer_sched)
    scheduler.step()
    print(f"Época {epoch+1:2d}  lr={scheduler.get_last_lr()[0]:.5f}  loss={loss:.4f}")

"""## Validación

La validación consiste en la ejecución del modelo sobre un conjunto de entradas.

Podemos medir la calidad del modelo atendiendo a su exactitud (Accuracy) que consiste en obtener la proporción de aciertos.

En este contexto, para mejorar el tiempo de respuesta
- Es aconsejable establecer el modo de ejecución eval() para evitar componentes irrelevantes desde el punto de vista de la clasificación
- Evitar la construcción del grafo con no_grad() pues no es necesario aplicar la propagación hacia atrás (backward)


"""

# Validación: eval_accuracy y eval_loss definidas en la celda de Entrenamiento
acc_train = eval_accuracy(train_loader, modelo)
acc_val   = eval_accuracy(val_loader,   modelo)
loss_val  = eval_loss(val_loader, modelo, fn_loss)

print(f"Exactitud entrenamiento : {acc_train:.3f}")
print(f"Exactitud validación    : {acc_val:.3f}")
print(f"Pérdida validación      : {loss_val:.4f}")

"""## Visualización del entrenamiento

Es buena práctica representar gráficamente la evolución de la **pérdida** (_loss_) y la **exactitud** (_accuracy_) a lo largo de las épocas, separando los datos de entrenamiento y validación:

- Si la pérdida de validación deja de bajar (o sube) mientras la de entrenamiento sigue bajando → **sobreajuste**.
- Curvas similares en ambos conjuntos indican buena generalización.

"""

import matplotlib.pyplot as plt

# Nuevo modelo desde cero para ver la evolución completa desde época 1
modelo_viz = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.Linear(28*28, 128),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.3),
    torch.nn.Linear(128, 10)
)
optimizer_viz = torch.optim.SGD(modelo_viz.parameters(), lr=1e-2)

epochs_viz = 10
tl, vl, ta, va = train(epochs_viz, train_loader, val_loader, modelo_viz, fn_loss, optimizer_viz)

ep = range(1, epochs_viz + 1)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

ax1.plot(ep, tl, label="Train")
ax1.plot(ep, vl, label="Val", linestyle="--")
ax1.set_title("Pérdida")
ax1.set_xlabel("Época")
ax1.legend()

ax2.plot(ep, ta, label="Train")
ax2.plot(ep, va, label="Val", linestyle="--")
ax2.set_title("Exactitud (Accuracy)")
ax2.set_xlabel("Época")
ax2.legend()

plt.tight_layout()
plt.show()

"""## Early stopping

El **early stopping** detiene el entrenamiento cuando la pérdida de validación (`val_loss`) no mejora durante un número de épocas consecutivas, llamado `patience`. Esto evita el sobreajuste y ahorra tiempo de cómputo.

La lógica es sencilla: en cada época se compara la `val_loss` con el mínimo registrado hasta ese momento. Si no mejora durante `patience` épocas seguidas, se detiene el entrenamiento y se restauran los pesos del mejor modelo.

"""

import copy

# Para provocar sobreajuste de forma visible usamos un modelo grande sin Dropout
# y un conjunto de entrenamiento muy pequeño (200 muestras)
train_es = DataLoader(Subset(train_dataset, range(200)), batch_size=32, shuffle=True)

modelo_es    = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.Linear(28*28, 512),   # capa grande → más capacidad → más fácil sobreajustar
    torch.nn.ReLU(),
    torch.nn.Linear(512, 10)       # sin Dropout para que el sobreajuste sea claro
)
optimizer_es = torch.optim.SGD(modelo_es.parameters(), lr=5e-2)

patience      = 3          # épocas sin mejora antes de parar
max_epochs    = 50
mejor_vl      = float("inf")
mejores_pesos = None
sin_mejora    = 0

for epoch in range(max_epochs):
    tl_e = train_epoch(train_es,   modelo_es, fn_loss, optimizer_es)
    vl_e = eval_loss(val_loader, modelo_es, fn_loss)
    print(f"Época {epoch+1:2d}  train_loss={tl_e:.4f}  val_loss={vl_e:.4f}")

    if vl_e < mejor_vl:
        mejor_vl      = vl_e
        mejores_pesos = copy.deepcopy(modelo_es.state_dict())
        sin_mejora    = 0
    else:
        sin_mejora += 1
        if sin_mejora >= patience:
            print(f"\nEarly stopping en época {epoch+1}  "
                  f"(val_loss sin mejorar {patience} épocas consecutivas)")
            break

modelo_es.load_state_dict(mejores_pesos)   # restaura el mejor modelo
print(f"Mejor val_loss: {mejor_vl:.4f}")

"""## **☞ Ejercicio entregable**: Comparación de optimizadores SGD y Adam

La elección del optimizador influye en la velocidad de convergencia y en la calidad del modelo final. El objetivo de este ejercicio es comparar empíricamente **SGD** y **Adam** entrenando el mismo modelo bajo las mismas condiciones de partida.

**Se pide:**

1. Crea dos instancias del mismo modelo (misma arquitectura). Copia los pesos del primer modelo al segundo con `copy.deepcopy` + `load_state_dict` para que **ambos partan del mismo estado inicial**.
2. Configura un optimizador `SGD(lr=1e-2)` para el primer modelo y `Adam(lr=1e-3)` para el segundo.
3. Entrena ambos modelos durante el mismo número de épocas usando la función `train` ya definida.
4. Representa en una misma figura las curvas de **pérdida** y **exactitud** de entrenamiento y validación para cada optimizador.
5. Comenta brevemente las diferencias observadas.

## **☞ Ejercicio entregable**: Aprendizaje por transferencia

El aprendizaje por transferencia (_Transfer Learning_) consiste en reutilizar un modelo ya entrenado en una tarea como punto de partida para otra tarea diferente, aprovechando las representaciones aprendidas.

Los pasos habituales son:

1. **Crear y entrenar un modelo base** (CNN simple) sobre el problema original (10 clases MNIST).
2. **Congelar** los parámetros del modelo base (`requires_grad=False`) para que no se modifiquen durante el nuevo entrenamiento.
3. **Adaptar la última capa** para que el número de salidas coincida con las clases del nuevo problema (5 clases: dígitos 0–4).
4. **Recrear el optimizador** filtrando solo los parámetros con `requires_grad=True` (la nueva capa), para que no intente actualizar los parámetros congelados.
5. **Entrenar únicamente la nueva capa** con los datos del nuevo problema.

**Se pide:**

1. **Definir un modelo CNN base** con dos bloques convolucionales y una cabeza clasificadora de 10 clases.
2. **Entrenarlo sobre MNIST** (10 clases).
3. **Congelar todos los parámetros** del modelo base (`requires_grad = False`). Muestra por pantalla el estado de `requires_grad` en cada capa **antes y después** de congelar para verificar el cambio.
4. **Sustituir la última capa** por una nueva capa lineal con 5 salidas (la nueva capa tendrá `requires_grad=True` por defecto). Recrear el optimizador filtrando únicamente los parámetros con `requires_grad=True`.
5. **Guardar una copia** de los pesos congelados con `.clone()` justo antes de entrenar.
6. **Entrenar el modelo adaptado** con datos filtrados a las clases 0–4.
7. **Verificar** tras el entrenamiento:
   - Los pesos congelados no han cambiado: compara cada uno con su copia usando `torch.equal()`.
   - La pérdida desciende durante el entrenamiento de la nueva capa.
"""