# -*- coding: utf-8 -*-
"""AINE 2026 - TXT.1 - Procesamiento del Lenguaje Natural-benmauflo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wyObfoMRQyXmdk-ReEJS9MxzP_VHtNpX

# **Análisis de Información No Estructurada**

## Máster en Ingeniería del Software: Cloud, Datos y Gestión TI

### Curso 2025-26

---
---

**Escriba aquí su nombre y apellidos:** Benjamin Ignacio Maureira Flores

Debes entregar este notebook con todo el trabajo que puedas completar antes de la fecha límite:
* Completar los ejercicios entregables (titulados "☞ Ejercicio entregable")

**Antes de entregar, rellena con tu nombre y apellidos la celda anterior, y cambia el nombre del notebook antes de entregarlo, sustituyendo la palabra "uvus" por tu usuario de la US).**

---



---

# TEXTOS 1: **Procesamiento del Lenguaje Natural**
Última modificación: febrero de 2026

La siguiente celda contiene una serie de dependencias que vamos a utilizar en este notebook. También se descargan algunos recursos que utilizaremos a lo largo del notebook.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter, defaultdict
import math
import spacy
from spacy.symbols import ADJ, PROPN, NOUN, VERB, AUX
from spacy.matcher import Matcher
import spacy.cli
import numpy as np
import textwrap
from sklearn.model_selection import train_test_split
import requests
import shutil
import os
from tqdm.auto import tqdm
from wordcloud import WordCloud

datos_basedir = "./datos/"

def download_file(url, basedir):
  with requests.get(url, stream=True) as r:
      if not os.path.isdir(basedir):
        os.makedirs(basedir)
      total_length = int(r.headers.get("Content-Length"))
      filename = url.split("/")[-1].split("?")[0]
      with tqdm.wrapattr(r.raw, "read", total=total_length, desc=filename) as raw:
          with open(basedir + filename, 'wb') as output:
              shutil.copyfileobj(raw, output)

download_file('https://www.dropbox.com/s/a2xzik0vyymvykw/prensa.csv?dl=1', datos_basedir)
download_file('https://www.dropbox.com/s/g8oqkwr2lxs3v82/senticon.es.xml?dl=1', datos_basedir)
download_file('https://www.dropbox.com/s/fvq8my7o0ucnvoa/spanish_movie_reviews.csv?dl=1', datos_basedir)

for modelname in ("es_core_news_lg",):
  print("\nDownloading", modelname)
  spacy.cli.download(modelname)

"""## 1. Introducción

El [**Procesamiento del Lenguaje Natural**](https://es.wikipedia.org/wiki/Procesamiento_de_lenguajes_naturales) (frecuentemente conocido por sus siglas en inglés: **NLP**, o en español: **PLN**) es un campo de las ciencias de la computación, inteligencia artificial y lingüística que estudia las interacciones entre las computadoras y el lenguaje humano (también llamado "lenguaje natural", en contraposición a los "lenguajes formales", como pueden ser los lenguajes de programación). En particular, se ocupa de cómo implementar algoritmos que procesen y analicen grandes cantidades de textos escritos en lenguaje natural. El PLN se ocupa de la formulación e investigación de mecanismos eficaces computacionalmente para la comunicación entre personas y máquinas por medio de lenguajes naturales.

Algunas de las tareas de las que se ocupa el PLN se han convertido en herramientas de preprocesado estándar para muchos sistemas que trabajan con textos. Algunas de estas tareas son las siguientes:

- Tokenization
- Sentence splitting
- POS tagging
- Chunking (shallow parsing)
- Dependency parsing
- Syntactic parsing
- Named-Entity Recognition and Classification

### 1.1. Origen de los textos

Los textos que serán objeto de estos análisis pueden proceder de distintas fuentes. En ocasiones, los tendremos disponibles en algún formato fácilmente procesable, por ejemplo en una base de datos o en un fichero csv. En otras ocasiones, puede que estemos interesados en procesar textos de la web o de redes sociales.

Si tenemos los textos en un csv, simplemente tenemos que cargarlos. Como ejemplo, carguemos los textos de un [corpus de críticas de cine en español](https://github.com/ITALIC-US/Spanish-Movie-Reviews):
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

movie_reviews_df = pd.read_csv(datos_basedir+ "spanish_movie_reviews.csv",delimiter=',',encoding='utf-8')
movie_reviews_df.dropna(inplace=True)
print(movie_reviews_df.info())

sns.countplot(x=movie_reviews_df.stars)
plt.xlabel('Puntuación')
plt.title('Nº de críticas por puntuación')

movie_reviews_df.head()

"""Si queremos procesar textos de la web, podemos hacer uso de [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/), que nos facilita el parseo y extracción de los contenedores de textos en los que estemos interesados. Por ejemplo, si queremos extraer el texto de un artículo de Wikipedia, podríamos hacerlo así:"""

import requests
from bs4 import BeautifulSoup

# URL de la página de la que quieres extraer el texto
url = 'https://es.wikipedia.org/wiki/Procesamiento_de_lenguajes_naturales'

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Para buscar un div por su ID
div_con_id = soup.find('div', id='mw-content-text')
texto_de_div_con_id = div_con_id.get_text() if div_con_id else 'Div no encontrado'
print(texto_de_div_con_id)

"""Es posible que necesitemos hacer este proceso no para una única página web, sino para un conjunto no conocido a priori de páginas. Para ello, se suelen utilizar los conocidos como scrappers o crawlers (por ejemplo, el mismo BeautifulSoup, o el más potente [Scrapy](https://scrapy.org/)), que nos permiten definir una serie de reglas de navegación para ir accediendo a distintas páginas a partir de una o varias iniciales. Por otra parte, si necesitamos obtener textos de redes sociales, lo  más habitual es utilizar alguna API que permita el acceso programático a la misma.

Tanto el uso de scrappers como el de APIs de redes sociales quedarán al margen del contenido de la asignatura (aunque pueden ser abordados en el proyecto entregable).

## 2. Procesamiento de textos con spaCy

En nuestra asignatura no abordaremos la implementación de algoritmos que resuelvan estas tareas, sino que aprenderemos a usar herramientas que las llevan a cabo, y veremos la utilidad que entrañan y algunas de sus posibles aplicaciones. Existen muchas librerías orientadas al procesamiento del lenguaje que incorporan soluciones a las tareas anteriores. Nosotros usaremos una relativamente reciente, con un gran acabado y eficiencia, llamada **spaCy**.

Una ventaja del uso de spaCy es que, además de resolver las tareas básicas de NLP enumeradas antes, tenemos disponibles modelos preentrenados para las principales lenguas, incluido el español. Esto no siempre es así: otras herramientas precisan disponer de grandes corpus de textos anotados convenientemente para llevar a cabo un proceso de entrenamiento y generación de los modelos necesarios. Aunque esto también se puede hacer con Spacy, disponemos de modelos preentrenados con bastante calidad con los que podemos empezar a funcionar desde el primer minuto. Puedes ver los modelos disponibles [aquí](https://spacy.io/usage/models).

Los ficheros que se descargan empaquetan los modelos necesarios para varias tareas.
"""

import spacy

print("Cargando modelo...")
nlp = spacy.load('es_core_news_lg')

"""La función de carga anterior nos devuelve una función de *pipeline*. Esto significa que el procesamiento de un texto determinado es tan simple como invocar a esa función pasándole el texto, lo que desencadenará la ejecución de una serie de analizadores secuencialmente (tokenizer, sentence splitter, POS tagging,...)."""

print("Procesando con Spacy el primer review del corpus de críticas de cine...")
doc = nlp(movie_reviews_df["review"][0])
print("Hecho.")

"""También podemos procesar un conjunto de textos de una sola vez. Esto tiene la ventaja de que internamente algunos de los componentes de los modelos son más eficientes cuando trabajan con paquetes de textos, en lugar de con los textos de uno en uno."""

print("Procesando con Spacy todo el dataset...")
docs = list(
    tqdm(     # Decoramos con tqdm para ver barra de progreso
        nlp.pipe(movie_reviews_df["review"], n_process=1),
        total=len(movie_reviews_df)
        )
    )
print("Hecho.")
print("Se han obtenido", len(docs), "documentos.")

"""---
### Oraciones y tokens

En los siguientes ejemplos de código se muestra cómo acceder a la información obtenida tras el procesamiento del texto. Usaremos el primero de los textos procesados:
"""

# Recorre frases, atributo sents
for i, sent in enumerate(docs[0].sents):
  print(f"Frase {i+1}: ",sent)

from itertools import islice # para recorrer los n primeros elementos de un iterador

# Recorre palabras (tokens)
for tok in islice(docs[0], 20):
    print(tok)
print("...")

# Las frases son vistas del documento (ofrecen la misma interfaz)
for i, sent in enumerate(islice(docs[0].sents, 5)):
    print("Frase", i+1)
    for tok in islice(sent, 5):
        print("\t", tok)
    print("\t ...")
print("...")

# Los tokens están etiquetados con información morfosintáctica
print("{:15} | {:15} | {:6}".format("Palabra", "Lema", "POS"))
print("------------------------------------------------")
for tok in islice(docs[0], 40):
    # Algunos campos de los tokens están representados por índices o constantes
    # para reducir el empleo de memoria. Si accedemos a dichos campos añadiendo la
    # barra baja, obtenemos la cadena correspondiente.
    print("{:15} | {:15} | {:6}".format(tok.text, tok.lemma_, tok.pos_))

"""Saquemos una lista de las distintas etiquetas [POS](https://universaldependencies.org/u/pos/) utilizadas por el modelo, y una lista de ejemplos de cada una. Intenta entender a qué categoría se refiere cada etiqueta (al menos las más comunes: nombre, adjetivo, verbo, ...)."""

# Mostrar un listado de las distintas etiquetas POS y algunos ejemplos de cada una:
from collections import defaultdict

pos_ejemplos = defaultdict(set)

for doc in docs:
  for tok in doc:
      pos_ejemplos[tok.pos_].add(tok.text)

for pos, ejemplos in sorted(pos_ejemplos.items()):
    print(pos+":\t", ', '.join(sorted(ejemplos)[:10]),"...")

"""Usando las etiquetas POS podemos fácilmente seleccionar determinado tipo de palabras del texto.

---
### Búsqueda de patrones con Matcher

Filtrando las palabras de las críticas de cine etiquetadas como nombre propio podemos encontrar nombres de directores, actores, personajes de ficción, lugares... Pero es común que dichas menciones estén formadas por más de una palabra. ¿Podríamos buscar entidades a partir de secuencias de palabras etiquetadas como nombre propio?

Para hacerlo, podemos utilizar Matcher, otra herramienta proporcionada por spaCy que nos permite buscar secuencias de tokens que concuerden con un patrón determinado:
"""

# Obtener secuencias de dos o tres palabras consecutivas etiquetadas como PROPN
from spacy.matcher import Matcher

matcher = Matcher(nlp.vocab)
matcher.add("Dos o tres PROPN consecutivos", [
      [{'POS': 'PROPN'}, {'POS': 'PROPN'}],
      [{'POS': 'PROPN'}, {'POS': 'PROPN'}, {'POS': 'PROPN'}]
    ])

# Para cada coincidencia encontrada por matcher, obtenemos
# una terna match_id, start, end. Con estos dos últimos valores
# podemos recuperar desde el documento los tokens correspondientes
# a la coincidencia.
contador = Counter(str(doc[match[1]:match[2]])
                  for doc in docs
                   for match in matcher(doc))

print("{:>25} | {:>10}".format("Nombre","Frecuencia"))
print("__________________________________________")
for entidad, frecuencia in contador.most_common(100):
    print("{:>25} | {:>10}".format(entidad, frecuencia))

"""Puedes ver las posibilidades que ofrece Matcher en esta guía: https://spacy.io/usage/rule-based-matching.

Para hacer patrones más complejos y poderlos depurar antes de incluirlos en tu código, puedes utilizar esta herramienta online: https://explosion.ai/demos/matcher.

### **☞ Ejercicio entregable**: Obtener secuencias de dos o más nombres propios

Repite el proceso anterior, pero modificando las reglas de Matcher para que se obtengan todas las apariciones de 2 o más nombres propios consecutivos.
"""

# TODO: Obtener secuencias de dos o más nombres propios consecutivos
from spacy.matcher import Matcher
from collections import Counter

matcher_propn = Matcher(nlp.vocab)

patron = [{'POS': 'PROPN'}, {'POS': 'PROPN', 'OP': '+'}]
matcher_propn.add("DosOMasPROPN", [patron])

contador_nombres = Counter(str(doc[match[1]:match[2]])
                           for doc in docs
                           for match in matcher_propn(doc))

print("{:>35} | {:>10}".format("Nombre", "Frecuencia"))
print("_________________________________________________")
for entidad, frecuencia in contador_nombres.most_common(20):
    print("{:>35} | {:>10}".format(entidad, frecuencia))

"""---
### Reconocimiento de entidades nombradas
Una forma mejor de hacer lo anterior es usar el reconocimiento de entidades nombradas (NER, por sus siglas en inglés: Named-Entity Recognition). De esta forma, las entidades encontradas serán conjuntos de palabras que "*funcionan como*" nombres propios, pero que no necesariamente son todas ellas nombres propios; por ejemplo, "El Código da Vinci", que es el título de una película, incluye la palabra "El", que no es un nombre propio, pero que forma parte del nombre de la película.

Por otra parte, la herramienta NER también clasifica las entidades encontradas por tipo. Observa la información contenida en los atributos de cada una de las entidades que obtenemos (text, start_char, end_char, ...):
"""

# Reconocimiento de entidades

import textwrap # Para formatear el texto mostrado a un ancho determinado

print("Texto usado para la prueba:\n", textwrap.fill(str(docs[100]), 80), "\n")
print("{:<50} {:>5} {:>5} {:>5} {:>10}".format("Entidad", "start", "end", "TIPO", "root"))
print("________________________________________________________________________________")
for ent in islice(docs[100].ents,5):
    print("{:<50} {:>5} {:>5} {:>5} {:>10}".format(ent.text, ent.start_char, ent.end_char, ent.label_, ent.root.text))

"""---
Saquemos una tabla con el número de entidades encontradas en el texto de cada tipo, y mostremos las 30 entidades más frecuentes de cada tipo:
"""

# Sacar una lista con el número de entidades por tipo
contador = Counter(ent.label_
                   for doc in docs
                   for ent in doc.ents)
print("{:>5} | {:>10}".format("Tipo","Frecuencia"))
print("_____________________________________")
for tipo, frecuencia in contador.items():
    print("{:>5} | {:>10}".format(tipo, frecuencia))

# Sacar listas con las 30 entidades más frecuentes de cada tipo
entidades_por_tipo = {}
for tipo in ["PER", "LOC", "ORG", "MISC"]:
    entidades_por_tipo[tipo] = Counter(ent.text
                                       for doc in docs
                                       for ent in doc.ents
                                       if ent.label_ == tipo)
d = {tipo: entidades.most_common(30)
     for tipo, entidades in entidades_por_tipo.items()}
df = pd.DataFrame(data=d)
df

"""Lee las listas con detenimiento y trata de encontrar errores. ¿Qué tipo de entidades acumula más errores?

### **☞ Ejercicio entregable**: Temas del día en El País

Buscar todas las entidades (y sus frecuencias) que aparecen nombradas en los textos de las noticias enlazadas en la página principal de El País. No utilizar las entidades de tipo MISC.

Inspeccione la página principal de la web para encontrar algún elemento que le permita recopilar todos los enlaces a las noticias. Luego, para cada uno de estos enlaces, extraiga el texto del artículo principal, de forma similar a como hicimos en el ejercicio anterior, y procéselo con spaCy para detectar las entidades nombradas.
"""

import requests
from bs4 import BeautifulSoup

def extrae_re(url, nlp):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    div_con_id = soup.find('div', class_='a_c clearfix')
    texto = div_con_id.get_text() if div_con_id else ''

    if texto:
        doc = nlp(texto)
        return [ent.text for ent in doc.ents if ent.label_ != "MISC"]
    else:
        return []

# Realiza la petición a la página web
response = requests.get("https://elpais.com/")

1# Crea una instancia de BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Encuentra todos los elementos h2 con la clase 'c_t'
h2_elements = soup.find_all('h2', class_='c_t')

# Extrae las URLs de los enlaces dentro de esos h2
urls = [link['href'] for h2 in h2_elements for link in h2.find_all('a')]

contador = Counter()
for url in tqdm(urls):
    contador.update(extrae_re(url, nlp))

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Generar la nube de palabras
wordcloud = WordCloud(background_color ='white').generate_from_frequencies(contador)

# Visualizar la nube de palabras con Matplotlib
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')  # No mostrar los ejes para una visualización más limpia
plt.show()

"""---
### Análisis sintáctico
Veamos ahora dos tipos de análisis realizados por el pipeline de Spacy de caracter sintáctico (es decir, relacionados con las relaciones sintácticas entre las palabras que componen las oraciones). Podemos iterar sobre los sintagmas nominales encontrados en el texto (este tipo de análisis se denomina **chunking**, aunque en Spacy sólo tenemos **noun chunking**):
"""

# Sintagmas nominales

print("Texto usado para la prueba:\n", textwrap.fill(str(docs[0])[:300]+"...", 80), "\n")
print("{:15} | {:10}".format("Sintagma", "Núcleo"))
print("____________________________")
for chunk in islice(docs[0].noun_chunks,20):
      print("{:15} | {:10}".format(chunk.text, chunk.root.text))

"""También podemos acceder a todas las dependencias sintácticas encontradas entre las palabras de las oraciones."""

# Árbol de dependencias sintácticas (dependency parsing)

frase = next(islice(docs[100].sents, 4, None)) # Accedemos a la frase número 4 del review 100
print(frase,"\n");
print("{:10} | {:8} | {:12} | {:20} | {}".format("Palabra", "DEP", "Padre (head)", "Hijos (children)", "Subárbol (subtree)"))
print("___________________________________________________________________________________________")
for token in frase:
    print("{:10} | {:8} | {:12} | {:20} | {}".format(token.text, token.dep_, token.head.text,
          ','.join([child.text for child in token.children]), ' '.join(t.text for t in token.subtree)))

# Representación del árbol
from spacy import displacy
displacy.render(frase, style='dep', jupyter=True)

"""Como puedes observar, las dependencias sintácticas forman un árbol entre las palabras. El árbol de dependencias sintácticas es una versión simplificada del clásico árbol sintáctico. En un análisis sintáctico completo, las palabras se agrupan en sintagmas y otras estructuras de frase, que a su vez se van agrupando hasta llegar a la raíz del árbol, que es la oración. Sin embargo, en el análisis de dependencias, las relaciones se establecen únicamente entre las palabras.

Con el paso de los años, se ha observado que este tipo de análisis sintáctico (el de dependencias) es más sencillo y útil para la mayoría de los problemas de tratamiento de textos.

## **☞ Ejercicio entregable**: Búsqueda de adjetivos relacionados con entidades

Queremos obtener listas de los adjetivos que aparecen en los textos de los reviews relacionados con las entidades con nombre de tipo Persona.

Intenta localizar sólo los adjetivos que cuelgan directamente de algunos de los tokens que conforman cada una de las entidades de tipo Persona de los reviews. Dada una entidad, hay que buscar entre los hijos que cuelgan directamente de cada uno de los tokens de dicha entidad, con una relación de dependencia de tipo ``amod`` o ``appos``.

La función que se pide debe devolver un diccionario en el que las claves serán las entidades de tipo persona (en formato cadena de texto), y los valores asociados serán listas de los adjetivos encontrados (también en formato cadena de texto).
"""

# Implementa aquí tu función
from spacy.tokens import Doc

def extrae_adjetivos_entidades(docs: list[Doc]) -> dict:
    '''
    Busca adjetivos que estén relacionados con las entidades de tipo Persona,
    mediante una relación de dependencia de tipo amod o appos.
    Devuelve un diccionario {str: [str]}
    '''
    propiedades = defaultdict(list)

    for doc in docs:
        for ent in doc.ents:
            if ent.label_ == "PER":
                for token in ent:
                    for child in token.children:
                        if child.dep_ in ("amod", "appos") and child.pos_ == "ADJ":
                            propiedades[ent.text].append(child.lemma_.lower())

    return dict(propiedades)

# Test de la función extrae_adjetivos_entidades
propiedades = extrae_adjetivos_entidades(docs)

# Mostramos los adjetivos para Emily Mortimer
print("Emily Mortimer:")
for adjetivo in propiedades["Emily Mortimer"]:
  print("\t", adjetivo)
print("================================")

# Mostramos las 10 entidades con más calificativos
print("\nLas 10 entidades con más calificativos distintos:")
for entidad, _ in sorted(propiedades.items(), key = lambda t:len(set(t[1])), reverse=True)[:10]:
    if propiedades[entidad]:
        print("{}:".format(entidad))
        for propiedad in set(propiedades[entidad]):
            print("\t{}".format(propiedad))

import requests
from bs4 import BeautifulSoup

def extrae_re_adjetivos(url: str):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    div_con_id = soup.find('div', class_='a_c clearfix')
    texto = div_con_id.get_text() if div_con_id else ''

    if texto:
        doc = nlp(texto)
        return extrae_adjetivos_entidades([doc])
    else:
        return {}

# Realiza la petición a la página web
response = requests.get("https://elpais.com/")

# Crea una instancia de BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Encuentra todos los elementos h2 con la clase 'c_t'
h2_elements = soup.find_all('h2', class_='c_t')

# Extrae las URLs de los enlaces dentro de esos h2
urls = [link['href'] for h2 in h2_elements for link in h2.find_all('a')]

propiedades = defaultdict(list)
for url in tqdm(urls):
    for entidad, adjetivos in extrae_re_adjetivos(url).items():
        propiedades[entidad].extend(adjetivos)


for entidad, adjetivos in sorted(propiedades.items(), key=lambda t:len(t[1]), reverse=True)[:10]:
    print("{}:".format(entidad))
    for propiedad in propiedades[entidad]:
        print("\t{}".format(propiedad))

"""---

## **☞ Ejercicio entregable**: Cálculo de la polaridad de las opiniones sobre entidades

Ahora que tenemos adjetivos que se refieren a las entidades, hagamos un cálculo de opinión basado en la polaridad de dichos adjetivos. Queremos responder a la pregunta: ¿qué tipo de opiniones contienen nuestros reviews de cine sobre las personas que se nombran?

Vamos a cargar un recurso llamado [ML-Senticon](https://github.com/ITALIC-US/ML-Senticon) que contiene estimaciones de polaridad a nivel de palabras, y usaremos esas estimaciones para calcular una media de la "positividad" o "negatividad" de las opiniones expresadas.

(Tenga en cuenta que es un acercamiento muy naif, más adelante probaremos con técnicos más potentes)
"""

# ML-Senticon
import xml.etree.ElementTree as ET
from spacy.symbols import ADJ, ADV, NOUN, VERB

def carga_ml_senticon(ruta=datos_basedir + 'senticon.es.xml', niveles = {1,2,3,4,5,6,7,8}):
    senticon = {}
    tree = ET.parse(ruta)
    root = tree.getroot()
    for level in root:
        if int(level.attrib['level']) in niveles:
            for polarity in level:
                for word in polarity:
                    palabra_pos = word.text.strip() + "_" + word.attrib['pos']
                    polaridad = float(word.attrib['pol'])
                    senticon[palabra_pos] = polaridad
    return senticon

SENTICON = carga_ml_senticon()
print("ML-Senticon: {} entradas cargadas.".format(len(SENTICON)))

print("\nFragmento de las entradas del lexicon:")
for palabra_pos, polaridad in islice(SENTICON.items(),20):
    print("\t",palabra_pos, polaridad)
print("\t ...")

"""Calcula **la suma de las polaridades de los adjetivos de cada entidad**, y muestra una lista con las 20 con peor puntuación y las 20 con mejor puntuación."""

# TODO: Hazlo una vez resuelto el ejercicio de extracción de adjetivos

propiedades_cine = extrae_adjetivos_entidades(docs)

polaridad_entidades = {}

for entidad, adjetivos in propiedades_cine.items():
    suma_polaridad = 0
    for adj in adjetivos:
        clave_senticon = f"{adj}_a"

        if clave_senticon in SENTICON:
            suma_polaridad += SENTICON[clave_senticon]

    polaridad_entidades[entidad] = suma_polaridad

entidades_ordenadas = sorted(polaridad_entidades.items(), key=lambda x: x[1])

print("### Las 20 entidades con PEOR puntuación (más negativas) ###")
for entidad, pol in entidades_ordenadas[:20]:
    print(f"{entidad}: {pol:.3f}")

print("\n### Las 20 entidades con MEJOR puntuación (más positivas) ###")
for entidad, pol in reversed(entidades_ordenadas[-20:]):
    print(f"{entidad}: {pol:.3f}")

"""Haz un análisis crítico de este ejercicio. ¿Qué cosas se te ocurren que se podrían mejorar? ¿Qué fallos, simplificaciones o deficiencias observas en las soluciones planteadas?"""